### ISSUE TITLE
v2 bug: StringSliceFlag not work

### ISSUE THREAD

**Issue by heyanlong** [urfave/cli#1003]
e.g.
```shell
go run main.go --test=a,b,c,d
```
output
```golang
[]string{"a,b,c,d"}
```
expect
```golang
[]string{"a", "b", "c", "d"}
```

**Comment by lynncyrin** [comment]
@heyanlong here's a usage example for `StringSliceFlag` https://github.com/urfave/cli/issues/910#issuecomment-542353576

I'm sorry it's confusing! I'll make an issue for adding an example to the docs.

**Comment by lynncyrin** [comment]
To fully re-create your example, instead of this

```
go run main.go --test=a,b,c,d
```

what you need is this

```
go run main.go --test a --test b --test c --test d
```
