### ISSUE TITLE
Codecov is still commenting on PRs 🙄

### ISSUE THREAD

**Issue by coilysiren** [urfave/cli#1020]
via https://github.com/urfave/cli/pull/1019#issuecomment-569253463

https://github.com/urfave/cli/pull/979 didn't work I guess 😭

**Comment by saschagrunert** [comment]
We could try something like this:
https://github.com/cri-o/cri-o/blob/master/.codecov.yml

We use this config to have only a very short comment on PRs like this:
https://github.com/cri-o/cri-o/pull/3045#issuecomment-565188431

**Comment by meatballhat** [comment]
I consider this resolved now. Please holler if you think otherwise 💖
