### ISSUE TITLE
How to represent the dynamic value in cli?

### ISSUE THREAD

**Issue by AchalaSB** [urfave/cli#1034]
Hi,
I need an approach to achieve my use-case using this package

I'm able to manage subcommands in the cli using this package(V1 version )
It is working like this `test hello compile` 

**Requirement**: 
Now I want to add another argument. like this  `test hello details <hash_of _the_code>`

`<hash_of _the_code>` is dynamic. How can I add it in cli? 
The method I used  for other command is to add field `Name: "string"` to get N subcommands,
 but in this case I need to get details using the hash. So it can't be a static name.

How can I achieve this? 

thanks

**Comment by lynncyrin** [comment]
@AchalaSB you can pass it in as an argument. [In this example](https://github.com/urfave/cli/blob/master/docs/v1/manual.md#arguments) `c.Args().Get(0)` is getting the first argument, which would be `<hash_of _the_code>` in your case.
