### ISSUE TITLE
maint: master is failing

### ISSUE THREAD

**Issue by lynncyrin** [urfave/cli#1038]
source:

- https://github.com/urfave/cli/pull/1037
- https://github.com/urfave/cli/pull/1037/checks?check_run_id=382594792
- `node_modules/.bin/markdown-toc: no such file or directory`

**Comment by asahasrabuddhe** [comment]
Will check this out :)

**Comment by asahasrabuddhe** [comment]
@lynncyrin I have updated #1037 to make the tests pass.

**Comment by lynncyrin** [comment]
Closed via https://github.com/urfave/cli/pull/1037
