### ISSUE TITLE
v2 bug: generated manpage has error in metadata

### ISSUE THREAD

**Issue by zhsj** [urfave/cli#1040]
## my urfave/cli version is

master

## Checklist

* [ ] Are you running the latest v2 release? The list of releases is [here](https://github.com/urfave/cli/releases).
* [ ] Did you check the manual for your release? The v2 manual is [here](https://github.com/urfave/cli/blob/master/docs/v2/manual.md)
* [ ] Did you perform a search about this problem? Here's the [Github guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## Dependency Management

- [ ] My project is using go modules.
- [ ] My project is using vendoring.
- [ ] My project is automatically downloading the latest version.
- [ ] I am unsure of what my dependency management setup is.

## Describe the bug

Take the manpage in testdata, `man -l testdata/expected-doc-full.man`

![image](https://user-images.githubusercontent.com/227180/72342948-ac683d00-3708-11ea-9344-b76032a4334e.png)

## To reproduce

Describe the steps or code required to reproduce the behavior

## Observed behavior

What did you see happen immediately after the reproduction steps above?

## Expected behavior

What would you have expected to happen immediately after the reproduction steps above?

The manpage is rendered correctly, like most manpages. For example, if you read the manpage of `man ls`

![image](https://user-images.githubusercontent.com/227180/72343093-0b2db680-3709-11ea-9f60-383e496218b3.png)

## Additional context

If the issue relates to a specific open source Github repo, please link that repo here.

If you can reproduce this issue with a public CI system, please link a failing build here.

## Want to fix this yourself?

We'd love to have more contributors on this project! If the fix for this bug is easily explained and very small, free free to create a pull request for it.
## Run `go version` and paste its output here

```
# paste `go version` output in here
```

## Run `go env` and paste its output here

```
# paste `go env` output in here
```

**Comment by saschagrunert** [comment]
Hey @zhsj, this might be an issue with our markdown doc template. The `greet(8)()` was not reproducible for me right now. Which kind of settings for the app did you use?

**Comment by zhsj** [comment]
> Hey @zhsj, this might be an issue with our markdown doc template. The `greet(8)()` was not reproducible for me right now. Which kind of settings for the app did you use?

The screenshot is taken from https://github.com/urfave/cli/blob/master/testdata/expected-doc-full.man run command `man -l path/to/file`

**Comment by saschagrunert** [comment]
Got it, fix is incoming.
