### ISSUE TITLE
how to stop a cli.App

### ISSUE THREAD

**Issue by bestgopher** [urfave/cli#1042]
## my question is...

i want to stop a cli.App by codes。what should i do？

**Comment by lynncyrin** [comment]
I'm not 100% certain this is the answer you're looking for, but I generally stop the app by any of these methods:

- add `return nil` inside of your `Action` function
- add a `log.Fatal` anywhere
- add an `os.Exit` anywhere

does that help @bestgopher ?

**Comment by lynncyrin** [comment]
♻️ closing as stale ♻️
