### ISSUE TITLE
altsrc doesnt set zero-values

### ISSUE THREAD

**Issue by eyudkin** [urfave/cli#1050]
## my urfave/cli version is

V2.1.1

## Dependency Management

- [+ ] My project is using go modules.

## Describe the bug

Parsing integer value from source will not set it if its == 0. (i have a case, when my default value was "1", but I wanted to set "0" via config)
It occurs here:
```
// ApplyInputSourceValue applies a int value to the flagSet if required
func (f *IntFlag) ApplyInputSourceValue(context *cli.Context, isc InputSourceContext) error {
	if f.set != nil {
		if !(context.IsSet(f.Name) || isEnvVarSet(f.EnvVars)) {
			value, err := isc.Int(f.IntFlag.Name)
			if err != nil {
				return err
			}
                        // OCCURS HERE, if value ==0 it will not be set
			if value > 0 {
				for _, name := range f.Names() {
					_ = f.set.Set(name, strconv.FormatInt(int64(value), 10))
				}
			}
		}
	}
	return nil
}
```

## To reproduce

To parse any int flag with zero value from config (probably works also for booleans, empty strings, etc - I didnt check)

## Observed behavior

altsrc doesnt set a value from config, I have a default value instead.

## Expected behavior

altsrc should set a value from config even if it is zero-value

## Run `go version` and paste its output here

```
go version go1.13.4 linux/amd64
```

## Run `go env` and paste its output here

```
GO111MODULE="auto"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/eugene/.cache/go-build"
GOENV="/home/eugene/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY="github.com/myrepo"
GONOSUMDB="github.com/myrepo"
GOOS="linux"
GOPATH="my-gopath"
GOPRIVATE="github.com/myrepo"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/path-to-project/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build435723549=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by lynncyrin** [comment]
Heya! We are planning on completely rewriting `altsrc` for v3, so its unlikely that a maintainer will get to this issue! I'm marking it as `help wanted` for any other contributor that wants to help, though 🙏

**Comment by dearchap** [comment]
This has been fixed as part of multiple PRs over past couple of months. Works fine now.
