### ISSUE TITLE
v2 feature: print text to indicate when a flag allow multiple values

### ISSUE THREAD

**Issue by tredoe** [urfave/cli#1066]
## Checklist

* [x] Are you running the latest v2 release? 
* [x] Did you check the manual for your release?
* [x] Did you perform a search about this feature?

## What problem does this solve?

- need to print a text to know when a flag is a slice (allow multiple values)

## Solution description

I would want that after of the usage message were printed a text like i.e. `(multiple)`

**Comment by lynncyrin** [comment]
I'm surprised that we don't do this already!

Something like `(accepts multiple inputs)` sounds perfect

**Comment by meatballhat** [comment]
Actually closed by #1208 yay
