### ISSUE TITLE
`go vet` errors

### ISSUE THREAD

**Issue by fern4lvarez** [urfave/cli#107]
Basically,

```
$ go vet ./...
app_test.go:46: cli.StringFlag composite literal uses unkeyed fields
cli_test.go:50: cli.StringFlag composite literal uses unkeyed fields
cli_test.go:60: cli.StringFlag composite literal uses unkeyed fields
cli_test.go:70: cli.StringFlag composite literal uses unkeyed fields
exit status 1
```

**Comment by binodluitel** [comment]
I am still getting this error, am I missing something?

/vagrant/src/code.softlayer.local/softlayer/nidp on master* make
==> Checking sanity
go fix ./...
go vet ./...
main.go:13: github.com/codegangsta/cli.StringFlag composite literal uses unkeyed fields
exit status 1
make: *** [sane] Error 1

{code}
app := cli.NewApp()
    app.Name = "Data Processor"
    app.Usage = "Insert data from a queue data stream into Cassandra"
    app.Flags = []cli.Flag {
        cli.StringFlag{"server, s", "localhost", "RabbitMQ server hostname"},
    }

    app.Action = func(c *cli.Context) {
        runApp(c)
    }
    app.Run(os.Args)
{/code}

**Comment by jszwedko** [comment]
@binodluitel that indicates that your code is not passing `go vet`, not `codegangsta/cli`. In this case, the error message is accurate that you aren't keying your struct fields.

**Comment by binodluitel** [comment]
Gotcha, thanks
Incase anyone will anyone needs it, this is what @jszwedko meant
```
    app.Flags = []cli.Flag {
        cli.StringFlag{
            Name: "server, s",
            Value: "localhost",
            Usage: "RabbitMQ server hostname",
        },
    }
```
