### ISSUE TITLE
Add blank line before of every category

### ISSUE THREAD

**Issue by tredoe** [urfave/cli#1070]
## Checklist

* [x] Are you running the latest v2 release? 
* [x] Did you check the manual for your release?
* [x] Did you perform a search about this feature?

## What problem does this solve?

- At the help, the command categories are printed just after of a command avoiding a visual separation between commands and commands groups.

## Solution description

Add a blank line before of add the name of every category, just like were done at v1.

**Comment by lynncyrin** [comment]
Makes sense @tredoe! Feel free to contribute a PR for this.

**Comment by dearchap** [comment]
This is the output I see with categories

```
$ go run . 
NAME:
   test5 - app.Usage

USAGE:
   test5 [global options] command [command options] [arguments...]

VERSION:
   app.Version

COMMANDS:
   help, h  Shows a list of commands or help for one command
   cat1:
     command1  command1.Usage
     command3  command3.Usage
   cat2:
     command2  command2.Usage

GLOBAL OPTIONS:
   --hello value  
   --help, -h     show help (default: false)
   --version, -v  print the version (default: false)
```

Dont see any real need for a visual separation.
