### ISSUE TITLE
q: App.Writer is being set twice

### ISSUE THREAD

**Issue by Nokel81** [urfave/cli#1096]
I was wondering why there is two instance of setting `*App.Writer` to `os.Stdout` in `*App.Setup()`? 

- https://github.com/urfave/cli/blob/master/app.go#L161
- https://github.com/urfave/cli/blob/master/app.go#L199

And `*App.ErrWriter` is not being set at all. Is that because it is going to be deprecated?

**Comment by lynncyrin** [comment]
> I was wondering why there is two instance of setting `*App.Writer` to `os.Stdout` in `*App.Setup()`?

🤷‍♀ 

> And `*App.ErrWriter` is not being set at all. Is that because it is going to be deprecated?

🤷‍♀

**Comment by lynncyrin** [comment]
@Nokel81 if you would like to change either of those behaviors, I would happily review PRs!
