### ISSUE TITLE
q: Is there any way to make `help` show subcommands as well?

### ISSUE THREAD

**Issue by selfish** [urfave/cli#1108]
## Subcommands in Help

Assume that I have an app named `app` with command `foo`, with subcommand `bar`.

```
[]*cli.Command{
		{
		Name:    "foo",
		Subcommands: []*cli.Command{
			{
				Name:    "bar",
			}
		},
	}
}
```

If I run my app help, I'd see:
```
COMMANDS:
   foo, f  foo help text
   help, h     Shows a list of commands or help for one command
```

similar to categories view, I would like to see the full "tree" of commands on my main help section, so something more like:
```
COMMANDS:
    foo, f  foo help text
        bar foobar
        baz foobaz
```

This is even though the usage is still `$ app foo bar`.

Thank you!

**Comment by cgedwar2** [comment]
It would be nice if these templates were exposed or at least shared output with the `cli command help` template. As it stands the help is very difficult to normalize across all the different exposed flags/commands.
