### ISSUE TITLE
install FAILURE - CANNOT FIND PACKAGE 

### ISSUE THREAD

**Issue by nicks6240** [urfave/cli#1110]
## my urfave/cli version is
can't install 

windows:

> 
> set GO111MODULE=on && go get github.com/urfave/cli/v2
> package github.com/urfave/cli/v2: cannot find package "github.com/urfave/cli/v2" in any of:
>         C:\Go\src\github.com\urfave\cli\v2 (from $GOROOT)
>         C:\Users\user\Documents\goprojects\src\github.com\urfave\cli\v2 (from $GOPATH)

_**( Put the version of urfave/cli that you are using here )**_

## Checklist

* [ ] Are you running the latest v2 release? The list of releases is [here](https://github.com/urfave/cli/releases).
* [ ] Did you check the manual for your release? The v2 manual is [here](https://github.com/urfave/cli/blob/master/docs/v2/manual.md)
* [ ] Did you perform a search about this problem? Here's the [Github guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## Dependency Management

- [ ] My project is using go modules.
- [ ] My project is using vendoring.
- [ ] My project is automatically downloading the latest version.
- [ ] I am unsure of what my dependency management setup is.

## To reproduce

Describe the steps or code required to reproduce the behavior

## Observed behavior

What did you see happen immediately after the reproduction steps above?

## Expected behavior

What would you have expected to happen immediately after the reproduction steps above?

## Additional context

If the issue relates to a specific open source Github repo, please link that repo here.

If you can reproduce this issue with a public CI system, please link a failing build here.

## Want to fix this yourself?

We'd love to have more contributors on this project! If the fix for this bug is easily explained and very small, free free to create a pull request for it.
## Run `go version` and paste its output here

```
# paste `go version` output in here
```

## Run `go env` and paste its output here

```
# paste `go env` output in here
```

**Comment by rliebz** [comment]
Hi @nicks6240 — 

Please fill out the complete template. You have not provided enough information for us to help you debug the issue. If I had to guess, it looks like you aren't actually running in module mode, which is required for v2.

**Comment by unbyte** [comment]
Update your Golang
