### ISSUE TITLE
v2 bug: ( StringSliceFlag, Value(default) does not set value in Destination )

### ISSUE THREAD

**Issue by sgoroshko** [urfave/cli#1121]
## my urfave/cli version is

_**github.com/urfave/cli/v2 v2.2.0**_

## Checklist

* [x] Are you running the latest v2 release? The list of releases is [here](https://github.com/urfave/cli/releases).
* [x] Did you check the manual for your release? The v2 manual is [here](https://github.com/urfave/cli/blob/master/docs/v2/manual.md)
* [x] Did you perform a search about this problem? Here's the [Github guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## Dependency Management

- [x] My project is using go modules.
- [ ] My project is using vendoring.
- [ ] My project is automatically downloading the latest version.
- [ ] I am unsure of what my dependency management setup is.

## Describe the bug

Default value does not setting in destination.

## To reproduce
```
package main

import (
	"github.com/urfave/cli/v2"
	"log"
	"os"
)

type config struct {
	Countries cli.StringSlice
}

func main() {
	cfg := new(config)

	app := cli.NewApp()
	app.Flags = []cli.Flag{
		&cli.StringSliceFlag{
			Name:        "country",
			Aliases:     []string{"c"},
			Value:       cli.NewStringSlice("CA", "US"),
			Destination: &cfg.Countries,
		},
	}
	app.Action = func(c *cli.Context) error {
		log.Printf("%+v", cfg)
		return nil
	}
	_ = app.Run(os.Args)
}
```

## Observed behavior
```
go run main.go 
2020/04/28 22:54:56 &{Countries:{slice:[] hasBeenSet:false}}
```
## Expected behavior
```
go run main.go 
2020/04/28 22:54:56 &{Countries:{slice:[CA US] hasBeenSet:false}}
```
## Additional context
```
go run main.go -c UA
2020/04/28 22:55:00 &{Countries:{slice:[UA] hasBeenSet:true}}
```
## Want to fix this yourself?

set default values manually
`cfg := &config{Countries: []string{"CA", "US"}}`

```
# paste `go version` output in here
```
`go version go1.14.2 darwin/amd64`

## Run `go env` and paste its output here

```
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/user/Library/Caches/go-build"
GOENV="/Users/user/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=" -mod="
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/user/go"
GOPRIVATE=""
GOPROXY="direct"
GOROOT="/usr/local/Cellar/go/1.14.2_1/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.14.2_1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/user/cli_test/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/n5/7nnknbgd727_w4s8yv3z9hyh0000gn/T/go-build026345303=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

**Comment by saschagrunert** [comment]
Yes, this seems like a bug I reproduced it on my side. @sgoroshko do you think that you're going to open a PR to address that issue?

**Comment by sgoroshko** [comment]
by analog with the implementation of other flags

flag.go:839 `func (f *FlagSet) Var(...` 
default value already must be set in `value flag.Value ` argument

and it's set, example for int, by flag.go:649 `func (f *FlagSet) IntVar`
in `newIntValue` function

so for me solution can be like that
flag_string_slice.go:138
```
for _, name := range f.Names() {
	if f.Value == nil {
		f.Value = &StringSlice{}
	}

	if f.Destination != nil {
		f.Destination.slice = f.Value.slice
		set.Var(f.Destination, name, f.Usage)
		continue
	}

	set.Var(f.Value, name, f.Usage)
}
```
**also, think it's problem actual for all slice like flags.**

**Comment by sgoroshko** [comment]
can u review my PR?

**Comment by lynncyrin** [comment]
Hey @sgoroshko in case you missed in, you'll need to resolve the duplication between your PR and https://github.com/urfave/cli/pull/1123
