### ISSUE TITLE
Parse arguments into struct

### ISSUE THREAD

**Issue by wesleimp** [urfave/cli#1136]
## Checklist

* [x] Are you running the latest v2 release? The list of releases is [here](https://github.com/urfave/cli/releases).
* [x] Did you check the manual for your release? The v2 manual is [here](https://github.com/urfave/cli/blob/master/docs/v2/manual.md)
* [x] Did you perform a search about this feature? Here's the [Github guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## What problem does this solve?

Parse arguments into struct instead of get one by one

## Solution description

Implement a `Parse` function to parse all arguments received into struct.

```go
type Config struct {
	Port         int  `env:"PORT" envDefault:"3000"`
	IsProduction bool `env:"PRODUCTION"`
}

func run(c *cli.Context) {
	cfg := Config{}

	err := c.Parse(&cfg)
        if err != nil{
		fmt.Printf("%+v\n", err)
	}

	fmt.Printf("%+v\n", cfg)
}
```

**Comment by dearchap** [comment]
I like this feature. Would make user code much easier to handle.

**Comment by meatballhat** [comment]
ftr some prior work exists that is compatible with urfave/cli v1: https://github.com/octago/sflags/blob/20f2a9c31dfce88b6e1ac276bfd395817089e0a0/examples/urfave_cli/main.go

**Comment by dearchap** [comment]
I think its best left to the user to handle the reflection and create the corresponding flags dynamically instead of cli library imposing the pattern
