### ISSUE TITLE
q: ( main.go:6:2: cannot find module providing package github.com/urfave/cli/v2: working directory is not part of a module )

### ISSUE THREAD

**Issue by shreyansh-zazz** [urfave/cli#1138]
## I have followed the document and I can see the package folder downloaded and I also renamed the `cli/v2@2.x.x` to `cli/v2` because without this it wasn't able to find the package. But after this also I am getting the following error:

_**main.go:6:2: cannot find module providing package github.com/urfave/cli/v2: working directory is not part of a module**_

**Comment by rliebz** [comment]
Please follow the template when opening an issue—there isn't enough context here for us to be able to help you.

**Comment by shreyansh-zazz** [comment]
I am sorry @rliebz 
Also closing this I fixed it.
