### ISSUE TITLE
v2 bug: Value does not work with TimestampFlag

### ISSUE THREAD

**Issue by vschettino** [urfave/cli#1144]
## my urfave/cli version is

_**2.2.0**_

## Checklist

* [x] Are you running the latest v2 release? The list of releases is [here](https://github.com/urfave/cli/releases).
* [x] Did you check the manual for your release? The v2 manual is [here](https://github.com/urfave/cli/blob/master/docs/v2/manual.md)
* [x] Did you perform a search about this problem? Here's the [Github guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## Dependency Management

- [x] My project is using go modules.
- [x] My project is using vendoring.
- [ ] My project is automatically downloading the latest version.
- [ ] I am unsure of what my dependency management setup is.

## Describe the bug

Passing a `Value` to `TimestampFlag` does nothing.

## To reproduce

```go
package main

import (
	"fmt"
	"github.com/urfave/cli/v2"
	"log"
	"os"
	"time"
)

func main() {
	var today = cli.NewTimestamp(time.Now())
	app := &cli.App{
		Commands: []*cli.Command{{
			Name: "sync",
			Flags: []cli.Flag{
				&cli.TimestampFlag{
					Name:   "from",
					Layout: "2006-01-02",
					Value:  today,
				},
			},
			Action: func(c *cli.Context) error {
				fmt.Println(c.Timestamp("from"))
				return nil
			},
		}},
	}
	err := app.Run(os.Args)
	if err != nil {
		log.Fatal(err)
	}
}

```
```bash
go install && go mymodule sync
```

Describe the steps or code required to reproduce the behavior

## Observed behavior

"from" flag is `<nil>` 

## Expected behavior

The `Value` (today) would be printed, as it works with other types of flag, such as `IntFlag`.

## Additional context

Docker build and run

## Want to fix this yourself?

I'd love to help. Can you guys confirm this and give me some directions about how to proceed?

## Run `go version` and paste its output here

```
go version go1.14.2 linux/amd64
```

## Run `go env` and paste its output here

```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="0"
GOMOD="/exfin/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build096471754=/tmp/go-build -gno-record-gcc-switches"

```

**Comment by aloababa** [comment]
I guess it's because of this: https://github.com/urfave/cli/blob/master/flag_timestamp.go#L121
Default value always gets ovveride.
So i think this can be fixed by adding an if like:
```
if f.Value == nil {
	f.Value = &Timestamp{}
}
```

**Comment by vschettino** [comment]
@aloababa yes, seems like this is the place. Thanks for pointing out! I will open a PR to fix this on the weekend.

**Comment by lynncyrin** [comment]
Sounds good, cc me when you're ready for a review ^^

**Comment by vschettino** [comment]
@lynncyrin do you guys need any help on other issues? I saw a few that might be stale but I don't wanna to intrude ^^

**Comment by lynncyrin** [comment]
Yes we could totally use help with stale or help wanted issues 👍
