### ISSUE TITLE
Is it possible to disable help altogether?

### ISSUE THREAD

**Issue by iancullinane** [urfave/cli#1145]
I am using the library to handle incoming message from a chat application. As such, I seem to be able to pipe errors back through to chat, but a lot of commands still print the default help to the terminal. I don't need this output can I turn it off completely?

**Comment by rliebz** [comment]
If you're specifically interested in disabling the help message, you should be able to accomplish that by overriding the `HelpPrinter` function to be a noop:

```go
cli.HelpPrinter = func(w io.Writer, templ string, data interface{}) {}
```

**Comment by lynncyrin** [comment]
via https://github.com/urfave/cli/issues/174#issuecomment-71782256, I think `HideHelp` might also work for this.

**Comment by dearchap** [comment]
HideHelp and HideHelpCommand options are available to remove help processing.
