### ISSUE TITLE
v1 bug: user sets flag and does not provide value, but there is no error

### ISSUE THREAD

**Issue by bitscuit** [urfave/cli#1147]
## my urfave/cli version is

v1.22.4

## Checklist

* [x] Are you running the latest v1 release? The list of releases is [here](https://github.com/urfave/cli/releases).
* [x] Did you check the manual for your release? The v1 manual is [here](https://github.com/urfave/cli/blob/master/docs/v1/manual.md)
* [x] Did you perform a search about this problem? Here's the [Github guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## Dependency Management

- [x] My project is using go modules.
- [ ] My project is using vendoring.
- [ ] My project is automatically downloading the latest version.
- [ ] I am unsure of what my dependency management setup is.

## Describe the bug

I have an example CLI, `hello`, which takes two flags, `--flag1` and `--flag2` with default values, `value1` and `value2`. All it does right now is just print out the values of the arguments:
```
# ./hello --flag1 v1 --flag2 v2
flag1 value:  v1
flag2 value:  v2
```
But let's say a user accidentally forgets to provide the value for `--flag1`. The resulting output is:
```
# ./hello --flag1 --flag2 v2
flag1 value:  --flag2
flag2 value:  value2
```

I would expect this to output an incorrect usage error instead of `flag1` using the `--flag2` name as a value. Not to mention that `flag2` has completely ignored the value supplied to it.

If a user were to set `flag2` and forget to provide a value, an error message is _correctly_ displayed:
```
# ./hello --flag1 v1 --flag2
Incorrect Usage. flag needs an argument: -flag2

NAME:
   hello - A new cli application

USAGE:
   hello [global options] command [command options] [arguments...]

COMMANDS:
   help, h  Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --flag1 value  usage1 (default: "value1")
   --flag2 value  usage2 (default: "value2")
   --help, -h     show help
2020/06/11 13:21:09 flag needs an argument: -flag2
```

## To reproduce

Minimal code to reproduce the above issue:
```go
package main

import (
	"fmt"
	"log"
	"os"

	"github.com/urfave/cli"
)

func main() {
	app := cli.NewApp()

	app.Flags = []cli.Flag{
		cli.StringFlag{Name: "flag1", Value: "value1", Usage: "usage1"},
		cli.StringFlag{Name: "flag2", Value: "value2", Usage: "usage2"},
	}

	app.Action = func(c *cli.Context) error {
		fmt.Println("flag1 value: ", c.String("flag1"))
		fmt.Println("flag2 value: ", c.String("flag2"))
		return nil
	}

	err := app.Run(os.Args)
	if err != nil {
		log.Fatal(err)
	}
}

```

## Observed behavior

```
# ./hello --flag1 --flag2 v2
flag1 value:  --flag2
flag2 value:  value2
```

## Expected behavior

```
# ./hello --flag1 --flag2 v2
Incorrect Usage. flag needs an argument: -flag1

NAME:
   hello - A new cli application

USAGE:
   hello [global options] command [command options] [arguments...]

COMMANDS:
   help, h  Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --flag1 value  usage1 (default: "value1")
   --flag2 value  usage2 (default: "value2")
   --help, -h     show help
2020/06/11 13:21:09 flag needs an argument: -flag1
```

## Additional context

None

## Want to fix this yourself?

We'd love to have more contributors on this project! If the fix for this bug is easily explained and very small, free free to create a pull request for it. You'll want to base the PR off the `v1` branch, all `v1` bug fix releases will be made from that branch.

## Run `go version` and paste its output here

```
go version go1.14.1 linux/amd64
```

## Run `go env` and paste its output here

```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/root/go/src/hello/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build579337196=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by rliebz** [comment]
Thanks for opening an issue! 

Here I actually think the CLI is behaving as intended.

> But let's say a user accidentally forgets to provide the value for --flag1

While from the user's perspective, what happened was that they forgot to provide a flag value, from the CLI's perspective they _did_ provide a value.

```bash
./hello --flag1 --flag2 v2
```

The proper way to interpret that set of args in the case that `--flag1` takes an argument is that `--flag2` was passed as the literal value to `--flag1`, and `v2` is passed as a positional argument. It is a 100% correct series of arguments of the form:

```
<cmd> --<flagname> <flagvalue> <arg>
```

This is also consistent with how other CLI tools behave. For example, what if I were to try to create a new branch in `git` with the command `git checkout -b`, run it in quiet mode, and forget to pass the flag value?

```bash
$ git checkout -b --quiet
fatal: '--quiet' is not a valid branch name.
```

I'm not sure there's a behavior that's more correct than the one we offer now that doesn't inhibit our ability to interpret args correctly in other situations. For example, what if we _wanted_ to use `--flag2` as the value of `--flag1`? 

I do agree that the behavior outlined in the ticket is confusing, but I also believe it's the best we can do here.

**Comment by bitscuit** [comment]
Thanks for the explanation, so in terms of flag parsing, this is the correct behaviour, and it's left to the application to perform any necessary validation checks. I also managed to replicate this behaviour using just the `flag` library from GO, so closing this issue since everything is working as intended.
