### ISSUE TITLE
NewContext not printing flag names

### ISSUE THREAD

**Issue by bitscuit** [urfave/cli#1149]
## my urfave/cli version is

v1.22.4

## Checklist

* [x] Are you running the latest v1 release? The list of releases is [here](https://github.com/urfave/cli/releases).
* [x] Did you check the manual for your release? The v1 manual is [here](https://github.com/urfave/cli/blob/master/docs/v1/manual.md)
* [x] Did you perform a search about this problem? Here's the [Github guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## Dependency Management

- My project is using go modules.

## Describe the bug

Created a new context and supplied it with a new flag set, but `FlagNames()` returns an empty slice even though `NumFlags()` returns 1.

## To reproduce

Minimal code to reproduce:
```go
package main

import (
	"flag"
	"fmt"
	"log"
	"os"

	"github.com/urfave/cli"
)

func main() {
	app := cli.NewApp()

	app.Flags = []cli.Flag{
		cli.StringFlag{Name: "flag1", Value: "value1", Usage: "usage1"},
		cli.StringFlag{Name: "flag2", Value: "value2", Usage: "usage2"},
	}

	app.Action = func(c *cli.Context) error {
		args := []string{"--test1", "case"}
		set := flag.NewFlagSet("testFlagSet", 0)
		set.String("test1", "case1", "usage")
		set.Parse(args)
		nc := cli.NewContext(c.App, set, nil)

		fmt.Println(nc.NumFlags())

		fmt.Println(nc.Args())
		fmt.Println(nc.FlagNames())
		return nil
	}

	app.OnUsageError = func(context *cli.Context, err error, isSubcommand bool) error {
		fmt.Println("test")
		return err
	}

	err := app.Run(os.Args)
	if err != nil {
		log.Fatal(err)
	}

}
```

## Observed behavior

Output from running:
```
# ./hello
1
[]
[]
```

## Expected behavior

Something like this:
```
# ./hello
1
[case]
[test1]
```

## Additional context
None

## Want to fix this yourself?

We'd love to have more contributors on this project! If the fix for this bug is easily explained and very small, free free to create a pull request for it. You'll want to base the PR off the `v1` branch, all `v1` bug fix releases will be made from that branch.

## Run `go version` and paste its output here

```
go version go1.14.1 linux/amd64
```

## Run `go env` and paste its output here

```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/root/go/src/hello/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build923385009=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by lynncyrin** [comment]
Makes sense 👍 I'd be happy to review a PR for this!

**Comment by dearchap** [comment]
@bitscuit Not sure what you are trying to achieve here but in general cli.Context is only for internal use of the cli library. Its creation involves some difficult orchestration behind the scenes. The behaviour observed is expected. NumFlags = 1 since once flag has been parsed from args. Args() will be empty since all the args have been parsed as flags and there are no args remaining. FlagNames will be set only if a cli.Command is associated with that context.
