### ISSUE TITLE
can this tools support interacting cli(like docker attach)?

### ISSUE THREAD

**Issue by lockelee1015** [urfave/cli#1150]
## my question is...

_**( Put the question text here )**_
I wanna use this cli tools to develop some funny things.
I read the readme.md and have some question.
How to build a interacting command like docker attach?

**Comment by rliebz** [comment]
What you're asking for can be utilized alongside this project, but is outside the scope of what capabilities we provide. `urfave/cli` is specifically targeting the creation of a command-line interface for passing and interpreting arguments to an application, but doesn't really play a role in what that application does after the arguments have been parsed.

I'm not sure I have enough context on what your use case is to point you to any better resources here. Some of the basic building blocks that might be of interest are `os.Stdout`, `os.Stderr`, and `os.Stdin`, which can be used anywhere an `io.Reader` or `io.Writer` are needed, or interacted with manually. You could combine those with arbitrary external commands using [the `exec` package](https://golang.org/pkg/os/exec/), also part of the standard library.

**Comment by dearchap** [comment]
Question has been answered by @rliebz . Closing this issue
