### ISSUE TITLE
How to write unit tests foe commands?

### ISSUE THREAD

**Issue by AchalaSB** [urfave/cli#1157]
## my question is how to write unit test script for this function?
I have developed a cli `mycli create` will create a new file. 

```
func cmd() {
  app := &cli.App{
    Commands: []*cli.Command{
      {
        Name:    "create",
        Usage:   "create file",
	Flags: []cli.Flag{
		&cli.StringFlag{Name: "message, m"},
	},
        Action:  func(c *cli.Context) error {
	 sample.SRCfile("hello/src")  // function to create new file
          return nil
        },
      },
      },
      },
    },
  }

func main() {
	cmd()
	err := app.Run(os.Args)
	if err != nil {
		log.Fatal(err)
	}
}
```

Thanks

**Comment by lynncyrin** [comment]
@AchalaSB there's a short description here: https://github.com/urfave/cli/issues/731

There's also a bunch of tests in this file that test a cli App: https://github.com/urfave/cli/blob/9047f3b42dc9b70d2750c43815fdd1346f2129f7/app_test.go
