### ISSUE TITLE
v1 bug: the module at gopkg.in/urfave/cli.v1 is broken

### ISSUE THREAD

**Issue by golddranks** [urfave/cli#1162]
## my urfave/cli version is

_**1.22.4**_

## Checklist

* [x] Are you running the latest v1 release? The list of releases is [here](https://github.com/urfave/cli/releases).
* [x] Did you check the manual for your release? The v1 manual is [here](https://github.com/urfave/cli/blob/master/docs/v1/manual.md)
* [x] Did you perform a search about this problem? Here's the [Github guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## Dependency Management

- [x] My project is using go modules.
- [ ] My project is using vendoring.
- [ ] My project is automatically downloading the latest version.
- [ ] I am unsure of what my dependency management setup is.

## Describe the bug

The bug is described in this StackOverflow issue: https://stackoverflow.com/questions/63013135/what-to-do-when-go-list-doesnt-show-the-newest-version-of-a-package

In short: when importing the package with path `gopkg.in/urfave/cli.v1` using go modules, the versions onwards 1.20 are broken, because the `go.mod` file states that the import path is `github.com/urfave/cli`.

## To reproduce

Add line `gopkg.in/urfave/cli.v1 v1.22.4` to your go.mod requirements and run go build.

## Observed behavior

```
go: gopkg.in/urfave/cli.v1@v1.22.4: go.mod has non-....v1 module path "github.com/urfave/cli" at revision v1.22.4
```

## Expected behavior

I'm not sure if this can be fixed, as with go modules the package can have only one module path. Maybe `gopkg.in/urfave/cli.v1` should be deprecated, and it should be stated clear in the documentation and on the gopkg.in page. I'm not entirely sure though, maybe there's some way to get it work.

## Additional context

This happened to me when upgrading old code to use go modules. It worked with dep.

## Want to fix this yourself?

Not sure if this can be fixed?

## Run `go version` and paste its output here

```
go version go1.14.4 darwin/amd64
```

## Run `go env` and paste its output here

```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/REDACTED/Library/Caches/go-build"
GOENV="/Users/REDACTED/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY="REDACTED"
GONOSUMDB="REDACTED"
GOOS="darwin"
GOPATH="/Users/REDACTED/go"
GOPRIVATE="REDACTED"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.14.4/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.14.4/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/REDACTED/repos/jln-lab/jlab-batch-go/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/5d/nl4d9w0j4s5bnrxd6jp969rmnppcjn/T/go-build935024432=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

**Comment by rliebz** [comment]
Right now, the only URLs we officially support are `github.com/urfave/cli/v2`, or `github.com/urfave/cli` for v1. I'm not sure what the story was historically for `gopkg.in`, but as far as modules go, you'll need to use the current import URL. 

This is consistent with what our docs describe, and I don't think there's anything that `gopkg.in` buys anyone in a module-aware world, so the path forward to get your project working again is just to update your references from `gopkg.in/urfave/cli.v1` to `github.com/urfave/cli`.

**Comment by golddranks** [comment]
Would it be possible to update the contents of the page at http://gopkg.in/urfave/cli.v1 ? Not sure who controls that or how.

**Comment by rliebz** [comment]
Seems to be auto-generated. This is a gopkg.in link that points to my fork of this repo, despite me not registering anything: https://gopkg.in/rliebz/cli.v1

Having gone through the gopkg.in docs, it looks like there's no user input there. It's just a service that maps gopkg.in URLs to GitHub projects.

**Comment by golddranks** [comment]
I see. In that case, there's hardly anything that could be done. I'll close this issue.
