### ISSUE TITLE
gh repo create kicks me out of my gh account

### ISSUE THREAD

**Issue by AlphaKennyBudy** [urfave/cli#1164]
Every time when I use `gh repo create` it creates a private repo, adds remote branches, but then it asks me for username and password. Since I use 2FA (and, you know, often passwords don't work there, so I have to generate access token again and again) it becomes very problematic for me to create repos. After that I can't use commands like `git push origin master` because I am not authorized and it asks me for username&password again. But without `gh ...` git works well, I can push/pull e t.c.

**Comment by rliebz** [comment]
I think this issue might have been opened in the wrong place.

**Comment by lynncyrin** [comment]
You’re looking for https://github.com/cli/cli ^^
