### ISSUE TITLE
Bash/ZSH Completion Not Working

### ISSUE THREAD

**Issue by ghost** [urfave/cli#1165]
# Background

I've followed the docs [here](https://github.com/urfave/cli/blob/master/docs/v1/manual.md#enabling) to enable bash completion on my machine with no success.

# Information

- My terminal is running ZSH, I've tried both files to enable completion.
- This is set inside `main.go`: `app.EnableBashCompletion = true`.
- Binary for MacOS is built and stored inside the `/usr/local/bin` directory. Running `mycli somecommand someargument` works fine.
- Typing `mycli` followed by the tab key produces results for the files inside my current directory, not subcommands.
- `go.mod` includes `github.com/urfave/cli v1.22.3`.

# Questions

- Should it the only step be to run `PROG=mycli source zsh_autocomplete` anywhere (assuming `zsh_autocomplete` is in the current directory)?
- Is there any other information I could provide to help further elaborate?

**Comment by joebateh** [comment]
I'm still interested in this issue's resolution.

**Comment by 6543** [comment]
@joebateh for bash completion i did:
`sudo wget -O /etc/bash_completion.d/tea https://raw.githubusercontent.com/urfave/cli/master/autocomplete/bash_autocomplete && sudo chmod +x /etc/bash_completion.d/tea`

**Comment by joebateh** [comment]
Hey @6543, I gave that a shot on both MacOS and Ubuntu with no success. I'm still getting directories instead of autocomplete suggestions.

**Comment by 6543** [comment]
:point_up: you have to replace `tea` with the name of your command - but I guess you did

what is returned when you do `./your-tool --generate-bash-completion`?

**Comment by joebateh** [comment]
I tried running the command below:

```bash
sudo wget -O /etc/bash_completion.d/mycli https://raw.githubusercontent.com/urfave/cli/master/autocomplete/bash_autocomplete && sudo chmod +x /etc/bash_completion.d/mycli
```

Then I typed `mycli` followed by pressing the tab character. It still shows up with the local directory as opposed to autocompletion.

If I type `mycli --generate-bash-completion` I see the set of subcommands for any given command, so it seems like whatever logic generates that _can_ do it. It's just not saving or pulling it in somewhere else.

Is there anything basic I might be missing?

**Comment by 6543** [comment]
do you have `[ -r /usr/share/bash-completion/bash_completion ] && . /usr/share/bash-completion/bash_completion` in youe `~/.bashrc` ?

**Comment by joebateh** [comment]
It wasn't there, but I added it with no success.

**Comment by 6543** [comment]
ok at this point I also have no idear ...
