### ISSUE TITLE
Convert FilePath field in flags from string to string array

### ISSUE THREAD

**Issue by kneal** [urfave/cli#1166]
## Checklist

* [x] Are you running the latest v2 release? The list of releases is [here](https://github.com/urfave/cli/releases).
* [x] Did you check the manual for your release? The v2 manual is [here](https://github.com/urfave/cli/blob/master/docs/v2/manual.md)
* [x] Did you perform a search about this feature? Here's the [Github guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## What problem does this solve?

_A clear and concise description of what problem this feature would solve. For example:_

- I am suggesting the `FilePath` option in all flags should be converted to a string array. 

## Solution description

_A detailed description of what you want to happen._

Today, the `FilePath` option for all flags is a string. You can use it as an array by doing [comma-separated paths within the field](https://github.com/urfave/cli/blob/d648edd48d89ef3a841b1ec75c2ebbd4de5f748f/flag.go#L375-L388). In v1 `EnvVar` and `FilePath` were consistent where you could specify an array of environment names separated by commas. I believe the value in converting `FilePath` to a string array is to maintain consistency for the users setting defaults on the flag options. 

## Describe alternatives you've considered

_A clear and concise description of any alternative solutions or features you've considered._

Another option I see is leaving it the way it is but one could argue the user experience isn't consistent between setting config for `EnvVar` and `FilePath`.

**Comment by dearchap** [comment]
@kneal  do you have any examples that utilize this behavior? Since this is a breaking change I would likely target for v3
