### ISSUE TITLE
v2 bug: The v2 manual supports flag alias such as `Name: "lang, l"`

### ISSUE THREAD

**Issue by olibre** [urfave/cli#1172]
## my urfave/cli version is

v2.2.0

## Checklist

* [x] Are you running the latest v2 release? The list of releases is [here](https://github.com/urfave/cli/releases).
* [x] Did you check the manual for your release? The v2 manual is [here](https://github.com/urfave/cli/blob/master/docs/v2/manual.md)
* [x] Did you perform a search about this problem? Here's the [Github guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## Dependency Management

- [ ] My project is using go modules.
- [ ] My project is using vendoring.
- [x] My project is automatically downloading the latest version.
- [ ] I am unsure of what my dependency management setup is.

## Describe the bug

The alias defined within the flag name string (after the coma) is not displayed in the help message.

```go
app := &cli.App{
	Flags: []cli.Flag{ &cli.StringFlag{Name: "lang, l", Usage: "Language for the greeting"},
}
```

produces the following help message without the alias `"-l value"`

    --lang value   Language for the greeting (default: "english")

## To reproduce

Use the snippet provided in the v2 manual:
https://github.com/urfave/cli/blob/master/docs/v2/manual.md#ordering

```go
package main

import (
  "log"
  "os"
  "sort"

  "github.com/urfave/cli/v2"
)

func main() {
  app := &cli.App{
    Flags: []cli.Flag{
      &cli.StringFlag{
        Name:  "lang, l",
        Value: "english",
        Usage: "Language for the greeting",
      },
      &cli.StringFlag{
        Name:  "config, c",
        Usage: "Load configuration from `FILE`",
      },
    },
    Commands: []*cli.Command{
      {
        Name:    "complete",
        Aliases: []string{"c"},
        Usage:   "complete a task on the list",
        Action:  func(c *cli.Context) error {
          return nil
        },
      },
      {
        Name:    "add",
        Aliases: []string{"a"},
        Usage:   "add a task to the list",
        Action:  func(c *cli.Context) error {
          return nil
        },
      },
    },
  }

  sort.Sort(cli.FlagsByName(app.Flags))
  sort.Sort(cli.CommandsByName(app.Commands))

  err := app.Run(os.Args)
  if err != nil {
    log.Fatal(err)
  }
}
```

## Observed behavior

The aliases "-c" and "-l" are missing in the help message:

    --config FILE  Load configuration from FILE
    --lang value   Language for the greeting (default: "english")

## Expected behavior

The v2 manual says the aliases "-c" and "-l" are present:

    --config FILE, -c FILE  Load configuration from FILE
    --lang value, -l value  Language for the greeting (default: "english")

## Run `go version` and paste its output here

```
go version go1.14.3 linux/amd64
```

## Run `go env` and paste its output here

```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/o/.cache/go-build"
GOENV="/home/o/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/o/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go-1.14"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.14/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/o/test/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build086020681=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by zemzale** [comment]
That is an issue with the documentation looks like.
There are notes in v1 to v2 migration guide about that https://github.com/urfave/cli/blob/master/docs/migrate-v1-to-v2.md#flag-aliases-are-done-differently
The example is just wrong, and that is the only place where it's like that.

**Comment by olibre** [comment]
Thank you for the info.

😢 I was prefering the concise format of the v1 😥 
* `Name: "foo, f"` :+1:
* `Name: "foo", Aliases: []string{"f"}` 🚂🚃🚃🚃🚃🚃🚃🚃
