### ISSUE TITLE
Prevent exit when help not found

### ISSUE THREAD

**Issue by garlicgit** [urfave/cli#1176]
I have the CLI inside a small shell loop. When urfave/cli finds a command to execute or help for a command, the shell loop continues as usual providing another prompt. When no help is found, the shell loop breaks to the normal unix prompt, with this message "2020/08/18 14:45:43 No help topic for 'gg'". What is it doing differently when it cannot find help and is there a way to stop that?

Thanks, enjoying the package.
Mark

**Comment by garlicgit** [comment]
Ok, so I was probably a little lazy before, I can see what it is doing:

"if ctx.App.CommandNotFound == nil {
		return Exit(fmt.Sprintf("No help topic for '%v'", command), 3)
 }"

So I guess the question is whether there is a way to override it, or if I just need to modify the source. I am guessing the latter.

**Comment by rliebz** [comment]
The way it's laid out is a bit confusing, but you shouldn't have to modify the source. `Exit` is a function that returns an exit error, where the default behavior for a `cli.App` is to call `os.Exit`, but can be overridden. 

Take a look at the `ExitErrHandler` field. As an example, this would disable the exiting behavior completely:

```go
app.ExitErrHandler = func(*cli.Context, error) {}
```

**Comment by garlicgit** [comment]
Thank you for the suggestion. For now, I commented out the fatal log error on the app.run(). I was not able to get the ExitErrHandler to create a different outcome.

//app.ExitErrHandler = func(*cli.Context, error) {
  //  fmt.Println("Got to errorHandler")
  //}
  
  err := app.Run(args)
  if err != nil {
    fmt.Println(err)
    //log.Fatal(err)
  }
  
This is good for now.

Thanks
Mark

**Comment by rliebz** [comment]
Not sure what the rest of your program looks like, but `log.Fatal` always exits an application. Glad you got something work.
