### ISSUE TITLE
v2 bug: ( flags have become positional, ignored when placed after arguments )

### ISSUE THREAD

**Issue by yogeshlonkar** [urfave/cli#1177]
## my urfave/cli version is v2.2.0

It seems flags now have become positional, they are ignored if they are placed after main argument.

## Checklist

* [x] Are you running the latest v2 release? The list of releases is [here](https://github.com/urfave/cli/releases).
* [x] Did you check the manual for your release? The v2 manual is [here](https://github.com/urfave/cli/blob/master/docs/v2/manual.md)
* [x] Did you perform a search about this problem? Here's the [Github guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## Dependency Management

- [x] My project is using go modules.
- [ ] My project is using vendoring.
- [ ] My project is automatically downloading the latest version.
- [ ] I am unsure of what my dependency management setup is.

## Describe the bug

Below command used to detect correct value for flag in v1 but with v2 update it returns empty value
```shell
example subcommand arg1 arg2 --flag1 this_value_is_ignored
```

## To reproduce

Pass string flag value after arguments to subcommand

## Observed behavior

Value for the flag is empty in execution

## Expected behavior

Actual value should have been set in flag

## Additional context
-

```
# paste `go version` output in here
```

## Run `go env` and paste its output here

```
# paste `go env` output in here
```

**Comment by rliebz** [comment]
Considering this is behaving as documented, I'm going to go ahead and close this.
