### ISSUE TITLE
v2 feature: Per-Command Metadata

### ISSUE THREAD

**Issue by imle** [urfave/cli#1182]
## Checklist

* [Yes] Are you running the latest v2 release? The list of releases is [here](https://github.com/urfave/cli/releases).
* [Yes] Did you check the manual for your release? The v2 manual is [here](https://github.com/urfave/cli/blob/master/docs/v2/manual.md)
* [Yes] Did you perform a search about this feature? Here's the [Github guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## What problem does this solve?

Writing a Command to be used across multiple Apps is a code reuse pattern that I am sure many benefit from. Currently it is possible to do so as long as you write the Command to be agnostic of the app calling it, which is generally a good practice anyway. However, in an ecosystem of micro-services all defining an App for themselves with a set of base functionality, it is difficult to take advantage of the App's metadata field since the Command is not sure which App or Apps it may be registered against. Providing a metadata field on commands would allow for a set of applications to take advantage of a single Command definition and the underlying App can see the Command's metadata to perform actions like keeping a task running in the background that is requested by the Command.

## Solution description

I propose that the Metadata field defined on the App struct be copied to Command struct to allow for situations like this.

## Describe alternatives you've considered

No other alternative has been evaluated due to the simplicity of this approach.

**Comment by imle** [comment]
A PR (#1174) was put in for this functionality and it was suggested that I elaborate further in a feature request.

**Comment by imle** [comment]
@xordspar0 I have put together a repo (https://github.com/imle/cli-example-for-pr) which show our use case for this PR. It is a bit convoluted, so feel free to ask any questions.

**Comment by lynncyrin** [comment]
I want to understand the motivation here, but I'm still not quite getting it. @imle could you add more details to this Github issue that further detail your use case / possibly provide concrete code examples within the issue itself? I see the example repo you have setup, but its difficult to parse the relevant context when looking at an entire repo.

**Comment by imle** [comment]
@lynncyrin the initial reason for this PR was misguided. I don't know why it wasn't obvious to me earlier but there are much better ways to do what I was trying to accomplish.
