### ISSUE TITLE
Command.Action error indication

### ISSUE THREAD

**Issue by Byron** [urfave/cli#119]
Even though `Command.Before` is supposed to check input arguments for their sanity and may return an error, during operation , i.e. `Command.Action()`, there may be other errors too that can't be estimated by `Command.Before` (e.g. IO failures)

Right now, it seems impossible to report these and force an error return, which would allow the process to exit with a non-zero value.

For me to be happy, the `Command.Action` member would need a signature change to `func(c *cli.Context) error`, with an accompanying minor change [here](https://github.com/codegangsta/cli/blob/master/app.go#L214).

Maybe there are other solutions which don't require a signature change or `panic()`.

**Comment by gdm85** [comment]
Can this please be re-opened? The problem is here: https://github.com/codegangsta/cli/blob/master/command.go#L127

```
	context.Command = c
	c.Action(context)
	return nil
}
```

Basically all actions can never fail?

**Comment by jszwedko** [comment]
@gdm85 the current API expects that you will handle any failures in `Action` rather than bubbling up. I agree that it would be nice for `c.Action` to bubble up the errors, but because it would change the API, I'm reticent to make that change.

Definitely on the list of things for a `2.0` though.

**Comment by gdm85** [comment]
@jszwedko ok, thanks for putting it on 2.0.

The discussion was about making it more test-friendly too.
