### ISSUE TITLE
v2 feature: Expose constructor of MapInputSource type

### ISSUE THREAD

**Issue by igorrius** [urfave/cli#1193]
## Checklist

* [x] Are you running the latest v2 release? The list of releases is [here](https://github.com/urfave/cli/releases).
* [x] Did you check the manual for your release? The v2 manual is [here](https://github.com/urfave/cli/blob/master/docs/v2/manual.md)
* [x] Did you perform a search about this feature? Here's the [Github guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## What problem does this solve?

There is a problem is on creating a custom input source that should implement all Input SourceContext methods instead of extending with current realization.

## Solution description

To fix this problem, suggesting to add a constructor to the current MapInputSource type. I will open PR in a few minutes.

## Describe alternatives you've considered

It possible to implement all methods of InputSourceContext interface but in general, it would be the same or very close to methods from MapInputSource type.

**Comment by rliebz** [comment]
Should be resolved already.
