### ISSUE TITLE
StringSliceFlag does not set destination when reading from yaml

### ISSUE THREAD

**Issue by lburgazzoli** [urfave/cli#1197]
## my urfave/cli version is

_**( v2.2.0 )**_

## Checklist

* [X] Are you running the latest v2 release? The list of releases is [here](https://github.com/urfave/cli/releases).
* [X] Did you check the manual for your release? The v2 manual is [here](https://github.com/urfave/cli/blob/master/docs/v2/manual.md)
* [X] Did you perform a search about this problem? Here's the [Github guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## Dependency Management

- [X] My project is using go modules.
- [ ] My project is using vendoring.
- [X] My project is automatically downloading the latest version.
- [ ] I am unsure of what my dependency management setup is.

## Describe the bug

The `Destination` field of a `StringSliceFlag` is not set when reading from a YAML file

## To reproduce

Create YAML file with the following content: 

```yaml
dependency:
  - mvn:g/a/v
```

Create a Go application with the following code: 

```go
package main

import (
	"fmt"
	"log"
	"os"

	"github.com/urfave/cli/v2"
	"github.com/urfave/cli/v2/altsrc"
)

func main() {
	dependencies := &cli.StringSlice{}

	flags := []cli.Flag{
		altsrc.NewStringFlag(&cli.StringFlag{
			Name:  "config",
			Value: ".app-config.yaml",
		}),
		altsrc.NewStringSliceFlag(&cli.StringSliceFlag{
			Name:        "dependency",
			Usage:       "dependency",
			Aliases:     []string{"d"},
			Destination: dependencies,
		}),
	}
	app := &cli.App{
		Name:   "kamel",
		Usage:  "kamel",
		Before: altsrc.InitInputSourceWithContext(flags, altsrc.NewYamlSourceFromFlagFunc("config")),
		Flags:  flags,
		Action: func(c *cli.Context) error {
			fmt.Println("context:", c.StringSlice("dependency"))
			fmt.Println("destination:", dependencies)
			return nil
		},
	}

	err := app.Run(os.Args)
	if err != nil {
		log.Fatal(err)
	}
}
```

## Observed behavior

This code will print:

```
context: [mvn:g/a/v]
destination: []
```

## Expected behavior

the value read from the file and associated to the `dependency` flag should be available both via the context and the destination.

## Run `go version` and paste its output here

```
go version go1.14.9 linux/amd64
```

## Run `go env` and paste its output here

```
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/lburgazz/.cache/go-build"
GOENV="/home/lburgazz/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/lburgazz/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/data/sfw/lang/go/1.14.9"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/data/sfw/lang/go/1.14.9/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/lburgazz/work/lb/dev/camel-k-cli/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build629793049=/tmp/go-build -gno-record-gcc-switches"

```

**Comment by mikunalpha** [comment]
Trick?
![Screenshot-20201206205830](https://user-images.githubusercontent.com/7397397/101280760-da191180-3805-11eb-8219-f9cdbc5ba104.png)

**Comment by dearchap** [comment]
Fixed. Please use latest release
