### ISSUE TITLE
v1.22.5 tagged with v2 mod version

### ISSUE THREAD

**Issue by costela** [urfave/cli#1201]
## my urfave/cli version is

v1.22.5

## Dependency Management

- [x] My project is using go modules.
- [ ] My project is using vendoring.
- [ ] My project is automatically downloading the latest version.
- [ ] I am unsure of what my dependency management setup is.

## Describe the bug

The [go.mod](/urfave/cli/blob/v1.22.5/go.mod) file for v1.22.5 has a v2 module (`github.com/urfave/cli/v2`; v1.22.4 had the correct `github.com/urfave/cli`).

## To reproduce

```
$ go mod download github.com/urfave/cli@v1.22.5
github.com/urfave/cli@v1.22.5: invalid version: go.mod has post-v1 module path "github.com/urfave/cli/v2" at revision v1.22.5
```
The same works fine for `v1.22.4`.

**Comment by costela** [comment]
@asahasrabuddhe maybe some `git checkout` typo while cutting the simultaneous v1 and v2 releases yesterday?

**Comment by joeycumines** [comment]
I am not certain but it seems this may have broken prior versions as well (my builds, without existing modcache, that included `v1.22.4` are now failing)

**Comment by asahasrabuddhe** [comment]
Hi @costela Looks like I typo. I have fixed it now and your builds should work.

**Comment by costela** [comment]
Yes, moving the tag seems to have fixed it. Lucky that proxy.golang.org doesn't seem to have cached (and checksumed) the broken state! :+1:
