### ISSUE TITLE
v2 bug: can not set default value

### ISSUE THREAD

**Issue by Delgus** [urfave/cli#1209]
## my urfave/cli version is

_**( 2.3.0 )**_

## Checklist

* [x] Are you running the latest v2 release? The list of releases is [here](https://github.com/urfave/cli/releases).
* [x] Did you check the manual for your release? The v2 manual is [here](https://github.com/urfave/cli/blob/master/docs/v2/manual.md)
* [ ] Did you perform a search about this problem? Here's the [Github guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## Dependency Management

- [x] My project is using go modules.
- [x] My project is using vendoring.
- [ ] My project is automatically downloading the latest version.
- [ ] I am unsure of what my dependency management setup is.

## Describe the bug

How set defalt value for flag?

## To reproduce
  
```package main

import (
	"fmt"
	"github.com/urfave/cli/v2"
	"os"
)

var sqlDir     string

func main() {
		app := cli.NewApp()
		app.Version = "1.0.0"
		app.Flags = []cli.Flag{
			&cli.StringFlag{
				Name:        "sql",
				Value:       "sql",
				Usage:       "sql directory",
				Destination: &sqlDir,
				EnvVars:     []string{"ANALYTIC_MIGRATE_SQL_DIR"},
			},
		}
		app.Name = "migrate tool"
		app.Usage = "migrate postgresql db for analytics"
		app.Action = func(c *cli.Context) error {
			fmt.Println(sqlDir)
			return nil
		}
		err := app.Run(os.Args)
		if err != nil {
			fmt.Println(err)
			os.Exit(0)
		}
}  
```

## Observed behavior
go run main.go

see empty response, sqlDir = ""

## Expected behavior

go run main.go
sql

expected sqlDir = sql

**Comment by zemzale** [comment]
I can't reproduce this. I would assume that you have set `ANALYTIC_MIGRATE_SQL_DIR` in environment to empty string.
Run `unset ANALYTIC_MIGRATE_SQL_DIR` to unset the variable if it exists and then run `go run main.go`, and you should see output `sql`

**Comment by Delgus** [comment]
Thx

**Comment by Delgus** [comment]
bug doesn't exist
