### ISSUE TITLE
Allow shorthands by calling commands via a unique name substring

### ISSUE THREAD

**Issue by noerw** [urfave/cli#1215]
## Checklist

* [x] Are you running the latest v2 release? The list of releases is [here](https://github.com/urfave/cli/releases).
* [x] Did you check the manual for your release? The v2 manual is [here](https://github.com/urfave/cli/blob/master/docs/v2/manual.md)
* [x] Did you perform a search about this feature? Here's the [Github guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## What problem does this solve?
Command aliases are somewhat limited for shortening command names.

## Solution description
Instead of explicit aliases, commands could be called via a part of their name only, as long as that is unique among all commands.
The `ip` utility or the network manager cli (`nmcli`) implement this behaviour and give a good showcase of the usability enhancements this brings:
![Peek 2020-12-16 12-30](https://user-images.githubusercontent.com/7880552/102343235-30b6e600-3f92-11eb-9e7b-cc483df5f7d9.gif)
To avoid ambiguity between subcommands & and command arguments, this behaviour should be disableable per command, eg via a setting `cmd.AcceptsArguments`

**Comment by 6543** [comment]
it could be a opt in feature "Longest Prefix Matching"

since Aliases are nice and can differ in any direction while "Longest Prefix Matching" does exactly as it says :)

**Comment by XANi** [comment]
I remember that feature from Perl's Getopt::Long, it was pretty convenient there

**Comment by 6543** [comment]
I think this should stay open ...

**Comment by dearchap** [comment]
@noerw What to take a look at the draft PR and see if it works for you ? I still need to add test cases but I've verified manually that it works.
