### ISSUE TITLE
Unable to go get v2 

### ISSUE THREAD

**Issue by pbalajiips** [urfave/cli#1220]
## my question is...
i am not able to get  "go get github.com/urfave/cli/v2". 
_**( Put the question text here )**_

**Comment by lynncyrin** [comment]
There isn't nearly enough context here to help you. Have you tried standard debugging practices, like searching related issues? => https://github.com/urfave/cli/search?q=go+get+v2&type=issues

**Comment by dearchap** [comment]
Not enough context. Works as it should if golang tools are setup correctly
