### ISSUE TITLE
The return value structure of the Args function in the CLI library is incorrect

### ISSUE THREAD

**Issue by ws150809201** [urfave/cli#1230]
## my urfave/cli version is

Git was last updated on Mon Jan 25  2021  the latest v1 release

## Checklist

* [y] Are you running the latest v1 release? The list of releases is [here](https://github.com/urfave/cli/releases).
* [y] Did you check the manual for your release? The v1 manual is [here](https://github.com/urfave/cli/blob/master/docs/v1/manual.md)
* [y] Did you perform a search about this problem? Here's the [Github guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## Dependency Management

- [y] My project is using go modules.
- [ ] My project is using vendoring.
- [ ] My project is automatically downloading the latest version.
- [ ] I am unsure of what my dependency management setup is.

## Describe the bug

cli/context.go
The function Args should return []string instead of an Args structure

func (c *Context) Args() Args {
	ret := args(c.flagSet.Args())
	return &ret
}

**Comment by meatballhat** [comment]
This is intentional behavior. The `Args` type may be coerced (back) to `[]string` when needed:

```go
package main

import (
        "fmt"
        "os"

        "github.com/urfave/cli"
)

func main() {
        app := cli.NewApp()

        app.Action = func(cCtx *cli.Context) error {
                fmt.Printf("%+#v\n", cCtx.Args())
                for i, arg := range cCtx.Args() {
                        fmt.Printf("%v: %+#v\n", i, arg)
                }

                asSlice := []string(cCtx.Args())
                fmt.Printf("[]string() -> %+#v\n", asSlice)

                return nil
        }

        app.Run(os.Args)
}
```

```sh-session
$ go run 1230.go hello dear humans
cli.Args{"hello", "dear", "humans"}
0: "hello"
1: "dear"
2: "humans"
[]string() -> []string{"hello", "dear", "humans"}
```
