### ISSUE TITLE
v2 feature: support no-name flags

### ISSUE THREAD

**Issue by vipally** [urfave/cli#1237]
## Checklist

* [x] Are you running the latest v2 release? The list of releases is [here](https://github.com/urfave/cli/releases).
* [x] Did you check the manual for your release? The v2 manual is [here](https://github.com/urfave/cli/blob/master/docs/v2/manual.md)
* [x] Did you perform a search about this feature? Here's the [Github guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## What problem does this solve?

To make a cli app like linux command cp:
```
$ cp --help
Usage: cp [OPTION]... [-T] SOURCE DEST
  or:  cp [OPTION]... SOURCE... DIRECTORY
  or:  cp [OPTION]... -t DIRECTORY SOURCE...
Copy SOURCE to DEST, or multiple SOURCE(s) to DIRECTORY.
```

The SOURCE and DEST flags are supplied as *no-name* ones.
 
## Solution description

- If Name not supplied by a flag, auto-generate a hidden Name
- Add a LogicName for every flag. Eg:  SOURCE is a logic name for command cp, which is without name.

## Describe alternatives you've considered

I have tried to implement this feature by modify std.flag at [cmdline](https://github.com/vipally/cmdline)
But it makes the flag APIs change.

Could you let me impliment this feature at the repo by not change the APIs?

**Comment by gregnr** [comment]
Worth noting that other CLI frameworks call this a `positional` argument.

Eg in `yargs`:
https://yargs.js.org/docs/#api-reference-positionalkey-opt

**Comment by lynncyrin** [comment]
This is the same feature as https://github.com/urfave/cli/issues/1074, more or less. @vipally @gregnr would either or you mind commenting on that issue with any ideas that you have? Please and thank you ✨ 

Closing this one as a duplicate, I would love to see more work happen on https://github.com/urfave/cli/issues/1074 though!!!
