### ISSUE TITLE
Is there a way to declare global options (global flags) to be printed with every command?

### ISSUE THREAD

**Issue by dsotirakis** [urfave/cli#1243]
## my question is...

_**Is there a way to declare global options (global flags) to be printed with every command?**_

Hi,

I am looking for a way to be able to have global options printed regardless of whether the command is a top-level or a sub command. 

One solution that I came up with was to make the flags a Global var and then pass it through my top-level flags and through sub-command flags, but that doesn't seem to be what I seek, since in the second case the flags are been shown like `OPTIONS` rather than `GLOBAL OPTIONS`.

Again, if a subcommand has another flag, then those "global flags" are overridden and are not being shown at all.

Followed the issue #795, but that didn't seem to find what I was looking for.

Anyone has any idea on if there's something I can use?

Thanks!

**Comment by dsotirakis** [comment]
Any news on that? ^^ 
Thanks!

**Comment by dearchap** [comment]
@dsotirakis do you want to only print global options in help for command or to be able to use specify them on cmdline after command ? For the former case you could override command help template to achieve it

**Comment by dearchap** [comment]
No way to do it right now. Nothing is planned for it yet
