### ISSUE TITLE
v2 feature: ( Positional `Args` Type Checking and Conversion )

### ISSUE THREAD

**Issue by sshaw** [urfave/cli#1246]
## Checklist

* [X] Are you running the latest v2 release? The list of releases is [here](https://github.com/urfave/cli/releases).
* [X] Did you check the manual for your release? The v2 manual is [here](https://github.com/urfave/cli/blob/master/docs/v2/manual.md)
* [X] Did you perform a search about this feature? Here's the [Github guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## What problem does this solve?

If find myself doing a lot of int conversion of the positional arguments. For example:

```go
id, err := strconv.ParseInt(c.Args().Get(0), 10, 64)
if err != nil {
        return fmt.Errorf("whatever id '%s' invalid: must be an int", c.Args().Get(0))
}
```

While there are a lot of conversions for flags, positional arguments (appear) to have none. 

## Solution description

Something that would attempt to do the conversion and error on failure, similar to what happens with flags. 

Or maybe let the user do this via:

```go
id, err := c.Args().GetInt64(0)
```

## Describe alternatives you've considered

Wrapper functions for the above.

**Comment by vipally** [comment]
The flag-based cli style is based on *Name* but not possition. I guess you want to use a cli arg as *someapp foo* instead of *someapp -f=foo* .
Maybe you are intrested in #1237

**Comment by lynncyrin** [comment]
This is the same feature as https://github.com/urfave/cli/issues/1074, more or less. @sshaw would you mind commenting on that issue with any ideas that you have? Please and thank you ✨ 

Closing this one as a duplicate, I would love to see more work happen on https://github.com/urfave/cli/issues/1074 though!!!
