### ISSUE TITLE
Can't run help without required global flags

### ISSUE THREAD

**Issue by 0xch4z** [urfave/cli#1247]
## my urfave/cli version is

v2.3.0

## Checklist

* [x] Are you running the latest v2 release? The list of releases is [here](https://github.com/urfave/cli/releases).
* [x] Did you check the manual for your release? The v2 manual is [here](https://github.com/urfave/cli/blob/master/docs/v2/manual.md)
* [x] Did you perform a search about this problem? Here's the [Github guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## Dependency Management

- [x] My project is using go modules.
- [ ] My project is using vendoring.
- [ ] My project is automatically downloading the latest version.
- [ ] I am unsure of what my dependency management setup is.

## To reproduce

`> go run main.go help list`

```go
package main

import "github.com/urfave/cli/v2"

const cmdHelpTemplate = "should reach this point without error"

func main() {
	cli := &cli.App{
		Name: "test",
		Flags: []cli.Flag{
			&cli.StringFlag{
				Name:     "token",
				EnvVars:  []string{"API_TOKEN"},
				Required: true,
			},
		},
		Commands: []*cli.Command{
			{
				Name:  "list",
				Usage: "list all clusters",

				Flags: []cli.Flag{
					&cli.StringFlag{
						Name:     "filter",
						Required: true,
					},
				},

				Action: func(_ *cli.Context) error { return nil },

				CustomHelpTemplate: cmdHelpTemplate,
			},
                        // ... other misc. commands that all require a token
		},
	}
	cli.RunAndExitOnError()
}
```

## Observed behavior

The default app help text is rendered to the terminal.

## Expected behavior

The help text for the `list` command to be rendered to the terminal. Maybe the user wanted to learn about the `filter` flag. The user shouldn't have to fulfill global flag requirements just to display help for a subcommand.

---

would love to fix this myself but want to ensure that this is not the intended behavior.

## Run `go version` and paste its output here

```
go version go1.15.8 darwin/amd64
```

## Run `go env` and paste its output here

```

```

**Comment by makeworld-the-better-one** [comment]
Also experiencing this, it's frustrating. Here is the code I used to get around it:

```go
	// Hack around issue where required flags are still required even for help
	// https://github.com/urfave/cli/issues/1247
	if len(os.Args) == 3 {
		if os.Args[1] == "h" || os.Args[1] == "help" {
			// Like: my-app help cmd
			for _, c := range app.Commands {
				if c.Name == os.Args[2] {
					cli.HelpPrinter(os.Stdout, cli.CommandHelpTemplate, c)
					return
				}
			}
			fmt.Println("no command with that name")
			os.Exit(1)
		} else if os.Args[len(os.Args)-1] == "-h" || os.Args[len(os.Args)-1] == "--help" {
			// Like: my-app cmd --help
			for _, c := range app.Commands {
				if c.Name == os.Args[1] {
					cli.HelpPrinter(os.Stdout, cli.CommandHelpTemplate, c)
					return
				}
			}
			fmt.Println("no command with that name")
			os.Exit(1)
		}
	}

	err := app.Run(os.Args)
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
```

It works well enough for me, but would get tricky with subcommands.

**Comment by lynncyrin** [comment]
> would love to fix this myself but want to ensure that this is not the intended behavior

It's not intended 👍🏼 asking for `--help` should definitely just output the help, and not output an error

The code change for this might be pretty straightforward, I think! Marking this as `help wanted` 🙏🏼

**Comment by jaimem88** [comment]
I believe the problem only happens when using the word `help` as a command. Using `--help`does not cause the error. Here is a simple attempt to fix this https://github.com/urfave/cli/pull/1285
