### ISSUE TITLE
Getting the error "no required module provides package " on windows

### ISSUE THREAD

**Issue by Blakeinstein** [urfave/cli#1252]
## my question is...

_**( Getting the error "no required module provides package " on windows )**_

My import system is as follows,
```go
package main

import (
	"log"
	"os"

	"github.com/urfave/cli/v2"
)
```

Running `go build main.go` returns the following error.

```bash
main.go:7:2: no required module provides package github.com/urfave/cli/v2: working directory is not part of a module
```

I am new to GO, and I have tried setting GO111MODULE=on as most sources have suggested, both by using `go env -w GO111MODULE=on` and `set GO111MODULE=on`. I have even used `$env:GO111MODULE="on"` with no luck.

**Comment by rliebz** [comment]
The relevant part of the error message is this:

> working directory is not part of a module

This means that while module mode is enabled, the project that you're working on is not part of a module. If you have a project hosted at say `github.com/Blakeinstein/my-project`, you can convert your project to a module by running the following from the project's root directory:

```bash
go mod init github.com/Blakeinstein/my-project
```

This will create a `go.mod` file in your working directory, which is the indicator to the go tool chain that your project is a module, in addition to all of the information that is included in `go.mod`.

A couple links that might be helpful:
- Usage guide: https://blog.golang.org/using-go-modules
- Full module reference: https://golang.org/ref/mod

**Comment by dearchap** [comment]
Comment by @rliebz is the proper way to go
