### ISSUE TITLE
Required field in Flag not work as expected with Name with only one character

### ISSUE THREAD

**Issue by Gerrard-YNWA** [urfave/cli#1253]
## my urfave/cli version is
master branch

## Checklist

* [x] Are you running the latest v2 release? The list of releases is [here](https://github.com/urfave/cli/releases).
* [x] Did you check the manual for your release? The v2 manual is [here](https://github.com/urfave/cli/blob/master/docs/v2/manual.md)
* [ ] Did you perform a search about this problem? Here's the [Github guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## Dependency Management

- [x] My project is using go modules.
- [ ] My project is using vendoring.
- [ ] My project is automatically downloading the latest version.
- [ ] I am unsure of what my dependency management setup is.

## Describe the bug
Setting `Required` field to `true` in Flags* will not worked while the Name field in flag only contains only one character.

## To reproduce
```
package main

import (
	"fmt"
	"os"

	"github.com/urfave/cli/v2"
)

func main() {
	app := cli.NewApp()
	app.Flags = []cli.Flag{
		&cli.StringFlag{Name: "c", Value: "config.yaml", Usage: "specify config file", Required: true},
	}
	app.Action = func(c *cli.Context) error {
		fmt.Println(c.String("c"))
		return nil
	}

	if err := app.Run(os.Args); err != nil {
		fmt.Println(err)
	}
}
```

## Observed behavior
When specified the `Name` field to "c", and run program will exit normally with a `config.yaml` output. When I Changed `Name` field to "conf" program exit with help message and a `Required flag "conf" not set` output which is as expected.

It seems the `checkRequiredFlags` function in https://github.com/urfave/cli/blob/master/context.go#L256 filtered the key with length 1.  
## Expected behavior

I Want to know whether this behavior designed deliberately or not?  If is, what's the purpose and can we clarify in the doc? If not, shall I correct this?

What I expect is Name field with only one character in flag should also work with `checkRequiredFlags`

## Want to fix this yourself?
yes

**Comment by dearchap** [comment]
@Gerrard-YNWA Do you plan to submit a PR for this ?

**Comment by Gerrard-YNWA** [comment]
Hi @dearchap Sorry for the late reply.  I've just send a PR and  please take a glance when you  have time :)
