### ISSUE TITLE
Flags & Args ordering

### ISSUE THREAD

**Issue by ebarped** [urfave/cli#1265]
## Ordering of Flags & Args not interchangeable?

Hello,

I developed a simple app, that needs to receive an url mandatory, so i use an Argument, and allows to modify the behavior using Flags. Also, because is very simple and does only one thing, does not have subcommands.

If i execute the app in this way, everything works:
`./app -r flag1 -c flag2 --log-level debug localhost:5000`

But, i would like to execute in this other way, because seems more understandable:
`./app localhost:5000 -r flag1 -c flag2 --log-level debug`

In the second form, the cli doesnt work, and tells:
`Required flags "flagX, flagY" not set`

Is this the expected behaviour?

I searched through issues and it seems to be work in progress to rearrange the reordering of flags, and to implement Args interface, but im not sure if this is related.

Thanks in advance!

**Comment by dearchap** [comment]
@ebarped Yes this is an ongoing discussion. Thanks for raising this issue.
