### ISSUE TITLE
How to pass string slice flags

### ISSUE THREAD

**Issue by altafan** [urfave/cli#1267]
Hello, this is a dumb question but I found no mention in the doc on how a string slice should be defined when using the CLI.

I tried with `mycli example --names name1,name2` but when I parse the flag values with `ctx.StringSlice("names")` I get a slice of one long string `"name1,name2"` instead of a slice with 2 elems.

**Comment by maeglindeveloper** [comment]
hey @altafan , any chance to have a example for this ? :)

**Comment by dearchap** [comment]
@maeglindeveloper it will be 

`--names name1 --names name2`

@meatballhat Probably a good idea to add this to the docs.
