### ISSUE TITLE
can I remove default text when a flag's value is set

### ISSUE THREAD

**Issue by seyoatda** [urfave/cli#1277]

**Comment by seyoatda** [comment]
It seems that when I set a flag's value, the help info will show a default text , even if I  do not try to set a default text hint.  
for example, if I create a IntFlag, then its value is 0 as default, which is initialize by golang itself. then the default text is shown as `(default: 0)`. But I didn't set the value as 0, and the `default text` was not supposed to show

**Comment by valorl** [comment]
@Toady00 One thing I found you can do is set `DefaultText: ""` on the flag.

**Comment by lorensr** [comment]
@valorl's suggestion isn't working for me with a `BoolFlag`:

```
--help, -h                       Show help (default: false)
```

<img width="397" alt="image" src="https://user-images.githubusercontent.com/251288/191891024-38e3575a-80d6-4db8-b1d8-fc3d1dbf8153.png">

**Comment by dearchap** [comment]
@lorensr Can you check if this problem exists with latest release as well ? We've made some changes to default handling

**Comment by lorensr** [comment]
@dearchap I'm getting the same behavior on latest `v2.23.7`

**Comment by dearchap** [comment]
@lorensr can you post a code snippet ?

**Comment by lorensr** [comment]
```
cli.HelpFlag = &cli.BoolFlag{
	Name:    "help",
	Aliases: []string{"h"},
	Usage:   "Show help",
	DefaultText: "",
}
```

Setting `DefaultText: ""` does not remove the `(default: false)` output below:

```
--help, -h                       Show help (default: false)
```

Diff: https://github.com/temporalio/cli/compare/main...repro-1277
Repro: https://github.com/temporalio/cli/tree/repro-1277

**Comment by dearchap** [comment]
Can you set DefaultText to " " or a non empty string?

**Comment by lorensr** [comment]
Here is `" "`:

```
   --help, -h     Show help (default:  )
```

**Comment by dearchap** [comment]
Okay I see the issue now. So would you like to hide the default text only for bool flags or for all flags ?

**Comment by lorensr** [comment]
Only for these two flags:

```
GLOBAL OPTIONS:
   --help, -h     show help (default: false)
   --version, -v  print the version (default: false)
```

and not for other bool flags or flags of other types.

**Comment by dearchap** [comment]
@lorensr Can you try the PR and see if it works for you ? Thanks

**Comment by lorensr** [comment]
@dearchap I'm on `v2.25.7`, and now by default I don't see `(default: false)`. However, if I change `show help` to `Show help` with this, `(default: false)` comes back:

```
cli.HelpFlag = &cli.BoolFlag{
	Name:    "help",
	Aliases: []string{"h"},
	Usage:   "Show help",
	DefaultText: "",
}
```
