### ISSUE TITLE
v2 bug: multi-line UsageText doesn't consistently indent in help output

### ISSUE THREAD

**Issue by codefromthecrypt** [urfave/cli#1278]
## my urfave/cli version is

latest master

## Checklist

* [x] Are you running the latest v2 release? 581b769cf3ee996b7277e895b30afa3f3e6921bf
* [x] Did you check the manual for your release?
* [x] Did you perform a search about this problem? Looked at the issues list

## Dependency Management

- [x] My project is using go modules.

## Describe the bug

If your `UsageText` is multi-line, help output `USAGE` only indents the first line 4 spaces, not the others.

## To reproduce

Add `UsageText` that includes at least one newline. Ex:

```go
		Usage:     "Download and install a <version> of Envoy",
		ArgsUsage: "<version>",
		UsageText: fmt.Sprintf(`The '<version>' is from the "versions" command.
The Envoy <version> will be installed into $GETENVOY_HOME/versions/<version>

Example:
$ getenvoy install %s`, version.LastKnownEnvoy),
```

## Observed behavior

The first line indents, but the others don't.

```
USAGE:
   The '<version>' is from the "versions" command and installed if necessary.
The '<args>' are interpreted by Envoy.
The Envoy working directory is archived as $GETENVOY_HOME/runs/$epochtime.tar.gz upon termination.

Example:
$ getenvoy run 1.18.3 --config-path ./bootstrap.yaml
```

## Expected behavior

I would expect consistent indent because trying to manipulate `UsageText` to indent manually is awkward and fragile (ex guess 4 spaces)

## Additional context

Before https://github.com/urfave/cli/pull/1171 this wouldn't render at all. Now it renders, but not quite right.

## Want to fix this yourself?

could if reviewing my work is easier than fixing directly

## Run `go version` and paste its output here

```
go version go1.16.3 darwin/amd64
```

## Run `go env` and paste its output here

```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/adrian/Library/Caches/go-build"
GOENV="/Users/adrian/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/adrian/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/adrian/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.16.3/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.16.3/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16.3"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/adrian/tetratelabs/getenvoy/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/vd/1cf8zdb1721f4z5rjggy8bp40000gn/T/go-build2368530510=/tmp/go-build -gno-record-gcc-switches -fno-common"

```

**Comment by clok** [comment]
I did some testing and digging on this issue. First, I believe that this is not a regression due to #1171. It appears to be in the code since at least `v2.0.0` (I have not checked `v1` at this point). Second, it should be a pretty straight forward feature to add.

The root cause is that the template used to generate the command help output will use the `UsageText` directly, with no formatting. See: https://github.com/urfave/cli/blob/master/template.go#L41-L43

This should do the trick. I will open a PR to address this.
```go
USAGE:
   {{if .UsageText}}{{.UsageText | nindent 3 | trim}}{{else}}{{.HelpName}}{{if .VisibleFlags}} [command options]{{end}} {{if .ArgsUsage}}{{.ArgsUsage}}{{else}}[arguments...]{{end}}{{end}}{{if .Category}}
```

**Comment by clok** [comment]
@codefromthecrypt and @rliebz Got a PR up to address this. #1279
