### ISSUE TITLE
v2 bug: cannot find package "github.com/urfave/cli/v2" in any of: /Users/myusername/.goenv/versions/1.14.2/src/github.com/urfave/cli/v2 (from $GOROOT)  /Users/myusername/go/1.14.2/src/github.com/urfave/cli/v2 (from $GOPATH)

### ISSUE THREAD

**Issue by 92612ShiyuQiu** [urfave/cli#1283]
## my urfave/cli version is

_**( Put the version of urfave/cli that you are using here )**_

## Checklist

* [x] Are you running the latest v2 release? The list of releases is [here](https://github.com/urfave/cli/releases).
* [x] Did you check the manual for your release? The v2 manual is [here](https://github.com/urfave/cli/blob/master/docs/v2/manual.md)
* [x] Did you perform a search about this problem? Here's the [Github guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## Dependency Management

- [x] My project is using go modules.
- [ ] My project is using vendoring.
- [ ] My project is automatically downloading the latest version.
- [x] I am unsure of what my dependency management setup is.

## Describe the bug

When I run "go get github.com/urfave/cli/v2", I get:
package github.com/urfave/cli/v2: cannot find package "github.com/urfave/cli/v2" in any of:
        /Users/sqiu/.goenv/versions/1.14.2/src/github.com/urfave/cli/v2 (from $GOROOT)
        /Users/sqiu/go/1.14.2/src/github.com/urfave/cli/v2 (from $GOPATH)

Then I changed it to run "GO111MODULE=on go get github.com/urfave/cli/v2", and I got:
go: github.com/urfave/cli/v2 upgrade => v2.3.0

I import v2 as "github.com/urfave/cli/v2", but when I run the program it gives me error:
cannot find package "github.com/urfave/cli/v2" in any of:
        /Users/myusername/.goenv/versions/1.14.2/src/github.com/urfave/cli/v2 (from $GOROOT)
        /Users/myusername/go/1.14.2/src/github.com/urfave/cli/v2 (from $GOPATH)

## To reproduce

Describe the steps or code required to reproduce the behavior

## Observed behavior

What did you see happen immediately after the reproduction steps above?

## Expected behavior

What would you have expected to happen immediately after the reproduction steps above?

## Additional context

If the issue relates to a specific open source Github repo, please link that repo here.

If you can reproduce this issue with a public CI system, please link a failing build here.

## Want to fix this yourself?

We'd love to have more contributors on this project! If the fix for this bug is easily explained and very small, free free to create a pull request for it.
## Run `go version` and paste its output here

```
# paste `go version` output in here
```
go version go1.14.2 darwin/amd64

## Run `go env` and paste its output here
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/sqiu/Library/Caches/go-build"
GOENV="/Users/sqiu/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/sqiu/go/1.14.2"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/sqiu/.goenv/versions/1.14.2"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/sqiu/.goenv/versions/1.14.2/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/j7/xjg8nkls16s11kf9r4zcntp40000gq/T/go-build097675889=/tmp/go-build -gno-record-gcc-switches -fno-common"
```
# paste `go env` output in here
```

**Comment by rliebz** [comment]
It sounds like modules might not be correctly enabled in your project—the thing to check for is a `go.mod` file.

If it's missing, assuming you're working on a project at `github.com/92612ShiyuQiu/my-project`, at the root of your repo, run:

```sh
go mod init github.com/92612ShiyuQiu/my-project
```

This will create a `go.mod` file for you. From there, `go get github.com/urfave/cli/v2` should work without setting `GO111MODULE=on` explicitly, and running your project should do the same.
