### ISSUE TITLE
Is there a way to have flags that don't require arguments/values? e.g. --flag

### ISSUE THREAD

**Issue by HmzAli** [urfave/cli#1284]
## my question is...

_**( I have to say this... Thank you for crafting such awesome CLI tool!  it's a major component of a very exciting project I'm working on. Anyway, I was wonder if it's possible to have a flag that don't require values/arguments. currently if a flag is specified without an argument, `flag needs an argument:` error is thrown. Some other cli tools support this feature,  e.g. npm `npm init --y`, so the presence of the flag is enough to act upon it**_

**Comment by lynncyrin** [comment]
A `BoolFlag` is what you're looking for 🙂

**Comment by HmzAli** [comment]
Thanks @lynncyrin !
