### ISSUE TITLE
q: what should I do if just input help/version and show help/version info and exit 0

### ISSUE THREAD

**Issue by Turing-Chu** [urfave/cli#1294]
## my question is...

I have a flag named config to specify config file path. However, when user input -h,-v,--version,--help and without --config, I want to just show help / version information and exit 0.

so what should I do for my question.

**Comment by WestleyK** [comment]
Hi @Turing-Chu, here is some functions that may help:
 - [`ShowAppHelp()`](https://pkg.go.dev/github.com/urfave/cli#ShowAppHelp)
 - [`ShowAppHelpAndExit()`](https://pkg.go.dev/github.com/urfave/cli#ShowAppHelpAndExit) Or:
 - [`ShowCommandHelp`](https://pkg.go.dev/github.com/urfave/cli#ShowCommandHelp)
 - [`ShowCommandHelpAndExit`](https://pkg.go.dev/github.com/urfave/cli#ShowCommandHelpAndExit)

I believe [`ShowAppHelpAndExit()`](https://pkg.go.dev/github.com/urfave/cli#ShowAppHelpAndExit) is what you are looking for.

**Comment by Turing-Chu** [comment]
thanks for your help. Now I have another question: I define app in another package `init` function, and called before `main` function. but I can not get Arg. the code as follows:

project struct:
```text
awesomeProject
├── config
│   └── init.go
├── go.mod
├── go.sum
└── main.go
```

main.go:
```text
package main

import (
	_ "awesomeProject/config"
)

func main() {}
```

config/init.go:
```
package config

import (
	"fmt"
	"os"

	"github.com/urfave/cli/v2"
)

func init() {
	app := &cli.App{
		Name:  "grid",
		Usage: "a sample command line application",
		Flags: []cli.Flag{
			&cli.StringFlag{
				Name:    "config",
				Aliases: []string{"c"},
				Usage:   "specify config file to be used",
			},
			&cli.BoolFlag{
				Name:    "version",
				Aliases: []string{"v"},
				Usage:   "show version for this application and exit",
			},
		},
		Action: func(ctx *cli.Context) error {
			if ctx.NArg() == 0 {
				cli.ShowAppHelpAndExit(ctx, 0)
				return nil
			}
			fmt.Println(ctx.Args().Get(0), ctx.NArg())
			return nil
		},
	}

	if err := app.Run(os.Args); err != nil {
		fmt.Println(err)
		return
	}
}
```

when I run with `go run main.go -c config/init.go`, it exit at `if ctx.NArg() == 0 {`

**Comment by WestleyK** [comment]
So, you code should work just fine. When you run `go run main.go -c config/init.go`, you are passing flag `-c string`, which is a flag. `ctx.NArg()` only returns the args count, eg. `go run main.go -c foo arg1` -> `NArg() = 1`.

If you want to get the value of `--config`, you will need to do this:

```
fmt.Printf("config=%s\n", ctx.String("config"))
```

And remove the `if ctx.NArg()` unless you are expecting arguments in addition to flags.

**Comment by Turing-Chu** [comment]
and another question: how can I run `go test` success?

before [urfave/cli](https://github.com/urfave/cli), I used [alecthomas/kingpin](https://github.com/alecthomas/kingpin). 
But alecthomas/kingpin panic with `error: unknown short flag '-t', try --help` when run `go test`. 
Now I intend to change kingpin to urfave/cli to resolve this, ie. kingpin or urfave/cli can parse command line arguments and run go test success.
But now urfave/cli run `go test` with error `Incorrect Usage. flag provided but not defined: -test.paniconexit0`
So what should I do with urfave/cli or how can I run go test without flag error?

**Comment by WestleyK** [comment]
I'm not sure what testing framework (end-2-end vs unit tests) you use, or your test code. Check your test code for for undefined flags. Testing frameworks are usually very verbose on which test failed.

**Comment by rliebz** [comment]
@Turing-Chu it sounds like you may be running something like `app.Run(os.Args)` in your tests. That will pass the arguments used internally by `go test` to your application, where presumably you're interested in passing a set of arguments particular to the test case, rather than the test runner.

Make sure that the flags your test uses are the flags you want to test. That should start with the name of your executable, followed by any flags you want to pass for the test case, e.g., `[]string{"my-app", "--name", "foo"}`. There should probably not be a reference to `os.Args` in your test case or the code it calls, as a quick spot check.

**Comment by Turing-Chu** [comment]
yes, I used same to `app.Run(os.Args)`, and I have some test cases which have nothing to `app.Run(os.Args)`. By the way , `app.Run(os.Args)` was written at an init function. so, when run `go test`, some package contain test case  and import package with init function which contain app.Run(os.Args). then it exit with panic. Let me have a look at  what I can do about it.

**Comment by Turing-Chu** [comment]
Now for test my code that has nothing to parse arguments, I add the following code in init function first line😄 :

```
func init() {
	if strings.HasSuffix(os.Args[0], ".test") {
		return
	}
       // MY OTHER CODE
}
```
