### ISSUE TITLE
Return explicit usage error

### ISSUE THREAD

**Issue by flowchartsman** [urfave/cli#1305]
## Checklist

* [X] Are you running the latest v2 release? The list of releases is [here](https://github.com/urfave/cli/releases).
* [X] Did you check the manual for your release? The v2 manual is [here](https://github.com/urfave/cli/blob/master/docs/v2/manual.md)
* [X] Did you perform a search about this feature? Here's the [Github guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## What problem does this solve?

I have a CLI app that has differing arg requirements based on a particular flag. Either it will be `cmd sub --all <first>` or `cmd sub <first> <second> [etc]...` I can check for the arg length and return an error fine, but it would be nice to be able to do something like

```go
	if c.Args().Len() == 0 {
		return cli.UsageErr(fmt.Errorf("requires at least one argument"))
	}
	all := c.Bool("all")

	if !all {
		if c.Args().Len() < 2 {
			return cli.UsageErr(fmt.Errorf("missing name(s)"))
		}
                //...
	} else {
            //...
	}
```

This way, certain errors will automatically print the command usage, while later errors can fail as normal.

**Comment by flowchartsman** [comment]
Notes after digging somewhat: the most straightforward implementation would be changing `handleExitCoder` to `handleErrorTypes`, which could use `errors.As()` and either retrofitting `exitError` to implement `Unwrap() error`, or ideally changing `message` from `interface{}` to `error` (unsure how feasible this is yet). Then it would be a matter of adding a new `UsageError` type, also implementing `Unwrap() error`, along with `NewUsageError(error)error`.

This way the two could be used in conjunction for errors which should either exit with a code, print usage or both.

**Comment by flowchartsman** [comment]
Something like this: https://play.golang.org/p/jGF1iYuBl9z

**Comment by flowchartsman** [comment]
Functional error options are also a possibility: https://play.golang.org/p/HMkLILVU3FP

**Comment by dearchap** [comment]
@flowchartsman This a a good idea. Would you like to submit a PR for this ?

**Comment by flowchartsman** [comment]
Sure, but I wouldn't mind a little buy-in before I do an implementation. I think probably the most "correct" way to do it would be to use errors.As and then define different error wrappers for error behaviors like I mention [above](https://github.com/urfave/cli/issues/1305#issuecomment-930547926). Can I get a show of thumbs-up thumbs-down on that proposal?

**Comment by dearchap** [comment]
@flowchartsman PR #1545 might help. Can you let me know if it is what you are looking for ? We cant change the interface{} to error but breaking some clients so we'd rather not

**Comment by dearchap** [comment]
Wont fix in v2. Will be superseded by #1662 in v3
