### ISSUE TITLE
Allow default command if one is not passed 

### ISSUE THREAD

**Issue by jalavosus** [urfave/cli#1307]
## Checklist

* [x] Are you running the latest v2 release? The list of releases is [here](https://github.com/urfave/cli/releases).
* [x] Did you check the manual for your release? The v2 manual is [here](https://github.com/urfave/cli/blob/master/docs/v2/manual.md)
* [x] Did you perform a search about this feature? Here's the [Github guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## What problem does this solve?

Say I have an `App` with one or two primary commands. Say I want it to default to one of those commands if a command arg isn't specifically passed, so that the app has easy and useful default behavior. 

Right now, there's no good way to do this; rather, there's no way to do it at all, if the "default" to be set takes any flags. 

Current app behavior: 

**Calling command "properly"**

`./app-binary do-thing --flag1 x -n 2`

No errors.

**Hacking together some stuff to try and have default command-like behavior**

(should default to whatever `do-thing`  is supposed to do, **including flag parsing**)

`./app-binary --flag1 x -n 2`

The above causes a UsageError, since flag parsing seems to happen at the `App` level. 

## Solution description

Implement a field on `App` similar to `Before`, `After`, and `Action`, which allows one to specify a command to be run if none are otherwise specified AND `-h/--help` isn't passed. If this field is present, flag parsing should happen at the `Command` level rather than the `App` level. 

## Describe alternatives you've considered

¯\\\_(ツ)\_/¯

**Comment by meatballhat** [comment]
@jalavosus Thank you for your thoughtful issue! I'm having trouble understanding how this would differ from the current behavior of running `Action` 🤔 e.g.:

```go
package main

import (
    "fmt"
    "log"
    "os"

    "github.com/urfave/cli/v2"
)

func main() {
    app := &cli.App{
        Name: "pants",
        Action: func(cCtx *cli.Context) error {
            fmt.Println("correctly so")
            return nil
        },
        Commands: []*cli.Command{
            {
                Name: "retract",
                Action: func(cCtx *cli.Context) error {
                    fmt.Println("your discomfort is visible")
                    return nil
                },
                Subcommands: []*cli.Command{
                    {
                        Name: "mostly",
                        Action: func(cCtx *cli.Context) error {
                            fmt.Println("you have achieved shorts")
                            return nil
                        },
                    },
                },
            },
        },
    }

    if err := app.Run(os.Args); err != nil {
        log.Fatal(err)
    }
}
```

```sh-session
$ go run pants.go
correctly so

$ go run pants.go retract
your discomfort is visible

$ go run pants.go retract mostly
you have achieved shorts
```

**Comment by meatballhat** [comment]
🤦🏼 it's the flag parsing bit that's the problem, right? Because of the long-standing weirdness with command-level flags vs global flags?
