### ISSUE TITLE
v2 bug: Default:false value for BoolFlag is true

### ISSUE THREAD

**Issue by AleksandraSp** [urfave/cli#1309]
## my urfave/cli version is

_**v2**_

## Checklist

* [x ] Are you running the latest v2 release? The list of releases is [here](https://github.com/urfave/cli/releases).
* [x ] Did you check the manual for your release? The v2 manual is [here](https://github.com/urfave/cli/blob/master/docs/v2/manual.md)
* [x ] Did you perform a search about this problem? Here's the [Github guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## Dependency Management

- [x ] My project is using go modules.
- [ ] My project is using vendoring.
- [ ] My project is automatically downloading the latest version.
- [x ] I am unsure of what my dependency management setup is.

## Describe the bug

BoolFlag default value:false is not set to false. Calling command with BoolFlag and no value set, returns true.

## To reproduce

Add BoolFlag, set Value to false. 
```
&cli.BoolFlag{
Name:     faultyflag,
Usage:    "somehting",
Required: true,
Value:    false,
},
```

Call command with no value set, but flag set.
```
$ foo --faultyflag
```

## Observed behavior

When flag value is read, it returns true.

## Expected behavior

That it returns false.

## Additional context

/

## Want to fix this yourself?

We'd love to have more contributors on this project! If the fix for this bug is easily explained and very small, free free to create a pull request for it.
## Run `go version` and paste its output here

```
# paste `go version` output in here
```

## Run `go env` and paste its output here

```
# paste `go env` output in here
```

**Comment by zhousicong** [comment]
Thx,it's useful for me.

**Comment by dearchap** [comment]
This is correct behavior for boolean flags. To turn on a bool flag one need to just do

'''
--my-bool-flag
'''

To turn off the syntax is 

'''
--my-bool-flag=false
'''
