### ISSUE TITLE
q: Passing resources from Command to Subcommand

### ISSUE THREAD

**Issue by halvfigur** [urfave/cli#1313]
## Is it possible to pass a resource created in a Command down to its Subcommands?

Hi,

Is it possible to have a command initialize some resource and put it into the `cli.Context` so that it becomes available to Subcommands? I want to do something like this

$ mycmd db -connect=<addr> create <entry>
$ mycmd db -connect=<addr> update <entry>

where `db --connect` initializes some resource that is then passed down to the Subcommands. Is it possible to accomplish this without resorting to global variables? Can I somehow put the resource into the `context.Context` within `cli.Context` using `context.WithValue` (would that even be the proper way to go about this with urfave/cli/v2?).
 
Thank you!

**Comment by jakegut** [comment]
I was able to add data to the context like so: 

```go
app := &cli.App{
  Before: func(c *cli.Context) error {
    c.App.Metadata["db"] = gorm.Open(sqlite.Open("test.db"), &gorm.Config{})
    return nil
  },
}
```
  
  And then getting the value from the context:
  ```go
  func action (c *cli.Context) error {
    db := c.App.Metadata["db"].(*gorm.DB)
    ...
  }
  ```

**Comment by halvfigur** [comment]
Great thanks!
