### ISSUE TITLE
Is there an easy way to toggle the Required attribute of a cli.Flag ?

### ISSUE THREAD

**Issue by zhiqiangxu** [urfave/cli#1329]
Now I have to create separate `cli.Flag` flag instances for `Required` and `Optional`, which is quite tedious:

```golang
// HeightFlag ...
var HeightFlag = cli.IntFlag{
	Name:     "height",
	Usage:    "specify height",
	Required: true,
}

// OptionalHeightFlag ...
var OptionalHeightFlag = cli.IntFlag{
	Name:  "height",
	Usage: "specify optional height",
}
```

**Comment by Necoro** [comment]
What about 
```
OptionalHeightFlag := HeightFlag
OptionalHeightFlag.Required = False
```

**Comment by zhiqiangxu** [comment]
> What about
> 
> ```
> OptionalHeightFlag := HeightFlag
> OptionalHeightFlag.Required = False
> ```

It still requires 2 variables, if there is a method like `toggleRequired()`, then only 1 is enough.

**Comment by dearchap** [comment]
Interface cannot be update to include these functions at this point. Please consider using v3x
