### ISSUE TITLE
correct way to enable autocompletion in zsh

### ISSUE THREAD

**Issue by varun06** [urfave/cli#1332]
I am adding auto completion to my cli app. I am following doc and set `app.EnableBashCompletion = true` and made changes to zsh shell config. But we I am trying to auto complete, I am getting these errors in shell.

```
fatal error: flag provided but not defined: -generate-bash-completion
fatal error: flag provided but not defined: -generate-bash-completion
fatal error: flag provided but not defined: -generate-bash-completion
\ \ \ alerts,\ a\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ Alert\ operations
```
  
am I missing something?

**Comment by dearchap** [comment]
@varun06 did you export PROG to name of your executable and source the zsh completion file ?

**Comment by dearchap** [comment]
@varun06 There was a bug in earlier versions which might have caused this. Can you try with latest release ?
