### ISSUE TITLE
q: Are there plans for new releases?

### ISSUE THREAD

**Issue by binwiederhier** [urfave/cli#1333]
Thank you for a fantastic library! I've used it in many of my projects.

My question is: The last release was in 2020, and it's obvious that you guys are still working on the lib. Are there plans for new releases any time soon? I've found a bug that I was going to report, but I saw it's fixed in master. I'm just curious.

**Comment by rliebz** [comment]
Hopefully this weekend: https://github.com/urfave/cli/pull/1326#issuecomment-1026904132

**Comment by tomaswarynyca** [comment]
Any news? :rocket:

**Comment by asahasrabuddhe** [comment]
Sorry for the delay. Release v2.4.0 is live - https://github.com/urfave/cli/releases/tag/v2.4.0

**Comment by binwiederhier** [comment]
Much appreciated. I was most excited about the `App.Reader` propagation bug in subcommands (in https://github.com/urfave/cli/pull/1225 via @Coderlane). Thank you folks.
