### ISSUE TITLE
Add `UInt64Slice`

### ISSUE THREAD

**Issue by td0m** [urfave/cli#1334]
## Checklist

* [x] Are you running the latest v2 release? The list of releases is [here](https://github.com/urfave/cli/releases).
* [x] Did you check the manual for your release? The v2 manual is [here](https://github.com/urfave/cli/blob/master/docs/v2/manual.md)
* [x] Did you perform a search about this feature? Here's the [Github guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## What problem does this solve?

It seems like `urfave/cli` doesn't currently support Uint64 slices, but supports `Int64Slice` and `UintSlice`. Is there a specific reason why?

## Solution description

Could we incorporate this a `Uint64Slice` flag into a new release?

## Describe alternatives you've considered

Copy-pasting the code for uintslice into my own code... But it would be nice to have this officially supported.

**Comment by dearchap** [comment]
@meatballhat I can take this up

**Comment by dearchap** [comment]
Fixed in release v2.16.0
