### ISSUE TITLE
Zsh autocompletion not working

### ISSUE THREAD

**Issue by AnuragThePathak** [urfave/cli#1341]
Zsh autocompletion not working in Fedora 35

Hello I was trying to get completions in a cli app. I have followed instructions as provided [here](https://github.com/urfave/cli/blob/master/docs/v2/manual.md#bash-completion). I was trying to use default auto-completion only at this moment. I got the completions working in bash but in zsh it is not working.

I have set the .zshrc file as mentioned here, and the script I have downloaded to source in .zshrc is [this one](https://github.com/urfave/cli/blob/master/autocomplete/zsh_autocomplete).

Everything seems fine to me, but still when I press tab to get completions I only get to see list of files in the directory only.

**Comment by dearchap** [comment]
@AnuragThePathak Did you replace the $PROG in the  zsh autocomplete with the name of your binary ?

**Comment by AnuragThePathak** [comment]
I exported the name of the binary as PROG environment variable.

**Comment by dearchap** [comment]
Just a sanity check. Did you export PROG prior to sourcing the completion file?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by AnuragThePathak** [comment]
Yes I did that

**Comment by dearchap** [comment]
can you share the snippet of .zshrc where you do this ?

**Comment by dearchap** [comment]
@AnuragThePathak I tried to reproduce this and I couldnt. I compiled a test app, set PROG to test app name and sourced the zsh_autocomplete file provided in this repo and it worked.

**Comment by AnuragThePathak** [comment]
Thanks for the info @dearchap. As of now, the project that needed it is archived, so anyways I am no longer concerned about it.
