### ISSUE TITLE
Responsive and friendly Documentation page

### ISSUE THREAD

**Issue by saintmalik** [urfave/cli#1343]
## Checklist

* [X] Are you running the latest v2 release? The list of releases is [here](https://github.com/urfave/cli/releases).
* [X] Did you check the manual for your release? The v2 manual is [here](https://github.com/urfave/cli/blob/master/docs/v2/manual.md)
* [x] Did you perform a search about this feature? Here's the [Github guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## What problem does this solve?

A clear and concise description of what problem this feature would solve. For example:

- It makes it easy for users to consume the guides about this open source project

## Solution description

A detailed description of what you want to happen.

Having a docs.domain.com or domain.com/docs page is really great and gets very fast accessibility to users.

**Comment by meatballhat** [comment]
FYI fellow @urfave/cli and @urfave/maintainers folks, I squatted urfave.org (via dnsimple) with intent to experiment with docs hosting. If interested, I'm ready to do stuff like adding a `.github` repo and doing CNAME things or whatever is needed.

**Comment by saintmalik** [comment]
Sure, I am interested

**Comment by rliebz** [comment]
I've had some success with mkdocs and GitHub pages in the past. My criteria were being able to write plain markdown, having a simple build process I could replicate locally and in CI, having minimal configuration.

For reference:
- The docs: https://rliebz.github.io/tusk/
- [The config](https://github.com/rliebz/tusk/blob/ea333e20b6136b048a120e03afdfb2ca4cc479bf/mkdocs.yml)
- [The documentation](https://github.com/rliebz/tusk/tree/ea333e20b6136b048a120e03afdfb2ca4cc479bf/docs) (notably the README and contributing guide are symlinked to avoid duplication)
- [The CI job](https://github.com/rliebz/tusk/blob/ea333e20b6136b048a120e03afdfb2ca4cc479bf/.circleci/config.yml#L81-L97) (should be easy to do with GH actions, and support for GH pages is built in)
- `mkdocs serve` to get a local server going
- Contributing is just plain old markdown if you don't want to mess around with the mkdocs CLI

The executable you can get with pip or homebrew, and if you don't care about downloading a fancy not-built-in theme, that and a working python environment are the only dependencies.

I looked at a couple other tools a few years back when I set that up, and typically the things that pushed me away were complex configs or needing to check in HTML/Javascript/etc. to get a basic "hello world" up, whereas `mkdocs` was very tightly designed for the exact use case I had—having markdown and wanting a documentation page.

**Comment by saintmalik** [comment]
Yeah, mkdocs is also great and awesome, but have you checked docusaurus? its less complex and easy, little to no configurations and you can spin it up locally via cli too, and a simple ``docusaurus serve`` will get it up.

The easiness and nice design is a great thing to also consider.

**Comment by meatballhat** [comment]
@saintmalik Are you up for proposing something using docusaurus in a PR?

**Comment by dearchap** [comment]
I think mkdocs should be good enough. docusaurus is js which is not my cup of tea

**Comment by saintmalik** [comment]
> @saintmalik Are you up for proposing something using docusaurus in a PR?

Yeah sure, am up

**Comment by saintmalik** [comment]
> I think mkdocs should be good enough. docusaurus is js which is not my cup of tea

Yeah I understand,

If you don't like docusaurus because it's js based, it's okay, mkdocs is okay too

**Comment by meatballhat** [comment]
@saintmalik Are you available to take a look at #1392 ?

**Comment by saintmalik** [comment]
> @saintmalik Are you available to take a look at #1392 ?

Yeah, on it
