### ISSUE TITLE
(re)introduce flag type generation

### ISSUE THREAD

**Issue by meatballhat** [urfave/cli#1381]
## Checklist

* [x] Are you running the latest v2 release? The list of releases is [here](https://github.com/urfave/cli/releases).
* [x] Did you check the manual for your release? The v2 manual is [here](https://github.com/urfave/cli/blob/main/docs/v2/manual.md).
* [x] Did you perform a search about this feature? Here's the [GitHub guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## What problem does this solve?

There are a non-trivial number of bugs related to inconsistent flag type behavior that have been reported since the deletion of the last iteration of flag type generation. Re-enabling a (modernized) flag type generation strategy promises to eliminate such differences between flag types and also ease the burden of implementing new flag types.

## Solution description

I would like to try a Go template based approach similar to those used in [other](https://github.com/kubernetes-sigs/kubebuilder) [projects](https://github.com/kyleconroy/sqlc) where the input to the flag generation is a terse YAML file with very light support for configurable overrides.

## Describe alternatives you've considered

Earlier implementations of flag generation in this project were implemented first in Python and then in Go and then _mostly deleted_. I have attempted to get an idea of what influenced the decision to remove flag generation in the past to better inform whether or not this issue is even worth opening 😅, but feedback has been pretty sparse so far. I'm happy to keep talking about how we arrived at these decisions, but I would also like to Try Again and see what others think.

**Comment by dearchap** [comment]
I still think its a good idea. The only problem may have been if a certain flag type needs some customization which deviates from other types. I would prefer go generation mechanism since that would require no new tools except for go 1.14+ . Have to check if this would be a problem for users using pre go 1.14 versions when they include this library.

**Comment by meatballhat** [comment]
I think we can safely say that we don't support Go `<= 1.14` since the Go team themselves don't support it anymore.

**Comment by dearchap** [comment]
Do you have a small sample of what you have in mind reg code generation ?

**Comment by meatballhat** [comment]
@dearchap I'll have a PR up soon, I think 🤞🏼 I could have worked harder at keeping it smaller 😂
