### ISSUE TITLE
"--" not present in c.Args() between v1.22.5 & v1.22.6

### ISSUE THREAD

**Issue by decentral1se** [urfave/cli#1447]
## My urfave/cli version is

v1.22.5

## Checklist

- [x] Are you running the latest v1 release? The list of releases is [here](https://github.com/urfave/cli/releases).
- [x] Did you check the manual for your release? The v1 manual is [here](https://github.com/urfave/cli/blob/main/docs/v1/manual.md).
- [x] Did you perform a search about this problem? Here's the [Github guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## Dependency Management

- My project is using go modules.

## Describe the bug

`./cmd arg1 -- foo` & `./cmd arg1 -- foo` do different things between the two versions.

in `.5` `c.Args()` is `[arg1 -- foo]` and in `.6` it is `[arg1 foo]`.

## To reproduce

Switch between versions, pass `--` to the command, check `c.Args()`.

## Observed behavior

`--` is not parsed and it was before.

## Expected behavior

`--` is parsed correctly and handed to `c.Args()`.

## Additional context

Another report: https://git.coopcloud.tech/coop-cloud/organising/issues/336

## Run `go version` and paste its output here

```
go version go1.18.3 linux/amd64
```

**Comment by dearchap** [comment]
@decentral1se I believe this was intentional. @meatballhat should be able to provide more info

**Comment by decentral1se** [comment]
Thanks @dearchap! It would then be definitely good to hear from @meatballhat about this. Currently pinning to v1.22.5 as my code attempts to detect if the `--` was present, so this broke it :sweat_smile:

**Comment by meatballhat** [comment]
Hey @decentral1se sorry for my delay. @dearchap is right: this behavior change was intentional and considered a bug fix.

Are you able to upgrade to the latest in the 1.22.x series (currently 1.22.9) knowing that this behavior is correct/expected and won't revert to including the `"--"` delimiter?

**Comment by decentral1se** [comment]
Yebbo, will figure something out, thanks for the updates!
