### ISSUE TITLE
No releases anymore?

### ISSUE THREAD

**Issue by xoxys** [urfave/cli#1468]
Hi, are there no GH releases anymore? There were a **lot** of tags created during the last hours, but no corresponding GH Releases + Changelog. Is this intended?

**Comment by dearchap** [comment]
I created the tags just for reference. Im waiting on @meatballhat to make the releases. Im not aware of how to create the change log for a release automatically



Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Robert Kaussow ***@***.***>
Sent: Thursday, September 1, 2022 11:04:23 AM
To: urfave/cli ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [urfave/cli] No releases anymore? (Issue #1468)


Hi, are there no GH releases anymore? There were a lot of tags created during the last hours, but no corresponding GH Releases + Changelog. Is this intended?

**Comment by xoxys** [comment]
The problem is, tags will create a proper release of the package on gopkg and update mechanisms like dependabot, renovate or even `go mod update` will fetch those versions already. That's why creating a lot of tags "just for reference" without a real release is IMO not a good way in this context.

![image](https://user-images.githubusercontent.com/3391958/187951205-d51875c9-bfc6-40ad-8d58-d59ee399d8b7.png)

**Comment by AkihiroSuda** [comment]
The v2.14.0 tag was removed?
https://github.com/urfave/cli/releases/tag/v2.14.0 is now 404

**Comment by meatballhat** [comment]
@dearchap hey I'm afraid I made the situation worse by not catching up on notifications before pushing a completely different tag 😐  I'm happy to try to clean this up, and I think I could also do a better job of describing the norms and process in `docs/RELEASING.md`.

**Comment by meatballhat** [comment]
The process I'm using goes like:

```sh-session
$ curl -s https://proxy.golang.org/github.com/urfave/cli/v2/@v/v2.11.5.info | jq -r .Origin.Hash
dac1c40ee53c6d210a69ec9b98b1e21f342af667
$ git tag -sam 'Release 2.11.5' v2.11.5 dac1c40ee53c6d210a69ec9b98b1e21f342af667
$ git push origin v2.11.5
```

**Comment by meatballhat** [comment]
I'm done backfilling annotated tags that match what's in the go package cache and creating github-level releases 👍🏼 Thanks your your patience, @xoxys!

**Comment by xoxys** [comment]
Feel free to close the issue. Everything clarified from my side.
