### ISSUE TITLE
Is there a way to disable help info when all parameters are provided?

### ISSUE THREAD

**Issue by Stoica-Mihai** [urfave/cli#1470]
So I made a simple cli app and everytime I run it, even if all the parameters were provided, the help info is being printed first and after the app executes. Is there a way to only show the help menu when an arguments is missing/wrong or when you explicitly set the help flag to be displayed?

Thanks.

**Comment by meatballhat** [comment]
This sounds like unexpected behavior to me 🤔 Are you able to provide any example code?

**Comment by Stoica-Mihai** [comment]
Thanks for your replay @meatballhat 
Here is the example code:
`package main

import (
	"fmt"
	"os"

	"github.com/urfave/cli/v2"
)

func main() {
	region, expiration := flags()

	fmt.Println("Region", region)
	fmt.Println("Expiration", expiration)
}

func flags() (string, int) {
	var region string
	var expiration int
	app := &cli.App{
		Flags: []cli.Flag{
			&cli.StringFlag{
				Name:        "region",
				Aliases:     []string{"r"},
				Value:       "region value",
				Usage:       "Assigns the region",
				Destination: &region,
				Required:    false,
			},
			&cli.IntFlag{
				Name:        "expiration",
				Aliases:     []string{"e"},
				Value:       3600,
				Usage:       "Assign the credentials expiration time",
				Destination: &expiration,
				Required:    false,
			},
		},
	}

	if err := app.Run(os.Args); err != nil {
		panic(err)
	}

	return region, expiration
}
`
Running it without providing any flags or adding an optional flag will always print first the help and after the the values

**Comment by dearchap** [comment]
@Stoica-Mihai The default action for App is to show the help . If you'd like to disable that you can have a simple action as follows

```
app := &cli.App{
      ....
     Action: func(c *cli.Context) error {
           return nil
     },
}
```

This is expected behaiour. You can actually move your prints to within the action

```
app := &cli.App{
      ....
     Action: func(c *cli.Context) error {
        fmt.Println("Region", region)
	fmt.Println("Expiration", expiration)
     },
}
```
which is what you should normally use.

**Comment by Stoica-Mihai** [comment]
@dearchap thank you for the explanation. This is the result I was trying to achieve.
