### ISSUE TITLE
String slice parsed twice while UseShortOptionHandling is used

### ISSUE THREAD

**Issue by rprtr258** [urfave/cli#1500]
## My urfave/cli version is

v2.16.3

## Checklist

- [x] Are you running the latest v2 release? The list of releases is [here](https://github.com/urfave/cli/releases).
- [x] Did you check the manual for your release? The v2 manual is [here](https://github.com/urfave/cli/blob/main/docs/v2/manual.md)
link not valid, but checking [docs](https://cli.urfave.org/v2/examples/combining-short-options/) says
> If you enable UseShortOptionHandling, then you must not use any flags that have a single leading - or this will result in failures. For example, -option can no longer be used. Flags with two leading dashes (such as --options) are still valid.
Though in my example it works wrong even with two dashes.
- [x] Did you perform a search about this problem? Here's the [Github guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.
I guess [this](https://github.com/urfave/cli/issues/1113) might be linked to the issue, but not sure about doubling.

## Dependency Management

- My project is using go modules.

## Describe the bug

In following code
```go
package main

import (
	"fmt"
	"log"
	"os"

	"github.com/urfave/cli/v2"
)

func main() {
	var (
		_inherit  bool
		_verbose  bool
		_envFiles = cli.NewStringSlice()
	)
	app := &cli.App{
		Flags: []cli.Flag{
			&cli.StringSliceFlag{Name: "env", Aliases: []string{"e"}, Destination: _envFiles},
			&cli.BoolFlag{Name: "verbose", Aliases: []string{"v"}, Destination: &_verbose},
			&cli.BoolFlag{Name: "inherit", Aliases: []string{"i"}, Destination: &_inherit},
		},
		Action: func(ctx *cli.Context) error {
			fmt.Println(_envFiles, _verbose, _inherit)
			return nil
		},
		HideHelpCommand:        true,
		UseShortOptionHandling: true,
	}
	if err := app.Run(os.Args); err != nil {
		log.Fatal(err)
	}
}
```

It handles 2 boolean args and one string slice arg and prints them (for simplicity). Depending on args order string slice might be doubled:
```bash
# expected not to double file
$ go run main.go -e file -vi
[file file] true true
$ go run main.go --env file -vi
[file file] true true
# works as expected
$ go run main.go -vi --env file
[file] true true
$ go run main.go -vi --env file
[file] true true
$ go run main.go -e file -v -i
[file] true true
$ go run main.go --env file -v -i
[file] true true
```

## To reproduce

Use code described above and run it as described above (e.g. `go run main.go --env file -vi`).

## Observed behavior

Described above.

## Expected behavior

Described above.

## Additional context

-

## Want to fix this yourself?
-

## Run `go version` and paste its output here

```
go version go1.19 linux/amd64
```

## Run `go env` and paste its output here
<details>

```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/user/.cache/go-build"
GOENV="/home/user/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/user/go/pkg/mod"
GONOPROXY="gitlab.private.kvado.ru/*"
GONOSUMDB="gitlab.private.kvado.ru/*"
GOOS="linux"
GOPATH="/home/user/go"
GOPRIVATE="gitlab.private.kvado.ru/*"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/user/rwenv/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3163294833=/tmp/go-build -gno-record-gcc-switches"
```

</details>

**Comment by dearchap** [comment]
@rprtr258 Yes this is definitely a bug. Its probably been there for a very long time but surprisingly no one has run into it till now. Let me send out a PR for this. Thanks for reporting.
