### ISSUE TITLE
Pass Arguments Directly

### ISSUE THREAD

**Issue by str1ngs-bytes** [urfave/cli#1529]
Commands: []*urfave.Command{
			{
				Name:    "clear",
				Aliases: []string{"cls"},
                         --> Arguments: []string{"oneline","all"},
				Action: func(ctx *urfave.Context) error {
					clearTerminal()
					return nil
				},
			},
                   }

## Another feature that would be nice is to have is availability to make any one flag required out of 2 or more.

**Comment by dearchap** [comment]
@str1ngs-bytes the one flag required out of 2 or more is covered by issue #1222 . Also I really fail to see the value of providing Args. Cant the Action check if len(ctx.Args()) == 0 and then use a preset value.

**Comment by dearchap** [comment]
@urfave/cli any ideas on this ?

**Comment by abitrolly** [comment]
I need a more complete example to get what's going on. What is the required interface?

```
app clear <oneline|all>
```

**Comment by dearchap** [comment]
No response from original issuer. Closing
