### ISSUE TITLE
Int64Slice not support by read toml file

### ISSUE THREAD

**Issue by Edelweiss-Snow** [urfave/cli#1550]
## Checklist

* [x] Are you running the latest v2 release? The list of releases is [here](https://github.com/urfave/cli/releases).
* [x] Did you check the manual for your release? The v2 manual is [here](https://github.com/urfave/cli/blob/main/docs/v2/manual.md).
* [x] Did you perform a search about this feature? Here's the [GitHub guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## What problem does this solve?
I used toml file input configuration, toml parsing int variables will become int64, but this file altsrc/map_input_source.go does not support int64Slice，toml Unmarshal number (example:1,2,3) will become int64 (1,2,3), so i nedd it

A clear and concise description of what problem this feature would solve. For example:

- needing to type out the full flag name takes a long time, so I
  would like to suggest adding auto-complete
- I use (osx, windows, linux) and would like support for (some
  existing feature) to be extended to my platform
- the terminal output for a particular error case is confusing, and
  I think it could be improved

## Solution description

A detailed description of what you want to happen.

## Describe alternatives you've considered

A clear and concise description of any alternative solutions or
features you've considered.

**Comment by dearchap** [comment]
PR #1551
