### ISSUE TITLE
How to escape "," in StringSliceValue

### ISSUE THREAD

**Issue by kameshsampath** [urfave/cli#1552]
I am trying to see if the `,` can be used as such when present in a flag value .

e.g. 

```go
package main

import (
	"log"
	"os"

	"github.com/urfave/cli/v2"
)

func main() {
	var cacheFrom cli.StringSlice
	app := &cli.App{
		Flags: []cli.Flag{
			&cli.StringSliceFlag{
				Name:        "cache-from",
				Usage:       "images to consider as cache sources",
				Destination: &cacheFrom,
			},
		},
		Action: func(c *cli.Context) error {
			log.Printf("Flag %s", cacheFrom.Value())
			for _, arg := range cacheFrom.Value() {
				log.Printf("Cache --> %s", arg)
			}
			return nil
		},
	}

	if err := app.Run(os.Args); err != nil {
		log.Fatal(err)
	}
}

```

when run `go run main.go --cache-from='type=registry,registry=example/foo'` I see the following output,

```shell
2022/10/29 19:11:53 Flag [type=registry registry=example/foo]
2022/10/29 19:11:53 Cache --> type=registry
2022/10/29 19:11:53 Cache --> registry=example/foo
```
Ideally I don't expect the value to be split by `,`. 

Is this bug or there is way to configure it ?

This causing another lib that uses CLI to fail https://github.com/thegeeklab/drone-docker-buildx/issues/141

**Comment by dearchap** [comment]
@kameshsampath PR #1546 has a fix for this. It allows you to set the separator to something else. The PR has been merged but release has not been tagged yet. It should be out any day now.

**Comment by kameshsampath** [comment]
super thanks @dearchap , looking forward to it :)
