### ISSUE TITLE
panic: flag redefined

### ISSUE THREAD

**Issue by hagen1778** [urfave/cli#1560]
## My urfave/cli version is 

_**v2.23.0**_

## Checklist

- [x] Are you running the latest v2 release? The list of releases is [here](https://github.com/urfave/cli/releases).
- [x] Did you check the manual for your release? The v2 manual is [here](https://github.com/urfave/cli/blob/main/docs/v2/manual.md)
- [x] Did you perform a search about this problem? Here's the [GitHub guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## Dependency Management

- My project is using go modules.
- My project is using vendoring.

## Describe the bug

With https://github.com/urfave/cli/commit/ae8d932413452718007ff70a4e50ccf9729afd87 `urfave/cli/v2` starts to conflict with other dependencies which has the same flags. In my case, it is `version` flag exposed by both `urfave/cli/v2` and one of my other dependencies. This broke a build once I get updated the library.

## To reproduce

Create an app that has a defined `version` flag or imports any dependency which has the same flag. Then use `urfave/cli/v2@2.23.0` and try to run the app.

## Observed behavior
```
myapp flag redefined: version
panic: myapp flag redefined: version
```

## Expected behavior

Do not interfere with other dependencies flags.

**Comment by dearchap** [comment]
@hagen1778 Can you set App.HideVersion to true so that the cli library doesnt append version flag ?

**Comment by hagen1778** [comment]
Thanks for quick response @dearchap! App.HideVersion  helped.

**Comment by johejo** [comment]
For example, it confuses many users to panic just by importing github.com/golang/glog.

https://go.dev/play/p/WAxoXS_BHib
