### ISSUE TITLE
how to build command without sub command 

### ISSUE THREAD

**Issue by y1rn** [urfave/cli#1566]
this is  [official demo with required flag](https://go.dev/play/p/3XapqAxcQOr)

## output
```
NAME:
   play - A new cli application

USAGE:
   play command [command options] [arguments...]

COMMANDS:
   help, h  Shows a list of commands or help for one command

OPTIONS:
   --lang value  language for the greeting (default: "english")
   --help, -h    show help (default: false)
2009/11/10 23:00:00 Required flag "lang" not set

Program exited.
```
## expect
<pre><code>
NAME:
   play - A new cli application

USAGE:
  play  <del>command</del> [<del>command</del> options] [arguments...]

<del>COMMANDS:</del>
 <del>  help, h  Shows a list of commands or help for one command</del>

OPTIONS:
   --lang value  language for the greeting (default: "english")
   --help, -h    show help (default: false)
2009/11/10 23:00:00 Required flag "lang" not set

Program exited.
</code></pre>

**Comment by dearchap** [comment]
@y1rn Yes this is by design. Would you like to submit a PR to fix this ?
