### ISSUE TITLE
Nested help command has a incorrect HelpName

### ISSUE THREAD

**Issue by remiposo** [urfave/cli#1570]
## My urfave/cli version is

v2.23.4

## Checklist

- [x] Are you running the latest v2 release? The list of releases is [here](https://github.com/urfave/cli/releases).
- [x] Did you check the manual for your release? The v2 manual is [here](https://github.com/urfave/cli/blob/main/docs/v2/manual.md)
- [x] Did you perform a search about this problem? Here's the [GitHub guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## Dependency Management

- My project is using go modules.

## Describe the bug

Help command has a help subcommand in default, so you can show help of help like `cmd help help`.
However, since help commands internally refers to the same object, its HelpName is not updated and incorrect value is displayed.

## To reproduce

```go
func main() {
	(&cli.App{
		Name: "a",
		Commands: []*cli.Command{
			{
				Name:        "b",
				Subcommands: []*cli.Command{{Name: "c"}},
			},
		},
	}).Run(os.Args)
}
```

```
$ a b c help help

NAME:
   a b help - Shows a list of commands or help for one command

USAGE:
   a b help [command options] [command]

OPTIONS:
   --help, -h  show help (default: false)
```

## Want to fix this yourself?

In the first place, for me, it's strange to be able to call help of help.
If there're no problems, I'd like to solve by enabling `HideHelp` of help command.
I'd appreciate your opinion.

**Comment by dearchap** [comment]
@remiposo Yes that would be good. Can you submit a PR ? Also dont forget to add unit tests for it. TIA
