### ISSUE TITLE
Add StringMap flag

### ISSUE THREAD

**Issue by avorima** [urfave/cli#1580]
## Checklist

* [x] Are you running the latest v2 release? The list of releases is [here](https://github.com/urfave/cli/releases).
* [x] Did you check the manual for your release? The v2 manual is [here](https://github.com/urfave/cli/blob/main/docs/v2/manual.md).
* [x] Did you perform a search about this feature? Here's the [GitHub guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## What problem does this solve?

There is no string mapping flag so I usually end up using a string slice and then splitting the elements into key/value pairs. pflag has the option to use the StringToString flag: https://github.com/spf13/pflag/blob/master/string_to_string.go.

## Solution description

Add a `StringMapFlag` and `StringMap` type that can be used like `StringSlice/Flag`, but is backed by a `map[string]string` and splits the elements accordingly with validation. Separator could be configurable, but I think `=` is a common default.

## Describe alternatives you've considered

Create a custom flag, but that would be even more boilerplate than now.

**Comment by dearchap** [comment]
@avorima We are not adding any new features to v2. Would you like to submit a PR for this for v3 ?

**Comment by dearchap** [comment]
yes please use main.

**Comment by artemklevtsov** [comment]
Will there be support for altsrc?

**Comment by dearchap** [comment]
@artemklevtsov would you like to submit a PR for altsrc ?

**Comment by artemklevtsov** [comment]
Hm... I'll digging into it.

**Comment by dearchap** [comment]
@artemklevtsov Lets continue this conversation in issue #1634
