### ISSUE TITLE
There are two problems when loading yaml (slice, Uint64 flags)

### ISSUE THREAD

**Issue by kjeom** [urfave/cli#1592]
test.yaml
```yaml
scope: 
  test: 
    - test1
    - test2
test: 
  temp: 
    test: 1
```
testYaml.go
```go
func main() {
	flags := []cli.Flag{
		&cli.StringFlag{
			Name:  "config",
			Usage: "yaml config file name",
		},
		altsrc.NewUint64Flag(
			&cli.Uint64Flag{
				Name:        "test.temp.test",
				Aliases:     []string{},
				Value:       0,
				Destination: &test,
			},
		),
		altsrc.NewStringSliceFlag(
			&cli.StringSliceFlag{
				Name:    "scope.test",
				Aliases: []string{},
				EnvVars: []string{},
			},
		),
	}

	app := &cli.App{
		Flags:  flags,
		Before: altsrc.InitInputSourceWithContext(flags, altsrc.NewYamlSourceFromFlagFunc("config")),
		Action: func(ctx *cli.Context) error {
			if ctx.IsSet("scope.test") {
				fmt.Println("true", ctx.StringSlice("scope.test"))
			} else {
				fmt.Println("false", ctx.StringSlice("scope.test"))
			}
			if ctx.IsSet("test.temp.test") {
				fmt.Println("true", ctx.Uint64("test.temp.test") {
			} else {
				fmt.Println("false", ctx.Uint64("test.temp.test")
			}
			return nil
		},
	}
	fmt.Println(app.Run(os.Args))
}
```
- Expected Result
  - scope.test : true [test1 test2]
  - test.temp.test : true 1
- Result
  - scope.test : **false** [test1 test2]
  - test.temp.test : **false** **0**

- Reason
  - slice : not setting flagSet (https://github.com/urfave/cli/blob/v2-maint/altsrc/flag.go#L114)
  - Uint64: there is no receiver function for Uint64 (https://github.com/urfave/cli/blob/v2-maint/altsrc/flag.go#L66)

**Comment by dearchap** [comment]
@kjeom The ctx.IsSet behaviour is expected since that function returns true if the flag has been set from the cmd line. Think of loading envvars, yaml files etc to set the default value of the flag which can then be modified from cmdline. yes the uint64 isnt implemented. Seems like a simple fix. Would you like to submit a PR ?

**Comment by lobachpavel** [comment]
Hi

here is the full list of the flag types which do not implement the FlagInputSourceExtension interface (ApplyInputSourceValue):
* Float64SliceFlag
* Int64Flag
* Uint64Flag
* UintFlag

so they can not be loaded from external config file

Also I do not agree about the ctx.IsSet() behaviour:
Currently this function returns true for most of the flag types, when the default value is overridden by env variable or loaded via altsrc. I guess it should be consistent throughout the all flag types.
