### ISSUE TITLE
Multiple (sub)commands from the terminal

### ISSUE THREAD

**Issue by 0cv** [urfave/cli#1595]
I'd like to execute subcommands from the CLI to not execute the CLI from the beginning again for different reasons (context, real-time info provided to the user in the terminal, etc.) - and have something interactive.

As far as I understood, when running a subcommand, arguments are evaluated immediately. I can't find a way for a user to provide new input (from stdin) to the CLI. Is that possible or it's actually a feature request?

EDIT: I know I could listen to the input and then execute that input. But I'm also leveraging the bash auto completion (`EnableBashCompletion`), so this would not work.

**Comment by dearchap** [comment]
@0cv This seems like a feature for an interactive terminal if I'm not mistaken. I'm afraid that is not possible with this library
