### ISSUE TITLE
`ToJSON` or JSON format for import/export of CLI options

### ISSUE THREAD

**Issue by abitrolly** [urfave/cli#1607]
I wonder if it is possible to create a generic options definition serialization/exchange format in JSON?

Then the stuff like Markdown help, man pages and command line completion (https://github.com/urfave/cli/pull/1606/files) could be generated from that JSON format by external tools without bloating the size of `urfave/cli` binaries (https://github.com/urfave/cli/discussions/1594).

I already tried to play with that a bit with Python here - https://github.com/abitrolly/podman-compose/commit/0cd4197a90453dbb299aab8e8b6c3d0191e59d16 - so it is possible to extract that bit to see if `urfave/cli` export and Python `argparse` export can be compatible.

**Comment by dearchap** [comment]
@abitrolly yes I'm sure its possible. The completion here in cli is minimal except for the fish completion code. Do you have any serialization formats and tools in mind for this ?

**Comment by abitrolly** [comment]
I have no particular format in mind. It should probably [be designed](https://modern-json-schema.com/json-schema-is-a-constraint-system) from scratch.  The use case is to generate everything that is currently possible (man, markdown, completions) given just the JSON.

**Comment by abitrolly** [comment]
Another way this could be useful - generate markdown parameter tables to `README.md` https://github.com/Zxilly/animated-timeline
