### ISSUE TITLE
Broken bash completions when using a shell different from the login shell

### ISSUE THREAD

**Issue by Arsen6331** [urfave/cli#1609]
## My urfave/cli version is

_v2.23.5_

## Checklist

- [x] Are you running the latest v2 release? The list of releases is [here](https://github.com/urfave/cli/releases).
- [x] Did you check the manual for your release? The v2 manual is [here](https://github.com/urfave/cli/blob/main/docs/v2/manual.md)
- [x] Did you perform a search about this problem? Here's the [GitHub guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## Dependency Management

- My project is using go modules.

## Describe the bug

On Arch Linux, bash completions seem to also provide parts of the description as options.

## To reproduce

Enable bash completions in the app, and install the `bash_autocomplete` file as `/usr/share/bash-completion/completions/lure`

## Observed behavior

I saw parts of the description in the options in bash:

![image](https://user-images.githubusercontent.com/41810442/205172176-7e92f759-2429-4625-836c-d91cbf08375c.png)

## Expected behavior

I expected it to be more like what zsh does with the same program:

![image](https://user-images.githubusercontent.com/41810442/205172238-c934e88f-5435-47e6-bce5-2906e431b925.png)

## Additional context

Git repo: https://github.com/Arsen6331/lure

## Want to fix this yourself?

We'd love to have more contributors on this project! If the fix for
this bug is easily explained and very small, feel free to create a
pull request for it.

## Run `go version` and paste its output here

```
go version go1.19.3 linux/amd64
```

## Run `go env` and paste its output here

```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/arsen/.cache/go-build"
GOENV="/home/arsen/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/arsen/.go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/arsen/.go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19.3"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3702642075=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by Arsen6331** [comment]
Looking at the bash documentation, it doesn't seem to support the "command:Description" format that zsh does. `compgen -W` interprets the wordlist as a list of words separated by characters in the `$IFS` variable, so it just gets separated by the spaces as well as the newlines.

The only solution I can see is to generate the completion options separately using `--generate-zsh-completion` for zsh and the current `--generate-bash-completion` for bash.

**Comment by dearchap** [comment]
@Arsen6331 https://github.com/urfave/cli/blob/v2-maint/help.go line 150. We handle zsh separately from bash already. Can you confirm that your SHELL variable is set correctly ?

**Comment by Arsen6331** [comment]
I can submit a PR to do that if that seems like a better solution

**Comment by Arsen6331** [comment]
Hmm, actually, it seems those variables aren't exported, so that's not going to work

**Comment by Arsen6331** [comment]
Yeah, it seems the only reliable way to figure out which shell was used to run a process is to get the parent PID, and there's no cross-platform way to do this, so it's likely not going to be a good idea.
