### ISSUE TITLE
RunAsSubcommand has been broken

### ISSUE THREAD

**Issue by hsanjuan** [urfave/cli#1610]
## My urfave/cli version is

_**v2.25.0**_

## Checklist

- [x] Are you running the latest v2 release? The list of releases is [here](https://github.com/urfave/cli/releases).
- [x] Did you check the manual for your release? The v2 manual is [here](https://github.com/urfave/cli/blob/main/docs/v2/manual.md)
- [x] Did you perform a search about this problem? Here's the [GitHub guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## Dependency Management

- My project is using go modules.

## Describe the bug

On https://github.com/urfave/cli/commit/d5947d781442f834bf417ecd020ec9568206844b the `RunAsSubcommand` method was removed. It was re-added on https://github.com/urfave/cli/commit/00afca42c863a8ab6b551bc41817a1558f626fa7 as a deprecated stub.

However, `a.RunContext(ctx.Context, ctx.Args().Slice())` behaves differently than what `RunAsSubcommand` did. For example, all the global flags in the original `cli.Context` are lost, where RunAsSubcommand correctly transferred them.

I have not found a way to run dynamic subcommands (i.e. an app which generates different subcommands at runtime by creating a subApp and calling `subApp.RunAsSubcommand(origCtx)`. The subApp no longer has access to global flags defined in the parent app as before.

For me this is a breaking and silent behavior change, moreover since it arrived with absolutely no heads up: https://github.com/urfave/cli/releases/tag/v2.20.0. It seems unintended, therefore a bug.

## To reproduce

See above.

## Observed behavior

Sub-apps cannot get global flags anymore.

## Expected behavior

There should be a way to pass global flags to sub-apps.

## Want to fix this yourself?

I think removals were done for a reason that is in conflict with keeping this functionality.

## Run `go version` and paste its output here

```
go version go1.19.3 linux/amd64
```

**Comment by hsanjuan** [comment]
> @hsanjuan Can you provide a small example to illustrate this ? Doesnt the App/Command.Before function work for your purposes ?

Yes, of course @dearchap . Take the following:

```go
package main

import (
	"errors"
	"fmt"
	"os"

	"github.com/urfave/cli/v2"
)

func main() {
	app := cli.NewApp()
	app.Flags = []cli.Flag{
		&cli.StringFlag{
			Name:  "global-flag",
			Value: "global-flag-value",
		},
	}
	app.Action = func(c *cli.Context) error {
		if !c.Args().Present() {
			fmt.Println("no subcommand")
			return errors.New("no subcommand")
		}

		subCmdName := c.Args().Get(0)
		dynamicApp := cli.NewApp()
		dynamicApp.Name = subCmdName
		dynamicApp.Flags = []cli.Flag{
			&cli.StringFlag{
				Name:  "subcommand-flag",
				Value: "subcommand-flag-value",
			},
		}
		dynamicApp.Action = func(c *cli.Context) error {
			fmt.Println("you ran a dynamic subcommand:", subCmdName)
			fmt.Println("global-flag:", c.String("global-flag"))
			fmt.Println("subcommand-flag", c.String("subcommand-flag"))
			return nil
		}

		return dynamicApp.RunAsSubcommand(c)
	}
	app.Run(os.Args)
}
```

With urfave/cli v2.16.3, running `go run main.go example` prints:

```
~/u/cli $ go run main.go example
you ran a dynamic subcommand: example
global-flag: global-flag-value
subcommand-flag subcommand-flag-value
```

With urfave/cli v2.25.0:

```
~/u/cli $ go run main.go example
you ran a dynamic subcommand: example
global-flag:
subcommand-flag subcommand-flag-value
```

(The value of the global flag is gone).

**Comment by dearchap** [comment]
Thanks @hsanjuan I'll take a look.

**Comment by dearchap** [comment]
@hsanjuan Can you test this fix and see if it works for you ?

**Comment by hsanjuan** [comment]
@dearchap thanks, commented on the PR.
