### ISSUE TITLE
Missing RequiredFlag doesn't invoke OnUsageError

### ISSUE THREAD

**Issue by remiposo** [urfave/cli#1616]
## My urfave/cli version is

_**( Put the version of urfave/cli that you are using here )**_
v2.23.6

## Checklist

- [x] Are you running the latest v2 release? The list of releases is [here](https://github.com/urfave/cli/releases).
- [x] Did you check the manual for your release? The v2 manual is [here](https://github.com/urfave/cli/blob/main/docs/v2/manual.md)
- [x] Did you perform a search about this problem? Here's the [GitHub guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## Dependency Management

- My project is using go modules.

## Describe the bug

When a required flag not given, `OnUsageError` is not invoked and `AfterFunc` is invoked.
This is a different behavior than when `parseFlags` fails (e.g. an invalid flag given).
From the user's point of view, both are `UsageError`. Are these differences in specifications?

**Comment by dearchap** [comment]
@remiposo Good point. Generally I would think that specifying a non-existent flag or using a given flag incorrectly will trigger OnUsage error. RequiredFlags are really a higher level construct which asks the users to ensure that they provide these flags(either in env or file or cmdline). Is it a usage error if a required flag isnt provided ? Not really sure.
