### ISSUE TITLE
Bash completion doesn't work for subcommands of subcommands

### ISSUE THREAD

**Issue by tchandelle** [urfave/cli#1617]
## My urfave/cli version is

_**github.com/urfave/cli/v2 v2.23.6**_

## Checklist

- [x] Are you running the latest v2 release? The list of releases is [here](https://github.com/urfave/cli/releases).
- [x] Did you check the manual for your release? The v2 manual is [here](https://github.com/urfave/cli/blob/main/docs/v2/manual.md)
- [x] Did you perform a search about this problem? Here's the [GitHub guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## Dependency Management

- My project is using go modules.

## Describe the bug

Bash completion (arg `--generate-bash-completion` and option `EnableBashCompletion`) does not provide completion for subcommands of subcommands.

## To reproduce

https://go.dev/play/p/aO7adBNLVCf

## Observed behavior

It returns commands below *alpha*.
```
$ ./app alpha beta --generate-bash-completion
beta
help
h
```

## Expected behavior

It should returns commands below *beta*  (ie. *gamma*)

```
$ ./app alpha beta --generate-bash-completion
gamma
help
h
```

## Run `go version` and paste its output here

```
$ go version
go version go1.18.8 darwin/amd64
```

**Comment by dearchap** [comment]
@tchandelle Can you check if PR fixes your issue ? Thanks

**Comment by tchandelle** [comment]
Thanks @dearchap, that was fast! Yes it works!

**Comment by dearchap** [comment]
@tchandelle v2.23.7 has the fix. Thanks for raising the issue
