### ISSUE TITLE
Is it possible to change the "No help topic" message?

### ISSUE THREAD

**Issue by talwat** [urfave/cli#1619]
I want to be able to change this message to be custom, is this possible?

**Comment by dearchap** [comment]
@talwat Yes you can use App.CommandNotFound to register a custom handler for when a given command isnt found. 

https://github.com/urfave/cli/blob/v2-maint/app.go#L79

**Comment by dearchap** [comment]
You have use App.HideVersion to disable the version flag. What command and item do you want to keep in the help menu ?

**Comment by talwat** [comment]
I want to keep the `version` command and this item in the help menu:
```
VERSION:
   0.2.0
```

**Comment by dearchap** [comment]
There is no prebuilt version command. The App.HideVersion disables the inbuilt version **flag**. You can still use your own version command if you want. To keep the version string in the help menu you have to override the app help template

https://github.com/urfave/cli/blob/v2-maint/template.go#L34
