### ISSUE TITLE
Errors should go to stderr

### ISSUE THREAD

**Issue by dearchap** [urfave/cli#1623]
## Checklist

* [ x] Are you running the latest v3 release? The list of releases is [here](https://github.com/urfave/cli/releases).
* [ x] Did you check the manual for your release? The v3 manual is [here](https://github.com/urfave/cli/blob/main/docs/v3/manual.md).
* [ ]x Did you perform a search about this feature? Here's the [GitHub guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## What problem does this solve?

As per POSIX's recommendations, diagnostics and error messages should always be printed to the /dev/stderr.

## Solution description

Help output (when requested) should go to stdout
Any usage errors, flag errors should go to stderr

## Describe alternatives you've considered

PR #1204 was raised for this. However it has been based off of v2 which is in maintenance mode. So this would be a good feature to include in v3.

**Comment by abitrolly** [comment]
Are there any moderns standard with argumentation?
