### ISSUE TITLE
Release Number / tag mismatch

### ISSUE THREAD

**Issue by whi-tw** [urfave/cli#1625]
Unsure if this is a real issue, but it's definitely confusing!

The release number and tag don't match for the latest release: the tag is [v2.23.7](https://github.com/urfave/cli/tree/v2.23.7), but the release number is [v2.24.0](https://github.com/urfave/cli/releases/tag/v2.23.7). Got me a bit confused while trying to bump to use the latest, and my `go.mod` didn't agree with the releases here.

**Comment by dearchap** [comment]
@whi-tw Can you try now ? The release number is v2.23.7

**Comment by whi-tw** [comment]
Amazing, thank you! It wasn't a functional problem - everything still worked as expected, just I was confused when I couldn't `go get` v2.24.0. It made sense once I looked at the tag for the release!
