### ISSUE TITLE
Required=true in StringFlag allows empty string

### ISSUE THREAD

**Issue by ccremer** [urfave/cli#1632]
## My urfave/cli version is 

_**v2.23.7**_

## Checklist

- [x] Are you running the latest v2 release? The list of releases is [here](https://github.com/urfave/cli/releases).
- [x] Did you check the manual for your release? The v2 manual is [here](https://github.com/urfave/cli/blob/main/docs/v2/manual.md)
- [x] Did you perform a search about this problem? Here's the [GitHub guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## Dependency Management

- My project is using go modules.
- My project is automatically downloading the latest version.

## Describe the bug

When a `StringFlag` has `Required=true` set, setting an empty String is still possible by explicitly setting to empty string (see observed section below).

I don't see a use case where a `Required` string flag would allow setting an empty string.
I mean, I want that the user provides a value in the first place, why should empty strings be allowed?
If an empty string is allowed, then it shouldn't be `Required` in the first place, therefore I consider this a bug.

## To reproduce

MWE:

```go
package main

import (
	"fmt"
	"os"

	"github.com/urfave/cli/v2"
)

func main() {
	app := cli.App{
		Flags: []cli.Flag{
			&cli.StringFlag{
				Name:     "flag",
				EnvVars:  []string{"FLAG"},
				Required: true,
			},
		},
		Action: func(context *cli.Context) error {
			flag := context.String("flag")
			fmt.Fprintf(os.Stdout, "Flag value is %q\n", flag)
			return nil
		},
	}
	err := app.Run(os.Args)
	if err != nil {
		fmt.Println(err)
	}
}
```

## Observed behavior

```console
$ FLAG= go run .
Flag value is ""

# or
$ go run . --flag=
Flag value is ""

# if set, as expected
$ go run . --flag=example
Flag value is "example"

# if unset
$ go run .
...
   --flag value   [$FLAG]
   --help, -h    show help (default: false)
Required flag "flag" not set
```

## Expected behavior

I would expect that the StringFlag with `Required=true` would check if a value is actually given:
```console
$ FLAG= go run .
Required flag "flag" not set
```

## Additional context

To workaround the check that the value is non-empty, I have to add a flag action like this:

```go
		Action: func(ctx *cli.Context, s string) error {
			if s == "" {
				return fmt.Errorf(`Required flag "flag" not set`)
			}
			return nil
		},
```

However, IMO this should be covered by the `Required=true` setting in the cli package already when parsing the flags.

## Want to fix this yourself?

I might be able to provide a fix, if the maintainers agree that this behavior is indeed a bug, and not "by design" or considered a breaking change.

## Run `go version` and paste its output here

```
go version go1.19.4 linux/amd64
```

## Run `go env` and paste its output here

I don't see how it's relevant here.

**Comment by dearchap** [comment]
@ccremer this is by design. The fact that the env is set is itself a signal that the user has set it . What it's contents are depend on the client application interpretation of the empty string. The cli cannot make a judgement call on behalf of the user.

**Comment by ccremer** [comment]
@dearchap I see. IMO that's still counter-intuitive because whether the flag is set or not doesn't ultimately matter, what matters is that "a value is required". 

In any case. Would it make sense to add a config option that says something like `RequireNonEmpty` that, together with `Required=true` returns an error if set to empty string?

**Comment by dearchap** [comment]
Yes having something like that would be preferred

**Comment by dearchap** [comment]
Also in v3 we plan to have flag/arg validation so this would be trivial to implement there

**Comment by ccremer** [comment]
Thanks.
Unfortunately I currently lack the time to contribute. Closing this as we have a workaround available which is good enough for now (or wait for v3).
Feel free to reopen if relevant again.
