### ISSUE TITLE
unknown field Action in struct literal

### ISSUE THREAD

**Issue by zofi-crash** [urfave/cli#1639]
## My urfave/cli version is

_**( v2 )**_

## Checklist

- [x] Are you running the latest v2 release? The list of releases is [here](https://github.com/urfave/cli/releases).
- [x] Did you check the manual for your release? The v2 manual is [here](https://github.com/urfave/cli/blob/main/docs/v2/manual.md)
- [x] Did you perform a search about this problem? Here's the [GitHub guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## Describe the bug

using v2 and using &cli.IntSliceFlag: There is no Field "Action" as https://cli.urfave.org/v2/examples/flags/#flag-actions says

**Comment by dearchap** [comment]
@schizoquant Which version of v2 are you using ? This capability was added in recent versions.

**Comment by schizoquant** [comment]
> @schizoquant Which version of v2 are you using ? This capability was added in recent versions.

i just did what the docs said, added "github.com/urfave/cli/v2" to my import and did go mod tidy to install it

**Comment by dearchap** [comment]
Can you post the contents of your go.mod ?

**Comment by dearchap** [comment]
@zofi-crash here is a sample of how the Action should be defined https://github.com/urfave/cli/blob/v2-maint/app_test.go#L2815
