### ISSUE TITLE
A Persistent flag's action is not ran.

### ISSUE THREAD

**Issue by skelouse** [urfave/cli#1644]
## Checklist

* [❌ ] Are you running the latest v3 release? Running the main branch
* [✔️] Did you check the manual for your release?
* [✔️] Did you perform a search about this feature?

## What problem does this solve?

When setting a global flag to persist and running a command within, the action of the flag is not ran.

```go
package cli_test

import (
	"testing"

	"github.com/urfave/cli/v3"
)

func TestFlagActionFail(t *testing.T) {

	var flagActionRan bool
	testFlag := &cli.BoolFlag{
		Name:       "env",
		Persistent: true,
		Action: func(ctx *cli.Context, b bool) error {
			flagActionRan = true
			return nil
		},
	}

	app := &cli.App{
		Flags: []cli.Flag{testFlag},
		Commands: []*cli.Command{
			{
				Name: "run",
				Action: func(ctx *cli.Context) error {
					return nil
				},
			},
		},
	}

	err := app.Run([]string{"prog", "run", "--env"})
	if err != nil {
		t.Error(err)
		return
	}

	if !flagActionRan {
		t.Error("Flag action did not run")
	}
}

```

## Solution description

In `command.go` we are calling the following, but c.Flags does not include persistent flags.
```go
if err = runFlagActions(cCtx, c.Flags); err != nil {
	return err
}
```

**Comment by dearchap** [comment]
Interesting. Thanks @skelouse . Any ideas on when this persistent flag action should be run ?

**Comment by skelouse** [comment]
> Interesting. Thanks @skelouse . Any ideas on when this persistent flag action should be run ?

The main question I have is should persistent flags run their action multiple times.
Ex: Let's consider these arguments

`prog run --env program --env`

Should the action run twice, or should the action only run once as in `prog run program --env --env`

If it should only run once we would have to clarify this on FlagBase with a `hasBeenActioned` parameter along with `persistent == true`.

If it should run for each command where defined then the following could be sufficient. 

Note: just a working concept, and quite heavy in practice.

```go
func runFlagActions(c *Context, fs []Flag) error {
	flagsSet := []string{}
	c.flagSet.Visit(func(f *flag.Flag) {
		flagsSet = append(flagsSet, f.Name)
	})

	flagsSearched := []string{}
	for _, f := range fs {
		isSet := false
		for _, name := range f.Names() {
			flagsSearched = append(flagsSearched, name)
			if c.IsSet(name) {
				isSet = true
				break
			}
		}

		if isSet {
			if af, ok := f.(ActionableFlag); ok {
				if err := af.RunAction(c); err != nil {
					return err
				}
			}
		}
	}

	if len(flagsSearched) == 0 {
		return nil
	}

	flagsNotChecked := []string{}
	for _, name := range flagsSet {
		if !slices.Contains(flagsSearched, name) {
			flagsNotChecked = append(flagsNotChecked, name)
		}
	}

	for _, flagName := range flagsNotChecked {
		flag := c.lookupFlag(flagName)
		if af, ok := flag.(ActionableFlag); ok {
			if err := af.RunAction(c); err != nil {
				return err
			}
		}
	}

	return nil
}
```
