### ISSUE TITLE
Test bash completion for sub-commands of sub-commands

### ISSUE THREAD

**Issue by schollii** [urfave/cli#1668]
## My urfave/cli version is

_**2.24.1**_

## Checklist

- [X ] Are you running the latest v2 release? The list of releases is [here](https://github.com/urfave/cli/releases).
- [ X] Did you check the manual for your release? The v2 manual is [here](https://github.com/urfave/cli/blob/main/docs/v2/manual.md)
- [ X] Did you perform a search about this problem? Here's the [GitHub guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## Dependency Management

- My project is using go modules.

## Describe the bug

There is no unit test that would have trapped #1617 

## To reproduce

Check the PR #1618 

## Observed behavior

None of the test files were modified

## Expected behavior

There should be at least one test file that has additional tests to trap the incorrect behavior that was seen in #1617

**Comment by dearchap** [comment]
@schollii would you like to submit a PR for this ?

**Comment by schollii** [comment]
I will try to find some time next couple weeks
