### ISSUE TITLE
Shell mode

### ISSUE THREAD

**Issue by flowchartsman** [urfave/cli#1681]
## Checklist

* [x] Are you running the latest v3 release? The list of releases is [here](https://github.com/urfave/cli/releases).
* [ ] Did you check the manual for your release? **No, manual link is broken.**
* [X] Did you perform a search about this feature? Here's the [GitHub guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## What problem does this solve?

Since the library already supports auto-completion, it's probably not too far of a reach to hook into a library like [go-prompt](https://github.com/c-bata/go-prompt) to provide an optional interactive shell mode.

This would increase the utility of the tool.

## Solution description

API could look something like:
```go
	app := &cli.App{
		SupportShell: true,
		Commands: []*cli.Command{
			{
				Name:  "template",
				Usage: "template commands",
				CanSet: true,
				Subcommands: []*cli.Command{
					{
						Name:     "add",
						Usage:    "add a template",
					},
					{
						Name:     "remove",
						Usage:    "remove a template",
						Unset: true,
					},
				},
			},
		},
	}
```

Then

```
$ myapp shell
myapp> help
COMMANDS:
   template  template commands
   help, h   Shows a list of commands or help for one command

myapp> template
  template - template commands
USAGE:
  template command [command options] [arguments...]
  set template [arguments...] # then issue template commands
COMMANDS:
   add
   remove
   help, h  Shows a list of commands or help for one command

myapp> template add
NAME:
   template add - add a template
USAGE:
   template add [command options] [arguments...]
OPTIONS:
   --someflag

myapp> set template foo
myapp/template [foo]> add --help
NAME:
   template add - add a template
USAGE:
   add [command options]
OPTIONS:
   --someflag

myapp/template [foo]> add --someflag
sucessfully added template "foo"
myapp/template [foo]> remove
successfully removed template "foo"
myapp> 
```

## Describe alternatives you've considered

Could also write a library, but I'm not sure if `App` is re-entrant in that way. If there's a way to call a subcommand with arbitrary arguments once `App.Run` has been called, it becomes a lot easier to keep them separate.

**Comment by dearchap** [comment]
@flowchartsman The idea is interesting but App is not re-entrant currently. Im guessing this will take a lot of work. Do you want to submit a PR ? I can happily review.
