### ISSUE TITLE
Zshell autocompletion error

### ISSUE THREAD

**Issue by Matt-Cam** [urfave/cli#1687]
## My urfave/cli version is

_**v2.23.7**_

## Checklist

- [x] Are you running the latest v2 release? The list of releases is [here](https://github.com/urfave/cli/releases).
- [x] Did you check the manual for your release? The v2 manual is [here](https://github.com/urfave/cli/blob/main/docs/v2/manual.md)
- [x] Did you perform a search about this problem? Here's the [GitHub guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## Dependency Management

- My project is using go modules.
- My project is using vendoring.

## Describe the bug

Autocompletion of commands is not working and is throwing an error `flag provided but not defined: -generate-shell-completion`. 

## To reproduce

* create a new go project "myProject"
* create a main.go file in the project as outlined below
* set env variable PROG=myProject
* in a zshell, source a file like the one outlined [here](https://github.com/urfave/cli/blob/main/autocomplete/zsh_autocomplete)
* in a zshell, navigate to /path/to/myProject
* run `go build`
* run `./myProject he[TAB]`
```
package main

import (
	"fmt"
	"log"
	"os"

	"github.com/urfave/cli/v2"
)

func main() {
	app := &cli.App{
		EnableBashCompletion: true,
		Commands: []*cli.Command{
			{
				Name:  "hello",
				Usage: "print hello",
				Action: func(cCtx *cli.Context) error {
					fmt.Println("hello: ", cCtx.Args().First())
					return nil
				},
			},
		},
	}
	if err := app.Run(os.Args); err != nil {
		log.Fatal(err)
	}
}
```

## Observed behavior

```
flag provided but not defined: -generate-shell-completion
2023/02/24 15:53:25 flag provided but not defined: -generate-shell-completion
2023/02/24 15:53:25 flag provided but not defined: -generate-shell-completion

```

## Expected behavior

Autocompletion to the `hello` command.

## Additional context

If the issue relates to a specific open source GitHub repo, please
link that repo here.

If you can reproduce this issue with a public CI system, please
link a failing build here.

## Want to fix this yourself?

We'd love to have more contributors on this project! If the fix for
this bug is easily explained and very small, feel free to create a
pull request for it.

## Run `go version` and paste its output here

```
go version go1.19.5 darwin/arm64
```

## Run `go env` and paste its output here

```
GO111MODULE="on"
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/matt.cameron/Library/Caches/go-build"
GOENV="/Users/matt.cameron/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/matt.cameron/go/pkg/mod"
GONOPROXY="github.com/DataDog"
GONOSUMDB="github.com/DataDog,go.ddbuild.io"
GOOS="darwin"
GOPATH="/Users/matt.cameron/go"
GOPRIVATE=[redacted]
GOPROXY="binaries.ddbuild.io,proxy.golang.org,direct"
GOROOT="/opt/homebrew/Cellar/go/1.19.5/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go/1.19.5/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.19.5"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/matt.cameron/GolandProjects/myProject/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

```

**Comment by dearchap** [comment]
@Matt-Cam You are using v2. The zsh complete for that is here https://github.com/urfave/cli/blob/v2-maint/autocomplete/zsh_autocomplete which is different from what we have for v3. Once you source the v2 file you should be fine.

**Comment by zhengpd** [comment]
@dearchap It would be nice if the README tells `main` branch is for v3. I got the same completion error when following the v2 manual, not knowing the v3 change.

**Comment by bartekpacia** [comment]
I struggled a bit with enabling shell completions for my CLI app built with this great package, but I managed to do it. In case anyone wants to see a working example, see https://github.com/bartekpacia/emu :)
