### ISSUE TITLE
CustomHelpTemplate is ignored with --help flag

### ISSUE THREAD

**Issue by feedmeapples** [urfave/cli#1703]
## My urfave/cli version is

_**2.25.0**_

## Checklist

- [x] Are you running the latest v2 release? The list of releases is [here](https://github.com/urfave/cli/releases).
- [x] Did you check the manual for your release? The v2 manual is [here](https://github.com/urfave/cli/blob/main/docs/v2/manual.md)
- [x] Did you perform a search about this problem? Here's the [GitHub guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## Dependency Management

- My project is using go modules.
- My project is automatically downloading the latest version.

## Describe the bug

While `cli top-level-command help` respects `CustomHelpTemplate` when printing help, `cli top-level-command --help` ignores it and prints `SubcommandHelpTemplate` instead.

Is this intentional? What is the purpose of `SubcommandHelpTemplate`?

If this is not intentional i can send a PR switching to  `CustomHelpTemplate`

## To reproduce

```
app := cli.NewApp()
	app.Name = "testapp"
        app.Commands = []*cli.Command{
		        {
			        Name:   "top-level-command",
			        Action: func(c *cli.Context) error { return nil },
			        CustomHelpTemplate: "TESTING",
			 }
}
```

```
go run ./cmd/app top-level-command --help
```

## Observed behavior

It prints `SubcommandHelpTemplate`

## Expected behavior

`go run ./cmd/app top-level-command --help` should print `CustomHelpTemplate`

## Additional context

https://github.com/temporalio/cli/pull/153

## Want to fix this yourself?

**Yes**

## Run `go version` and paste its output here

go version

**Comment by dearchap** [comment]
@feedmeapples Can you post your whole main.go file here. ? I want to double check some things. The behaviour is really really tricky to get right.

**Comment by jojje** [comment]
Here's a small main.go that reproduces the issue.
```Go
package main

import (
	"log"
	"os"

	"github.com/urfave/cli/v2"
)

func main() {
	app := &cli.App{
		Name: "myapp",
		Commands: []*cli.Command{
			{
				Name:               "subcmd",
				CustomHelpTemplate: "My template",
				// HideHelpCommand:    true,
				Action: func(c *cli.Context) error {
					return nil
				},
			},
		},
	}
	if err := app.Run(os.Args); err != nil {
		log.Fatal(err)
	}
}
```
This code has the right behavior, but if you comment in the `HideHelpCommand` line, the custom template is not used, but the default hard-coded one.

The problem seems to be [here](https://github.com/urfave/cli/blob/c0cc5c2f76ccbee45a0e115d8933462d93d42f36/help.go#L80), where the fall-through results in the hard coded template being used.
