### ISSUE TITLE
global bool flags does not work

### ISSUE THREAD

**Issue by tomasweigenast** [urfave/cli#1717]
## My urfave/cli version is 

_**github.com/urfave/cli/v2 v2.25.1**_

## Checklist

- [X] Are you running the latest v2 release? The list of releases is [here](https://github.com/urfave/cli/releases).
- [X] Did you check the manual for your release? The v2 manual is [here](https://github.com/urfave/cli/blob/main/docs/v2/manual.md)
- [X] Did you perform a search about this problem? Here's the [GitHub guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## The bug   

When I set a global bool flag, like the following:
```go
app = &cli.App{
		CustomAppHelpTemplate: helpText,
		CommandNotFound:       cli.ShowCommandCompletions,
		Flags: []cli.Flag{
			&cli.BoolFlag{
				Name:        "verbose",
				Required:    false,
				Hidden:      false,
				Destination: &verboseLogging,
				Usage:       "Print all logs to the console",
			},
		},
	}
```

When I run another command, like `plugin info`, it says: `Incorrect Usage: flag provided but not defined: -verbose` and at the end of the help text: `flag provided but not defined: -verbose`

But now, when I mark the flag as required, if I run the same command, the cli says: `Required flag "verbose" not set` lol.
The full command is: `go run . plugin info --verbose`. `plugin` is a command and `info` a subcommand that actually performs some action.

**Comment by dearchap** [comment]
@tomasweigenast This is expected behavior in v2. v3/main has support for this by setting the Persistent field in the flag. 

https://github.com/urfave/cli/blob/main/flag_impl.go#L92

**Comment by tomasweigenast** [comment]
When it will be released?

**Comment by dearchap** [comment]
v3 is in alpha. You can use it right now by importing "github.com/urfave/cli/v3"

**Comment by tomasweigenast** [comment]
> @tomasweigenast This is expected behavior in v2. v3/main has support for this by setting the Persistent field in the flag.
> 
> https://github.com/urfave/cli/blob/main/flag_impl.go#L92

I tried it but it does not work when the flag is specified last. 

`./mytool --the-flag command subcommand` -> It works
`./mytool command subcommand --the-flag` -> It does not work

I tried with the `Persistent` flag and without

**Comment by dearchap** [comment]
Yes you have to give all the flags before args
