### ISSUE TITLE
`BoolFlag.Count` increment once per alias

### ISSUE THREAD

**Issue by matthewhughes934** [urfave/cli#1737]
## My urfave/cli version is

`v2.25.3`

## Checklist

- [x] Are you running the latest v2 release? The list of releases is [here](https://github.com/urfave/cli/releases).
- [x] Did you check the manual for your release? The v2 manual is [here](https://github.com/urfave/cli/blob/main/docs/v2/manual.md)
- [x] Did you perform a search about this problem? Here's the [GitHub guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## Dependency Management

- My project is using go modules.

## Describe the bug

The value of `.Count` for a `BoolFlag` is impacted by the number of aliases defined for that flag.

## To reproduce

Reproducible program:

```go
package main

import (
	"fmt"
	"os"

	"github.com/urfave/cli/v2"
)

func main() {
	verbosity := 0
	
	app := &cli.App{
		Flags: []cli.Flag{
			&cli.BoolFlag{
				Name: "verbose",
				Aliases: []string{"v"},
				Count: &verbosity,
			},
		},
		Action: func(c *cli.Context) error {
			fmt.Printf("Running with verbosity: %d\n", verbosity)
			return nil
		},
	}

	app.Run(os.Args)
}
```

## Observed behavior

```console
$ go run main.go -v
Running with verbosity: 2
```

## Expected behavior

I would expect the count to be incremented only once, i.e.:

```console
$ go run main.go -v
Running with verbosity: 1
```

## Additional context

Beyond the initial value, things are incremented as expected:

```console
$ go run main.go -v -v
Running with verbosity: 3
```

## Want to fix this yourself?

I'd be happy to, though I don't think I have enough context to implement a suitable solution. The trace is:

* When we `.Apply` a `BoolFlag` we copy the `count` pointer for each alias https://github.com/urfave/cli/blob/dc77f3cf1beb4cec4ee7867bc8d4d3bad992ec3d/flag_bool.go#L138
* And when we `.Set` the flag we increment this count https://github.com/urfave/cli/blob/dc77f3cf1beb4cec4ee7867bc8d4d3bad992ec3d/flag_bool.go#L38

So when we run a command:

* We parse the flags https://github.com/urfave/cli/blob/acbbbf214672e2fc067ec6e5deee2e4a0ed83e83/command.go#L158
* Which requires normalizing https://github.com/urfave/cli/blob/acbbbf214672e2fc067ec6e5deee2e4a0ed83e83/command.go#L384
* When normalizing we copy for each alias we didn't see https://github.com/urfave/cli/blob/acbbbf214672e2fc067ec6e5deee2e4a0ed83e83/flag.go#L229
* Which in turn sets the value https://github.com/urfave/cli/blob/acbbbf214672e2fc067ec6e5deee2e4a0ed83e83/flag.go#L199

Consequently the flag is `.Set` once per alias, so the count is incremented once per alias.

Maybe flag types could implement the copying logic themselves?

## Run `go version` and paste its output here

```
$ go version
go version go1.20.4 linux/amd64
```

## Run `go env` and paste its output here

```
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/user/.cache/go-build"
GOENV="/home/user/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/user/.local/share/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/user/.local/share/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20.4"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/user/src/cli/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3085526498=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by dearchap** [comment]
@matthewhughes934 Try this "fix"
