### ISSUE TITLE
Timestamp flags don't work with environment variables

### ISSUE THREAD

**Issue by victorkt** [urfave/cli#1755]
## My urfave/cli version is

v2.25.6

## Checklist

- [x] Are you running the latest v2 release? The list of releases is [here](https://github.com/urfave/cli/releases).
- [x] Did you check the manual for your release? The v2 manual is [here](https://github.com/urfave/cli/blob/main/docs/v2/manual.md)
- [x] Did you perform a search about this problem? Here's the [GitHub guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## Dependency Management

- My project is using go modules.
- My project is using vendoring.

## Describe the bug

Timestamp flags don't seem to work with environment variables. When passing the value as an env var, the value is unchanged. This doesn't happen when passing values as arguments.

## To reproduce

I've tested it with the following code:

```go
package main

import (
	"fmt"
	"log"
	"os"
	"time"

	"github.com/urfave/cli/v2"
)

var someTimestampFlag cli.Timestamp

func main() {
	app := cli.NewApp()
	app.Flags = []cli.Flag{
		&cli.TimestampFlag{
			Name:        "some-timestamp-flag",
			EnvVars:     []string{"SOME_TIMESTAMP_FLAG"},
			Layout:      time.RFC3339,
			Destination: &someTimestampFlag,
			Required:    true,
		},
	}
	app.Action = func(c *cli.Context) error {
		fmt.Println("env var:", os.Getenv("SOME_TIMESTAMP_FLAG"))
		fmt.Println("flag:", someTimestampFlag.Value())
		return nil
	}
	if err := app.Run(os.Args); err != nil {
		log.Fatal(err)
	}
}

```

## Observed behavior

```sh
$ SOME_TIMESTAMP_FLAG=2021-03-02T06:20:00Z go run main.go
env var: 2021-03-02T06:20:00Z
flag: <nil>

$ go run main.go --some-timestamp-flag=2021-03-02T06:20:00Z
env var: 
flag: 2021-03-02 06:20:00 +0000 UTC

```

## Expected behavior

I'd expect the flag contained the provided date in both runs.

## Run `go version` and paste its output here

```
$ go version
go version go1.20.5 darwin/arm64
```

**Comment by dearchap** [comment]
@victorkt Thank you for raising this issue. Can you see if the PR fixes your issue ?

**Comment by victorkt** [comment]
@dearchap thanks for the quick response. yes, that seems to fix the problem.
