### ISSUE TITLE
Subcommand help is not showing

### ISSUE THREAD

**Issue by khash** [urfave/cli#176]
I seem to never be able to get help to print the subcommand help. Looking at the code, I would expect `SubcommandHelpTemplate` to be used for this, but it is not used anywhere in the code. If `stacks` is a command with sub commands, it will print the list of subcommands with a command like this: `cli stacks help` which uses `AppHelpTemplate`.

In this case however:
- Email and Author revert back to unknown and 0.0.0.0 (as if the command is app)
- There is no way to get the help for a subcommand.

**Comment by khash** [comment]
I found out that I can get the subcommand help by doing something like `cli stacks help subcommand` but find this unintuitive. Should not the help be shown by typing the following?
```
cli help stacks
cli help stacks subcommand
```

**Comment by telyn** [comment]
I also feel it's unintuitive that the output for `cli help stacks subcommand` is not the same as `cli stacks help subcommand`. Also, assuming `stacks` has subcommands, `cli help stacks` doesn't mention the fact, but `cli stacks help` does.

I spent an hour trying to fix this just now but ran into dependency initialisation loops. I'll have another crack at it at a later date probably.

**Comment by jszwedko** [comment]
I agree, the same output should be shown for `cli help stacks subcommand` as `cli stacks help subcommand`. Thanks for bringing this up!

**Comment by jszwedko** [comment]
(Note you can also see it via `cli stacks subcommand -h`)

**Comment by telyn** [comment]
I ended up working around this by doing my own global flag parsing, then scanning through looking for any argument called "help". If help, --help or -h were found, then it sticks --help on the end.

I'm no closer to actually fixing the problem though.

**Comment by lynncyrin** [comment]
In case anyone is interested in fixing this issue, I would love to review a PR for ya! ✨

**Comment by lynncyrin** [comment]
Manually closing this as stale! We can re-open if there's interest in the future.
