### ISSUE TITLE
Docs are not updated

### ISSUE THREAD

**Issue by abitrolly** [urfave/cli#1798]
The current version of the page https://cli.urfave.org/v2/getting-started/ reads "Let's give an action".

But https://github.com/urfave/cli/edit/main/docs/v2/getting-started.md says "Let's add an action".

CI shows that Pages upload job is runs successfully https://github.com/urfave/cli/actions/workflows/pages/pages-build-deployment

Why the contents of the web-site is not updated?

**Comment by dolmen** [comment]
Worse: the latest version is now `v3` but https://cli.urfave.org/ still talks only about v2 and v1.

**Comment by dearchap** [comment]
v3 docs are present but havent been pushed to remote server. https://github.com/urfave/cli/tree/main/docs/v3

**Comment by bartekpacia** [comment]
I think this was fixed by @dearchap recently, right?

**Comment by abitrolly** [comment]
Yep. Content is updated. Closing..
