### ISSUE TITLE
--help takes arguments even for the root command

### ISSUE THREAD

**Issue by ianlewis** [urfave/cli#1809]
When running a command like `mycmd --help foo` this should trigger help to be printed and ignore other command line arguments but in this case `cli` will treat `foo` as an argument to `--help` and try to print help for the `foo` command. This results in an error message like

```
$ mycmd --help foo
mycmd: No help topic for 'foo'
```

**Comment by dearchap** [comment]
@ianlewis This is expected behaviour. if someone wants help on a subcmd they can do 
```
$ mycmd --help subcmd
```
to get the help for subcmd. The workaround for you would be to set a custom App.CommandNotFound func and call ShowSubcommandHelp in that func
