### ISSUE TITLE
bug report: `cli.CommandsByName` not exist in v3-alpha4

### ISSUE THREAD

**Issue by Passer6y** [urfave/cli#1816]
## Checklist

* [x] Are you running the latest v3 release? The list of releases is [here](https://github.com/urfave/cli/releases).
* [x] Did you check the manual for your release? The v3 manual is [here] (https://github.com/urfave/cli/blob/main/docs/v3/manual.md). Could not find the manual, link points to 404
* [x] Did you perform a search about this feature? Here's the [GitHub guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## What problem does this solve?
I want to following code to sort cli command, it works in v2, but not exist in v3-alpha4
```
sort.Sort(cli.CommandsByName(cli.Commands))
```

**Comment by dearchap** [comment]
@Passer6y You can do 

```
rootCommand := Command{...}
sort.Sort(rootCommand.Commands)
```

**Comment by almas1992** [comment]
<img width="818" alt="Image" src="https://github.com/user-attachments/assets/f8014f27-5e1c-4a46-af88-0789ac954c7c" />

**Comment by dearchap** [comment]
@almas1992 you can do something like this

```
 slices.SortFunc(commands, func (a, b *Command) int {
    return a.Name < b.Name
  })
```
