### ISSUE TITLE
Compatibility for cli.Context and context.Context

### ISSUE THREAD

**Issue by ptth404** [urfave/cli#1823]
While `cli.Context` embeds `context.Context` sea time it overrides `Context.Value` notation so that thee standard `Context` interface isn't implemented

With that calling
```
var ctx context.Context = // WithValue WithCancel etc
command.Run(context.WithValue(), os.Args)
```
how is it supposed to access a standard Context interface in any downstream action calls which  are injected with `*cli.Context` one.
E.g
```
...
Action(ctx *cli.Context) error {
  var  stdCtx context.Context = ... // resolve from ctx
  net.DialContext(stdCtx, ...)
}
```

**Comment by dearchap** [comment]
@ptth404 You should be able to do 

```...
Action(ctx *cli.Context) error {
  var  stdCtx context.Context = ctx.Context
  net.DialContext(stdCtx, ...)
}
```

**Comment by ptth404** [comment]
Ah I see. Thank you @dearchap
