### ISSUE TITLE
Generate markdown from help

### ISSUE THREAD

**Issue by bricekams** [urfave/cli#1852]
## Checklist

* [X ] Are you running the latest v3 release? The list of releases is [here](https://github.com/urfave/cli/releases).
* [ X] Did you check the manual for your release? The v3 manual is [here](https://github.com/urfave/cli/blob/main/docs/v3/manual.md).
* [ X] Did you perform a search about this feature? Here's the [GitHub guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## What problem does this solve?
Easy generate documentation for command line app

**Comment by dearchap** [comment]
@bricekams This has been removed in v3 to decrease the size of cli executable. We are still exploring options as to how to do this.

**Comment by bricekams** [comment]
It has been removed in v3, meaning that it's available in v2? can I have a link?

**Comment by dearchap** [comment]
Look at docs.go App.ToMarkdown
