### ISSUE TITLE
FullName not working as it did in 2.19.3, seems to have broken in 2.20.0

### ISSUE THREAD

**Issue by devnut** [urfave/cli#1859]
## My urfave/cli version is

2.19.3

## Checklist

- [yes] Are you running the latest v2 release? The list of releases is [here](https://github.com/urfave/cli/releases).
- [yes] Did you check the manual for your release? The v2 manual is [here](https://github.com/urfave/cli/blob/main/docs/v2/manual.md)
- [yes] Did you perform a search about this problem? Here's the [GitHub guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## Dependency Management

- My project is using go modules.
- My project is using vendoring.
- My project is automatically downloading the latest version.

## Describe the bug

In urfave 2.19.3 when calling FullName() it is constructed from c.commandNamePath.

In 2.19.3 there is code in startApp() that does not seem to be in 2.20.0-2.21.1

## To reproduce

c.Command.FullName() (where c is *cli.Context of a subcommand)

## Observed behavior

Only the "subcommand" name is printed

## Expected behavior

FullName() would emit "command subcommand"

## Want to fix this yourself?

We'd love to have more contributors on this project! If the fix for
this bug is easily explained and very small, feel free to create a
pull request for it.

## Run `go version` and paste its output here

```
go version go1.21.3 darwin/arm64
```

## Run `go env` and paste its output here

```
GO111MODULE='auto'
GOARCH='arm64'
GOBIN='/Users/gsaylor/repos/bitbucket/everything_app/rapid_risk_assessment/bin'
GOCACHE='/Users/gsaylor/Library/Caches/go-build'
GOENV='/Users/gsaylor/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/gsaylor/go/pkg/mod'
GONOPROXY='hq-stash.corp.proofpoint.com'
GONOSUMDB='hq-stash.corp.proofpoint.com'
GOOS='darwin'
GOPATH='/Users/gsaylor/go'
GOPRIVATE='hq-stash.corp.proofpoint.com'
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='go1.21.3'
GCCGO='gccgo'
AR='ar'
CC='clang'
CXX='clang++'
CGO_ENABLED='1'
GOMOD='/Users/gsaylor/repos/bitbucket/everything_app/rapid_risk_assessment/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/73/p9_stkcx307dnz9y_qg4ydlr0000gp/T/go-build2092070924=/tmp/go-build -gno-record-gcc-switches -fno-common'
```

**Comment by dearchap** [comment]
@devnut Whats the actual issue you are facing ?

**Comment by devnut** [comment]
Fullname() is returning "subcommand", not "command subcommand".

- Greg

**Comment by dearchap** [comment]
@devnut Yes the FullName was actually buggy as you can see from your example. It wasnt consistent so FullName returns the name of the command and HelpName the display name in help.
