### ISSUE TITLE
Add completion for flags

### ISSUE THREAD

**Issue by VarunUmesh** [urfave/cli#188]
I am trying to work on the auto-completion part using this framework, and it does not work with the flags option. Here is my piece of code:

package main

import (
    "fmt"
    "os"

```
"github.com/codegangsta/cli"
```

)

func main() {
    app := cli.NewApp()
    app.Name = "greet"
    app.Usage = "sample command-line app by greet"
    app.Author = "abc"
    app.Email = "xyz@aaa.com"
    app.EnableBashCompletion = true
    app.Commands = []cli.Command{
        {
            Name:      "read",
            ShortName: "r",
            Usage:     "read something",
            Subcommands: []cli.Command{
                {
                    Name:   "articles",
                    Usage:  "read articles",
                    Action: readArticles,
                },

```
            {
                    Name:   "tweets",
                    Usage:  "read Tweets",
                    Flags: []cli.Flag{
                            cli.StringFlag{
```

Name: "account",
                                        Value: "SomeThing",
                                        Usage: "name of Twitter account",
                                },
                        },
                        Action: readTwitter,
                },
            },
        },
    }
    app.Run(os.Args)
}

func readArticles(ctx *cli.Context) {
    fmt.Println("Go to http://www.google.com to read articles!")
}

func readTwitter(ctx *cli.Context) {
        fmt.Printf("Go to https://twitter.com/%s to read tweets!", ctx.String("account"))
}

When i try to do an autocomplete on the flags, it does not work. Could anybody let me know if this is supported by the framework?

Example:

./greet read tweets --a [TAB][TAB] does not work.

**Comment by Matt3o12** [comment]
First, please format your code properly (add 4 spaces before pasting it into an issue or use sites like [pastebin.org](pastebin.org) for posting big chunks of code). 

Have you check if bash completion works? You can do that by calling `gowork-wrapper --generate-bash-completion`. If it returns all available commands, you're code is correct, you just haven't sourced the file, yet.  
You can source the file like this: `PROG=YOU_PROGRAM_NAME source "$GOPATH/src/github.com/codegangsta/cli/autocomplete/bash_autocomplete"`.

**Comment by jszwedko** [comment]
@VarunUmesh correct, the autocompletion only works for subcommands, not flags, as noted here: https://github.com/codegangsta/cli#bash-completion

**Comment by Matt3o12** [comment]
i think the author means that it should also work for flags since there is no reason for it not to work (at least non I can think of)
If you're concerned about backwards compatibility, you could add the "EnableAutocompleteFlags" field. You could also set it to true by default because it can't think of a case where completing flags could be harmful (even git completes flags).

**Comment by jszwedko** [comment]
Fair enough, I'll re-open as an enhancement.

**Comment by ngtuna** [comment]
Any update on this issue? Is there anyway to add completion for flags at this moment ?

**Comment by jszwedko** [comment]
I haven't had a chance to take a stab at this yet, put PRs are welcome!

**Comment by yogeshlonkar** [comment]
Can someone review and merge the changes in #808 ?
