### ISSUE TITLE
Delete stale branches

### ISSUE THREAD

**Issue by bartekpacia** [urfave/cli#1894]
@urfave/cli

Hey!

I noticed there are quite a few stale branches (see https://github.com/urfave/cli/branches/stale). Can they be removed?

**Comment by meatballhat** [comment]
(Mostly) done! Thank you for calling this out @bartekpacia 🤘🏼 ❤️

**Comment by bartekpacia** [comment]
Thanks! :)

BTW, why are names for v1 and v2 branches end with `t`? `v1-maint`, `v2-maint`, etc? I guess it's for `trunk` but I'd like confirmation.

**Comment by abitrolly** [comment]
@bartekpacia **t** stands for main**t**enance. `main` is already `trunk`.

**Comment by bartekpacia** [comment]
@abitrolly thank you:)


@dearchap there's also a branch of yours called `v2-maint-nogen`. Do you plan to land it into v2?

**Comment by abitrolly** [comment]
@bartekpacia `v2-maint-nogen` is from https://github.com/urfave/cli/pull/1802
