### ISSUE TITLE
Allow omission of default text in help text

### ISSUE THREAD

**Issue by drewfead** [urfave/cli#1925]
## Checklist

* [x] Are you running the latest v3 release? The list of releases is [here](https://github.com/urfave/cli/releases).
* [x] Did you check the manual for your release? The v3 manual is [here](https://github.com/urfave/cli/blob/main/docs/v3/manual.md). -- This link is a 404
* [x] Did you perform a search about this feature? Here's the [GitHub guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## What problem does this solve?

In 3.0.0-alpha9, default text is always printed, irrespective of whether the field is required, etc.

This means that required numeric flags have help text that prints a default value of 0, for example.  The current API supports bringing your own DefaultText, but if you set it to "", it doesn't get applied. See relevant code [here](https://github.com/urfave/cli/blob/main/flag.go#L348-L354) and [here](https://github.com/urfave/cli/blob/1210bdf785b2bddda680a262acc84d5e7b583460/flag_impl.go#L245-L251).

Arguably this is a bug for implicit zero-valued default values. Certainly this is a bug for required flags with an implicit zero-valued default. Regardless of its status as a bug or expected behavior, it would be nice to be able to opt out of showing default text altogether on a flag-by-flag basis.

## Solution description

I'd like for an `OmitDefaultText` boolean field to be added to flag base, or a similarly turn-key solution.

## Describe alternatives you've considered

I think you could also make the `DefaultText` field a `*string`, and use the empty string to indicate that default text shouldn't be printed, and I think that would also be fine. I could also imagine at the flag level being able to specify the help template for that flag only, which would be slightly more cumbersome.

**Comment by dearchap** [comment]
@drewfead Yes this starts to get very very complicated. You have defaults, zeros, required, optional and empty strings and it is getting harder and harder to distinguish all of them. Would you like to submit a PR for me to review ?

**Comment by Skeeve** [comment]
My proposal is: We already have "Hidden: true/false" in FlagBase.

Why not add "HideDefault: true/false"?

Also set HideDefault for the standard help command tu true as this makes no sense at all:

```text
GLOBAL OPTIONS:
   --help, -h     show help (default: false)
```
