### ISSUE TITLE
What is the purpose of `normalizeFlags`?

### ISSUE THREAD

**Issue by fiatjaf** [urfave/cli#1929]
I read the code but my understanding of it doesn't match what happens when I remove that function entirely.

It looks like the only things it does in practice is to disallow using the long form and the short form alias of the same flag in a same call.

Is there a reason why that should be disallowed? Or is that a necessity due to some constraint I am not seeing?

**Comment by dearchap** [comment]
@fiatjaf Thats one of the reasons. The other reason is that the flag aliases values are duplicated into the set for retrieval but set.Value function.

**Comment by dearchap** [comment]
@fiatjaf looking at it further it appears that the function is redudant. It is a holdover from an early v2 codebase. I have removed in v3.

**Comment by fiatjaf** [comment]
Thank you, this is good news!
