### ISSUE TITLE
Bug in v3: Count is off by 1

### ISSUE THREAD

**Issue by Skeeve** [urfave/cli#1930]
## Checklist

* [ x] Are you running the latest v3 release? The list of releases is [here](https://github.com/urfave/cli/releases).
* [ x] Did you check the manual for your release? The v3 manual is [here](https://github.com/urfave/cli/blob/main/docs/v3/manual.md).
* [ x] Did you perform a search about this feature? Here's the [GitHub guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## What problem did you observe?

When using cmd.Count("verbose") on my bool flag, it's value is always one too high

## Test Program

```go
package main

import (
	"context"
	"fmt"
	"os"

	"github.com/urfave/cli/v3"
)

func main() {
	cmd := &cli.Command{
		Name:                   "test",
		Usage:                  "Tool for testing",
		HideHelp:               true,
		UseShortOptionHandling: true,
		Flags: []cli.Flag{
			&cli.BoolFlag{
				Name:    "verbose",
				Aliases: []string{"v"},
				Usage:   "Be verbose",
			},
		},
		Action: tester,
	}

	if err := cmd.Run(context.Background(), []string{"prog", "-v"}); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}


func tester(_ context.Context, cmd *cli.Command) (err error) {
	fmt.Printf(`verbosecount: %d`, cmd.Count("verbose"))
	return
}
```

Also on playground: https://play.golang.com/p/om6L1TD_6s5

**Comment by dearchap** [comment]
@Skeeve This looks very much like #1737 which was fixed in v2 but not ported to v3. Think you can make a PR ?

**Comment by Skeeve** [comment]
> Think you can make a PR ?

I doubt it :(

**Comment by dearchap** [comment]
No one has requested count for non-bool flags.

**Comment by Skeeve** [comment]
> No one has requested count for non-bool flags. Not sure when I can get around to a fix though.

That "fix" (if it is a fix) should be easy. Just get rid of "if Countable" in the [Count function](https://github.com/urfave/cli/blob/c4cd0a51cc113a90eca318cc8f7d328f05a5f2b7/flag_impl.go#L44).

**Comment by Skeeve** [comment]
I would like to, but I can't. I have the slight feeling there is more wrong to it, than I first thought.

Here are my observations.

1. Count() returns the flag's `count`member
2. Flag has base`BoolConfig` which has  a member `Count`
3. This `Count` is never incremented nor returned. At least I was unable to find it and I assume this should have been done.

I created a test command for counting bools.

I also thought about counting all flags. I think it only makes sense for the `…SliceFlag`s as all the others usually are not used more than once.
