### ISSUE TITLE
Allow flags to come after arguments

### ISSUE THREAD

**Issue by fiatjaf** [urfave/cli#1950]
## Checklist

* [x] Are you running the latest v3 release? The list of releases is [here](https://github.com/urfave/cli/releases).
* [x] Did you check the manual for your release? The v3 manual is [here](https://github.com/urfave/cli/blob/main/docs/v3/index.md).
* [x] Did you perform a search about this feature? Here's the [GitHub guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## What problem does this solve?

`cli -s file.txt` and `cli file.txt -s` should work the same way because having to strictly type the flags before the arguments is annoying. Most unix utils allow flags after arguments so people are used to that pattern and a thing that is obviously a flag shouldn't be interpreted as an argument just because it comes after another argument.

## Solution description

`cli -s file.txt` and `cli file.txt -s` should work the same way.
`cli -s file.txt` and `cli --foo=bar file.txt -s -v --whatever=something` should work the same way.

## Describe alternatives you've considered

I've tried switching to other CLI frameworks, but they are all much worse than this except in this aspect.

I've tried frontporting a feature from v1 that reordered arguments manually before parsing them: https://github.com/urfave/cli/pull/1928 (currently using this with a custom fork and `replace`).

**Comment by XANi** [comment]
Additional context:

With multi-command binaries it's pretty common pattern to do the "config the command" first:

`cli --server 1.2.3.4 --password-file ~/.cli/production.creds`

and then when using it to just put subcommand after

`cli --server 1.2.3.4 --password-file ~/.cli/production.creds ls --help`

`cli --server 1.2.3.4 --password-file ~/.cli/production.creds show`

`cli --server 1.2.3.4 --password-file ~/.cli/production.creds show --filter asd`

or outright alias it

`alias cli-prod cli --server 1.2.3.4 --password-file ~/.cli/production.creds`

`cli-prod ls --help`

`cli-prod show`

`cli-prod --filter asd`

"POSIX compatbile" is not good. People are not POSIX compatible.

**Comment by BlackHole1** [comment]
In v3(alpha), this is already supported. You can verify it using: `go get github.com/urfave/cli/v3`.

Related PR: #1568 #1835

**Comment by fiatjaf** [comment]
It's not.

**Comment by decentral1se** [comment]
@BlackHole1 https://github.com/urfave/cli/issues/1717#issuecomment-1624383064 https://github.com/urfave/cli/issues/976#issuecomment-2056208381

**Comment by dearchap** [comment]
> Additional context:
> 
> With multi-command binaries it's pretty common pattern to do the "config the command" first:
> 
> `cli --server 1.2.3.4 --password-file ~/.cli/production.creds`
> 
> and then when using it to just put subcommand after
> 
> `cli --server 1.2.3.4 --password-file ~/.cli/production.creds ls --help`
> 
> `cli --server 1.2.3.4 --password-file ~/.cli/production.creds show`
> 
> `cli --server 1.2.3.4 --password-file ~/.cli/production.creds show --filter asd`
> 
> or outright alias it
> 
> `alias cli-prod cli --server 1.2.3.4 --password-file ~/.cli/production.creds`
> 
> `cli-prod ls --help`
> 
> `cli-prod show`
> 
> `cli-prod --filter asd`
> 
> "POSIX compatbile" is not good. People are not POSIX compatible.

@XANi I dont see how your example relates to this issue.

**Comment by fiatjaf** [comment]
This is my feature request, that PR is just one possible but humble attempt at implementing it. I'm sure people with more experience with this code can deal with this better, hence this feature request.

**Comment by dearchap** [comment]
@fiatjaf you may submit the PR and we can merge it but eventually over time it is upto the maintainers to maintain this code and move it forward. So I want to make sure we have a firm foundation since this is not a simple feature.

**Comment by dearchap** [comment]
@decentral1se Thank you for the example. The example supposes that these are bool flags correct ? If you had this

```
cli sub1 sub2 --foo 10 sub3 --bar arg1 --baz --global
```

for example we wouldnt reorder since foo is an int flag ? It starts getting tricky. So say we support only bool flags and we have shortoptionshandling enabled we would need to parse out 

```
cli [--global] sub1 [-f] sub2 [-b] sub3 [-z] arg1
cli sub1 sub2 sub3 arg1 --global -fbz

to 

cli --global sub1 -f sub2 -b sub3 -z arg1
```

I think we need to start working on #1273 which would provide a foundation for this behavior. One of pre-exec functions would allow users to add flags dynamically and another of those pre-exec functions would do reordering.

**Comment by decentral1se** [comment]
@dearchap that's a good point about non-bool flags. Yeh, I guess it's just the same rule: follow what is registered on the flag - does it accept an argument? then bring that with the sort?

Will try manual test along with https://github.com/urfave/cli/pull/1928 great work @fiatjaf

**Comment by dearchap** [comment]
Fixed in #1987

**Comment by fiatjaf** [comment]
Whoa! Thank you very much!

**Comment by decentral1se** [comment]
Holy shit, incredible work @dearchap 🎉🎉🎉
