### ISSUE TITLE
Propagate HideHelpCommand to sub-commands

### ISSUE THREAD

**Issue by decentral1se** [urfave/cli#1951]
## Checklist

* [x] Are you running the latest v3 release? The list of releases is [here](https://github.com/urfave/cli/releases).
* [x] Did you check the manual for your release? The v3 manual is [here](https://github.com/urfave/cli/blob/main/docs/v3/index.md).
* [x] Did you perform a search about this feature? Here's the [GitHub guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## What problem does this solve?

Avoid having to manually set `HideHelpCommand: true` on all sub-commands. E.g.

```
cli sub1 sub2 sub3 --foo
```

You need to set `HideHelpCommand: true` for each `sub1/2/3` `*cli.Command` definitions.

## Solution description

I'm not sure about the API tbh.

If you set it on the root command, it should propagate to all sub-commands? 🤔

An additional boolean seems like overkill.

## Describe alternatives you've considered

Setting it manually for all sub-commands.

**Comment by dearchap** [comment]
@decentral1se can you try out the PR ? I still need to add tests and such.
