### ISSUE TITLE
V3 has no `app.ToMarkdown()`

### ISSUE THREAD

**Issue by 6543** [urfave/cli#1955]
can somebody point me to what i have to migrate to for markdown generation e.g. `app.ToMarkdown()` func is gone in v3

I need it for https://github.com/woodpecker-ci/woodpecker/pull/2951

e.g.:

https://github.com/woodpecker-ci/woodpecker/blob/8831a0e6fd2d07c51e50fb862a293a03d22ccd4b/cmd/cli/docs.go#L24-L39

**Comment by bartekpacia** [comment]
Hey @6543, sorry about your bad experience! Please see #1900 – does it help you with the problem?

**Comment by 6543** [comment]
Yes thats it ... created https://github.com/urfave/cli/issues/1891#issuecomment-2227008368 to track it ;)
