### ISSUE TITLE
Strange `.Validator` behavior

### ISSUE THREAD

**Issue by tarampampam** [urfave/cli#1960]
Hi there! I'm wondering if I'm the only one who finds the behavior of this package a bit strange:

```go
package main

import (
  "context"
  "errors"
  "os"
  "strings"

  "github.com/urfave/cli/v3"
)

func main() {
  if err := (&cli.Command{
    Action: func(ctx context.Context, command *cli.Command) error {
      return nil
    },
    Flags: []cli.Flag{
      &cli.StringFlag{
        Name: "api-key",
        Validator: func(s string) error {
          if !strings.HasPrefix(s, "API-") {
            return errors.New("wrong API key format")
          }

          return nil
        },
      },
    },
  }).Run(context.Background(), os.Args); err != nil {
    println(err.Error())

    os.Exit(1)
  }
}
```

It seems that the default value validation is failing before the actual flag value is parsed. Since the default value will always be invalid, this validation function renders the app unusable, even when the correct flag value is provided:

```shell
❯ go run . -h

Incorrect Usage: wrong API key format

...

wrong API key format
exit status 1
```

```
❯ go run . --api-key API-123 -h

Incorrect Usage: wrong API key format

...

wrong API key format
exit status 1
```

Currently, the only option I have is to set a default value that appears to be "valid-like":

```diff
&cli.StringFlag{
	Name: "api-key",
+	Value: "API-<set-your-key>",
```

Could you please confirm if this is intentional or if it might be a bug?

> [!NOTE]
> ```
> github.com/urfave/cli/v3 v3.0.0-alpha9
> go version go1.22.5 linux/amd64
> ```

**Comment by jetexe** [comment]
It's looks like it the same as #1948

**Comment by dearchap** [comment]
Yes thats the current design. Since the flag is not required it will use the default value and then try to set it. We can look and see whether we can optimize this.

**Comment by tarampampam** [comment]
I would be extremely grateful if you could decide that the flag value should be validated only after parsing, once the default value has been replaced by the one provided by the user, but before allowing the developer to use it. Additionally, when the --help flag is used, no validation should be performed. I believe this is critically important
