### ISSUE TITLE
Passing arg to bool flag breaks other flags

### ISSUE THREAD

**Issue by svartkanin** [urfave/cli#1964]
## My urfave/cli version is

v2.27.4

## Checklist

- [x] Are you running the latest v2 release? The list of releases is [here](https://github.com/urfave/cli/releases).
- [x] Did you check the manual for your release? The v2 manual is [here](https://cli.urfave.org/v2/getting-started/)
- [x] Did you perform a search about this problem? Here's the [GitHub guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## Dependency Management

- My project is using go modules.

## Describe the bug

Using a boolean flag with a argument does not terminate the command. 

## To reproduce

```
package main

import (
	"fmt"
	"log"
	"os"

	"github.com/urfave/cli/v2"
)

func main() {
	app := &cli.App{
		Flags: []cli.Flag{
			&cli.BoolFlag{
				Name: "bool",
			},
			&cli.StringFlag{
				Name: "text",
			},
		},
		Action: func(ctx *cli.Context) error {
			fmt.Println(ctx.String("bool"))
			fmt.Println(ctx.String("text"))
			return nil
		},
	}

	if err := app.Run(os.Args); err != nil {
		log.Fatal(err)
	}
}
```

## Observed behavior

When a argument is passed to a bool flag then subsequent flags are not read correctly anymore 

```
$ go run . --bool --text str
true
str

$ go run . --bool wrong --text str
true

```

## Expected behavior

If a argument is passed to a bool flag then the command should fail as that is an invalid input

## Run `go version` and paste its output here

```
go version go1.22.2 darwin/arm64
```

**Comment by dearchap** [comment]
@svartkanin The whole point of bool flags is to not pass an arg. Why are you passing an arg for the bool flag in the first place ?

**Comment by svartkanin** [comment]
@dearchap I'm aware of that, but if someone accidentally uses the flags this way there will be unintentional behaviour because the parsing is all messed up for the flags coming after as it does not terminate. 
How would we verify that the flags were used as intended?

**Comment by dearchap** [comment]
It's not easy. What happens if 'wrong' is actually defined as a sub command ? We would then try to process it as such thinking that's what the user intended

**Comment by svartkanin** [comment]
If there is no subcommand defined with that name and the Args parameter is set to false for the given command this should result in a failure

**Comment by autowp** [comment]
Also issue with boolFlag in v3.0.0-alpha9: `--flag=false` and `--flag false` is not the same. First parsed to `false`, but second to `true`

**Comment by dearchap** [comment]
Its not really an issue. Its the design for command line flags in general. As per this https://pkg.go.dev/flag this is the standard format 

```
-flag x  // non-boolean flags only
```

without that it becomes ambigious. We cannot intend user's intention here.
