### ISSUE TITLE
Update docs for HideHelpCommands

### ISSUE THREAD

**Issue by midirhee12** [urfave/cli#1965]
## Checklist

* [ ] Are you running the latest v3 release? The list of releases is [here](https://github.com/urfave/cli/releases).
* [ ] Did you check the manual for your release? The v3 manual is [here](https://github.com/urfave/cli/blob/main/docs/v3/index.md).
* [x] Did you perform a search about this feature? Here's the [GitHub guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## What problem does this solve?

Sometimes the user of `cli` would like their app to not have any subcommands. The `help` subcommand is only useful when the app actually has other subcommands. Users of the app may find the usage of the `help` subcommand misleading that other subcommands exist. Even though the `help` subcommand does not list any subcommands, the docs / help message even lead you to believe in the usage section there are subcommands to be used beyond a simple `help` command.

## Solution description

There should be an option of some sort to disable subcommands. When disabled, the `help` subcommand should be removed. Also, the docs and help messages should be adjusted accordingly. This means the "commands" section should be removed entirely. And the usage section will show something along the lines of:
```
USAGE:
   <name> [options]
```
...instead of:
```
USAGE:
   <name> [global options] command [command options]
 ```

Not only should `command` be removed along with its corresponding `[command options]`, but `[global options]` should also be renamed to `[options]` since there is no other options to distinguish global options from. In other words, all options are already global when there are no subcommands. This also means the "global options" section in the docs / help message should be renamed to simply "options" for consistency.

## Describe alternatives you've considered

It is possible to create custom help messages. However, in this case, the `help` subcommand cannot be removed.

**Comment by dearchap** [comment]
@midirhee12 Have you tried the HideHelp/HideHelpCommands options ? https://github.com/urfave/cli/blob/main/command.go#L54

**Comment by midirhee12** [comment]
Oh, I did not see HideHelpCommand. I think I assumed it did not exist since it was not in the [full api example docs](https://cli.urfave.org/v2/examples/full-api-example/). Do you mind if we change the name of this issue and repurpose it to update the API docs then?

**Comment by dearchap** [comment]
Sure. Would you like to submit a PR against the docs ?

**Comment by midirhee12** [comment]
Yeah, sure. It is 21:03 here. So it'll have to be tomorrow.
