### ISSUE TITLE
cli/v2 panic because of flag redefined after enable aliases

### ISSUE THREAD

**Issue by gzliudan** [urfave/cli#2011]
## My urfave/cli version is

 v2.27.5

## Checklist

- [Y] Are you running the latest v2 release? The list of releases is [here](https://github.com/urfave/cli/releases).
- [Y] Did you check the manual for your release? The v2 manual is [here](https://cli.urfave.org/v2/getting-started/)
- [Y] Did you perform a search about this problem? Here's the [GitHub guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## Dependency Management

- My project is using go modules.

## Describe the bug

After I add `Aliases` for a flag:

```go
	XDCXDataDirFlag = &flags.DirectoryFlag{
		Name:     "XDCx.datadir",
		Aliases:  []string{"XDCx-datadir"},
		Usage:    "Data directory for the XDCX databases",
		Value:    flags.DirectoryString(filepath.Join(DataDirFlag.Value.String(), "XDCx")),
		Category: flags.XdcxCategory,
	}
```

some of my test cases failed with below messages:

```text
    test_cmd.go:249: (stderr) XDC-test flag redefined: XDCx.datadir
    test_cmd.go:249: (stderr) panic: XDC-test flag redefined: XDCx.datadir
```

If I remove `Aliases` this line, then all test cases passed without error.

## To reproduce

```shell
git clone https://github.com/gzliudan/XDPoSChain
git checkout cli-alias

# test with Aliases
make all && make test

# test without Aliases
git reset --hard 8aaa6919
make all && make test
```

## Observed behavior

`make test` reported: flag redefined.

## Expected behavior

should pass all test cases.

## Want to fix this yourself?

no

## Run `go version` and paste its output here

```text
go version go1.21.13 linux/amd64
```

## Run `go env` and paste its output here

```text
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/me/.cache/go-build'
GOENV='/home/me/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/me/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/me/go'
GOPRIVATE=''
GOPROXY='https://goproxy.cn,direct'
GOROOT='/home/me/govm/golang/go-1.21.13'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/home/me/govm/golang/go-1.21.13/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.21.13'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/home/me/XDPoSChain/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build2475665159=/tmp/go-build -gno-record-gcc-switches'
```

**Comment by dearchap** [comment]
@gzliudan I believe your intent here 

https://github.com/gzliudan/XDPoSChain/blob/57e40f59d7fe24a9c1b2d80d9187d3b28d176cd7/cmd/utils/customflags.go#L78

was 

```
	eachName(df.Name, func(name string) {
		set.Var(&df.Value, name, df.Usage)
	})
```

otherwise you are applying the same name multiple times ?

**Comment by gzliudan** [comment]
> @gzliudan I believe your intent here
> 
> https://github.com/gzliudan/XDPoSChain/blob/57e40f59d7fe24a9c1b2d80d9187d3b28d176cd7/cmd/utils/customflags.go#L78
> 
> was
> 
> ```
> 	eachName(df.Name, func(name string) {
> 		set.Var(&df.Value, name, df.Usage)
> 	})
> ```
> 
> otherwise you are applying the same name multiple times ?

The file `cmd/utils/customflags.go` has been removed in my branch: 
 https://github.com/gzliudan/XDPoSChain/tree/cli-alias

**Comment by dearchap** [comment]
@gzliudan The same behavior is in your branch as well.

https://github.com/gzliudan/XDPoSChain/blob/cli-alias/internal/flags/flags.go#L83

I believe your intent is 

```
	eachName(f, func(name string) {
		set.Var(&f.Value, name, f.Usage)
	})
```

**Comment by gzliudan** [comment]
Thank your very much. I fixed it by the commit: https://github.com/gzliudan/XDPoSChain/commit/24f53f78fd380878aa0c50924dd43046090f76f8.

But I don't think it's a good solution. Can we check the name is an alias ?

> @gzliudan The same behavior is in your branch as well.
> 
> https://github.com/gzliudan/XDPoSChain/blob/cli-alias/internal/flags/flags.go#L83
> 
> I believe your intent is
> 
> ```
> 	eachName(f, func(name string) {
> 		set.Var(&f.Value, name, f.Usage)
> 	})
> ```

**Comment by dearchap** [comment]
That panic is what is triggerred by golang flag package so for now there is nothing we can do since you are setting the name directly by flagset

**Comment by gzliudan** [comment]
I find a better solution:

change:

```go
func (f *DirectoryFlag) Apply(set *flag.FlagSet) error {
	eachName(f, func(name string) {
		set.Var(&f.Value, f.Name, f.Usage)
	})
	return nil
}
```

to

```go
func (f *DirectoryFlag) Apply(set *flag.FlagSet) error {
	set.Var(&f.Value, strings.Trim(f.Name, " "), f.Usage)
	return nil
}
```

**Comment by dearchap** [comment]
I don't think that will work when you have aliases. Have you tested this cli with the alias command ? It won't work

**Comment by gzliudan** [comment]
Sorry, I just noticed that the code you recommended before is the best solution.
