### ISSUE TITLE
StringFlag: let cli.File() also strings.TrimSpace()

### ISSUE THREAD

**Issue by 6543** [urfave/cli#2013]
## Checklist

* [x] Are you running the latest v3 release? The list of releases is [here](https://github.com/urfave/cli/releases).
* [x] Did you check the manual for your release? The v3 manual is [here](https://github.com/urfave/cli/blob/main/docs/v3/index.md).
* [x] Did you perform a search about this feature? Here's the [GitHub guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## What problem does this solve?

```go
	&cli.StringFlag{
		Name:  "grpc-token",
		Usage: "server-agent shared token",
		Sources: cli.NewValueSourceChain(
			cli.File(os.Getenv("WOODPECKER_AGENT_SECRET_FILE")),
			cli.EnvVar("WOODPECKER_AGENT_SECRET")),
	},
```

most editors add a newline at the end of an file, this causes issues if you wana read a single line string from it ...

A clear and concise description of what problem this feature would solve. For example:

- needing to type out the full flag name takes a long time, so I
  would like to suggest adding auto-complete
- I use (osx, windows, linux) and would like support for (some
  existing feature) to be extended to my platform
- the terminal output for a particular error case is confusing, and
  I think it could be improved

## Solution description

It would be nice to have either an option to trim space or an FileTrimSpace() ...
... other idears are welcome too :)

##  Alternative

well I will just trim the value myselfe in code ...
... this is more of an UX question rather than missing feature but just see it as feedback :)

**Comment by dearchap** [comment]
@6543 You've raised too many points(issues?) in this issue. So just for my clarification here are the points

- Use strings.TrimSpace() when using cli.File(). yes we can look at that. 
- need to type out full flag name : we do have auto-completion for common shells like bash, zsh and powershell . Are you not able to use those ?
- What feature(s) are you expecting to be supported on your platform(s) ? 
- terminal output : yes we are working on that

**Comment by 6543** [comment]
> Use strings.TrimSpace() when using cli.File(). yes we can look at that.

that one but I also have concnerns if we do so that there might be an edgecase that could fail in this regards ... through I'm not arware of one.

I just noticed an strange behaviour in my project and in the end it was just wrong asumptions of the api of urfave.cli -> so thats why i created this issue here

with the question: should we streamline cli.File() via trim or will this limit other usecases?!?


PS my fix: https://github.com/woodpecker-ci/woodpecker/pull/4465 is personally sufficient enouth for me.

**Comment by dearchap** [comment]
@6543 Try this

```
&cli.StringFlag{
		Name:  "grpc-token",
		Usage: "server-agent shared token",
                Config: cli.StringConfig{
                         TrimSpace: true,
                },
		Sources: cli.NewValueSourceChain(
			cli.File(os.Getenv("WOODPECKER_AGENT_SECRET_FILE")),
			cli.EnvVar("WOODPECKER_AGENT_SECRET")),
	},
```

I forgot that we had this option !!!

**Comment by 6543** [comment]
uh nice! that solves this issue :)

I would now normal ask if that could be better documented but I could not find the docu for devs at all :D

**Comment by dearchap** [comment]
Yes we are working on pushing out v3 documentation.

**Comment by 6543** [comment]
thanks for the tip anyway :) :rocket: 

and sorry for my not on point description of my idea ... in this issue :rock:
