### ISSUE TITLE
Can't use `-` as option value

### ISSUE THREAD

**Issue by unera** [urfave/cli#2030]
For example we have a subcommand/command flag:

```go
&cli.StringFlag{
          Name:     "output",
          Usage:    "output file name",
          Aliases:  []string{"o"},
          Required: false,
          Value:    "",
},
```

and then in command handler we have the following code:

```go
outFile := cCtx.String("output")

if outFile == "-" {     // traditional UNIX convention
    outFile = "/dev/stdout"
}

// code that writes output

```

In UNIX I can do:

```
$ foo bar -o file.txt
$ foo bar -o /dev/stdout
$ foo bar -o -                         # the same
$ foo bar -o-                          # works in UNIX, doesn't in THE CLI
```

`-o-` works under `getopt` , works under `argparse`, but doesn't under the cli.

the cli prints error:

```
Incorrect Usage: flag provided but not defined: -o-
```

**Comment by dearchap** [comment]
Interesting. I know this was working in v2. Perhaps we broke something in v3 . I'll take a look . Thanks for reporting @unera

**Comment by unera** [comment]
> I know this was working in v2.

I'm sorry, but I checked in v2, not v3.

Now I'll try to switch to v3 and come back.

**Comment by unera** [comment]
Yes, I switched to v3 and can reproduce the error, too
