### ISSUE TITLE
How to mock/"inject" parsed flags into a `Command` for testing?

### ISSUE THREAD

**Issue by oxisto** [urfave/cli#2035]
I want to test the functions I use for `Action` using a unit test, that supplies a pre-filled `cmd` to the `ActionFunc`, but I do not want to "run" the `Command`. Is there a way to prefill the parsed flags for a command for a unit test? It seems that they "live" in `parsedArgs` which is populated in `parseFlags`, but all of these functions are unexported. Would it make sense to have a public API that just parses the arguments, but does not "run" the command?

(this is related to v3)

**Comment by dearchap** [comment]
Why not have the command execute ? It's easier than having to export other fields and increase the API surface which we don't want to do . If you look at the test code there are multiple tests which do exactly this .

**Comment by oxisto** [comment]
Thanks for the quick reply, being a maintainer myself, I can understand the pain of changing/increasing the public API.

> Why not have the command execute ? It's easier than having to export other fields and increase the API surface which we don't want to do . If you look at the test code there are multiple tests which do exactly this .

This is of course possible, two things that I do not "like" about this approach
1) I am a fan of unit tests of different granularity, so I would usually test the action function on its own and then test it as part of the command; but this might not be completly necessary in the action case
2) My commands are nested (and stored in one variable) and it's a bit cumbersome to access the subcommands like `CLI.Commands[2].Commands[0]`. Is there a way to retrieve a sub-command by its name?

Update: I have just discovered `Command.Set`, which might be what I am looking for to set flag values.
