### ISSUE TITLE
Introduce variable Executable that is displayed in usage instead of the Name

### ISSUE THREAD

**Issue by muja** [urfave/cli#210]
Example from coreutils' ls:
```bash
$ ls --help
Usage: ls [OPTION]... [FILE]...

$ /usr/local/opt/coreutils/libexec/gnubin/ls --help
Usage: /usr/local/opt/coreutils/libexec/gnubin/ls [OPTION]... [FILE]...
```

I think it makes sense to split up the app's name and its executable into two variables, and use the executable in the usage field of the HelpTemplate.

I have implemented this behaviour in my fork: https://github.com/muja/cli/commit/b2261c6d78c2c8d146c45780103abdafe8dbc1b8

I wish to make a pull request, however, this is (deliberately) not backward-compatible so I first wanted to hear your opinion.

Oh and the commit also introduces a small consistency fix where the Name is set via "arguments[0]" passed in Run() instead of "os.Args[0]"

**Comment by meatballhat** [comment]
Sorry for the long delay!  This should be covered by both `App.Name` and `App.HelpName`.  Please yell if you disagree!
