### ISSUE TITLE
Proposal: option to hide help subcommand and keep global option

### ISSUE THREAD

**Issue by ahmetalpbalkan** [urfave/cli#222]
I have a use case where I want to hide the `help` subcommand that gets added to the app by default; however, I want to keep `-h, --help` because that's generally what people run when they need help.

Unfortunately, currently `app.HideHelp=true` hides both. 

```
$ mycmd
NAME:
   mycmd

USAGE:
   mycmd [global options] command [command options] [arguments...]

[...]
COMMANDS:
   foo		does foo
   bar		does bar
   help, h	Shows a list of commands or help for one command  <------- hide this 👎

GLOBAL OPTIONS:
   --help, -h		show help  <------- keep this 👍
   --version, -v	print the version

```

We can have another option `app.HideHelpSubcommand` to hide the subcommand and `HideHelp` would still hide both globab option and the subcommand to keep it backwards compatible.

How do folks feel about such a feature?

**Comment by wking** [comment]
I was missing this too, but it looks like there's something similar currently in flight with #636.
