### ISSUE TITLE
Support for TOML in altsrc

### ISSUE THREAD

**Issue by aacanakin** [urfave/cli#235]
What I currently need is to be able to use this library by using a defined configuration. I have a revel.Config or TOML configuration. I need to be able to inject this config structure into context or app struct. Is this possible currently ? If not, is there any plan to integrate a configurations module with this package ?

**Comment by wrouesnel** [comment]
+1 to this. Environment variable support is nice, but it'd be perfect if there was an official way to set default configuration from a file ala iniflags.

**Comment by jszwedko** [comment]
I agree that this would be useful.

**Comment by freddy33** [comment]
+1 repeating flags on each call is better solved with conf file in user home than with env vars.

**Comment by zpatrick** [comment]
+1

**Comment by jszwedko** [comment]
This is supported by https://github.com/codegangsta/cli/pull/306 for YAML -- changing the title to reflect `TOML` support, but it should be possible just by implementing the `altsrc.InputSourceContext` interface.

**Comment by jszwedko** [comment]
Support added in #491
