### ISSUE TITLE
Positional argument specifications

### ISSUE THREAD

**Issue by stevvooe** [urfave/cli#240]
I may be missing something in the documentation, but there doesn't seem to be a way to specify positional arguments for each commands. For example, one may want to specify in the help that two arguments are accepted only:

```
NAME:
   foo - Apply foo to argument bar and optionally a baz

USAGE:
   command foo bar [baz]
```

This seems like a straightforward addition to the library but I wanted to get feedback before dropping a PR. Python's [`argparse`](https://docs.python.org/3/library/argparse.html) provides a good example of this done well. Such a feature also provides the benefit that arguments can be pre-validated before proceeding with the command.

**Comment by jszwedko** [comment]
Work has been started on this over here: #140

**Comment by lynncyrin** [comment]
Given that this is from last year, I think I'm comfortable closing it 🙂 feel free to re-open / open a new issue / comment in support if there's still interest here!
