### ISSUE TITLE
Add App.License struct member

### ISSUE THREAD

**Issue by dreh23** [urfave/cli#255]
App.license = "MIT"

**Comment by meatballhat** [comment]
@dreh23 Sorry for the long delay!  Are you able to accomplish this with `App.Metadata` and a custom app help template as described [here](https://github.com/codegangsta/cli#generated-help-text-customization)?

**Comment by meatballhat** [comment]
There's also `App.Copyright`, although it's semantically different (depending on religion.)  Please yell if you believe this has been closed in error!
