### ISSUE TITLE
Subcommand and help text

### ISSUE THREAD

**Issue by orbatschow** [urfave/cli#262]
Hi there,

is there any possibility to create a command with a subcommand like this :

cli test:add

while cli is the name of the app, test is the command and :add is the subcommand ?

I'm also wondering if the possibility exists, whether the help text can be formatted like this:

add     #  add a new template

with the hash as a divider.

And maybe i can also add a custom usage text ?

**Comment by jszwedko** [comment]
@Synturas currently it expects commands to be space delimited, but this is an interesting idea. I'd be happy to take a look at a PR adding the ability to set the command/subcommand delimiter.

You can override the help print out via the exposed package level variables containing the templates.

**Comment by lynncyrin** [comment]
Given that this is from last year, I think I'm comfortable closing it 🙂 feel free to re-open / open a new issue / comment in support if there's still interest here!
