### ISSUE TITLE
Help text should automatically wrap based on term width

### ISSUE THREAD

**Issue by nikkolasg** [urfave/cli#287]
When we got a long text description in Usage, it should automatically wrap and make a nice display.
A bit like what "man" does, it automatically rewraps the text so it fits nicely in the current terminal session.

**Comment by wikiwi** [comment]
+1

**Comment by syossan27** [comment]
+1

**Comment by immesys** [comment]
+1

**Comment by hickeng** [comment]
and should be able to handle `\n` in the various command and flag descriptions, indenting appropriately.

**Comment by JensRantil** [comment]
...or simply wrap at 80 characters, which is considered a common default and also adheres to [general readability best-practises](https://baymard.com/blog/line-length-readability).

**Comment by lynncyrin** [comment]
This feature is now `in review` - @urfave/cli please add a 👍 or 👎 to the top post if you're in favor or against this feature being added!

**Comment by saschagrunert** [comment]
@lynncyrin we should move forward with this one. Wrapping based on the term width seems a sane default. :)

**Comment by lynncyrin** [comment]
👀 this is now ready for anyone to work on!

**Comment by xordspar0** [comment]
> ...or simply wrap at 80 characters, which is considered a common default and also adheres to [general readability best-practises](https://baymard.com/blog/line-length-readability).

I agree that an 80 character limit would be easier to read. It would also be easier to implement. That said, I don't want to bikeshed this issue. Whoever actually does the work to implement this will have my vote.

**Comment by mostynb** [comment]
I will try to make #1119 implement a basic version of this feature.

**Comment by mostynb** [comment]
Bump.

**Comment by mostynb** [comment]
Bump.

**Comment by mostynb** [comment]
Bump.

**Comment by dearchap** [comment]
@mostynb Are you up to making a PR for this ?

**Comment by dearchap** [comment]
Duplicate of #674

**Comment by mostynb** [comment]
I added line-wrapping support in #287, but the terminal's width detection is not automatic (to avoid adding new dependencies/adding binary size). Here's an example of how client code can specify the line-wrap length: https://github.com/urfave/cli/pull/1119/files#diff-4d3f36d62cad94424544bb84fc93b33b73ffe3491a4ddca81a7f825539afc19cR1161-R1169
