### ISSUE TITLE
Allow --help to be provided first

### ISSUE THREAD

**Issue by calvn** [urfave/cli#318]
## Request

Allow `greet --help command` to show help output

## Context

The docs, and in general with CLI's, says that the global `--help` flag should come before the command if you need more info on that command. However, doing so is not a valid entry (or at least it doesn't show you the help for that command) with this CLI library.

```
 greet [global options] command [command options] [arguments...]
```

Assuming that `command` is a valid command, `greet --help command` doesn't show me the help for `command`, but `greet command --help` does. With the git CLI, for example, both `git --help status` and `git status --help` works.

---

_edited by @lynncyrin!_

**Comment by jszwedko** [comment]
Hi @cleung2010, I don't believe that behavior is supported, where did you find it in the docs?

**Comment by cleung2010** [comment]
Let me provide you an example:
```go
package main

import (
  "os"
  "github.com/codegangsta/cli"
)

func main() {
  app := cli.NewApp()
  app.Name = "hello"
  app.Usage = "Say hello"
  app.Version = "0.1.0"
  app.Commands = []cli.Command {
    {
      Name: "say",
      Usage: "Say something",
      Action: func(c *cli.Context) {
        println("Called the say command")
      },
    },
  }

  app.Run(os.Args)

}
```
Outputs:
```bash
$ ./hello --help say
NAME:
   hello - Say hello

USAGE:
   hello [global options] command [command options] [arguments...]
   
VERSION:
   0.1.0
   
COMMANDS:
   say		Say something
   help, h	Shows a list of commands or help for one command
   
GLOBAL OPTIONS:
   --help, -h		show help
   --version, -v	print the version

$ ./hello say --help
NAME:
   hello say - Say something

USAGE:
   hello say [arguments...]

```

As you can see, `hello say --help` gives me the help for the say command, but not when used the other way around (`hello --help say`).

If you do `git status --help` or `git --help status` it gives you the help for the status command. A lot of the CLI's supports `program --help [command]` and I was expecting cli.go to support this as well (git, Hashicorp's tools, rvm, etc.).

**Comment by jszwedko** [comment]
@cleung2010 :+1: I follow -- I initially thought you meant you saw something about this in the documentation for this library, but I agree that this would be a good enhancement.

Thanks for the report!

**Comment by thedoc31** [comment]
#744 also references this but the other way around; global options are not available to the subcommands and throw weird error messages if you try to use them. Definitely needs to be made consistent with other non-Go CLI tools.

**Comment by lynncyrin** [comment]
As far as I can tell, this issue is waiting for someone who wants to work on it 🙂 anyone is free to take it!

**Comment by lynncyrin** [comment]
This is possibly a duplicate of https://github.com/urfave/cli/issues/176

**Comment by lynncyrin** [comment]
Closing as stale! We can re-open if there's interest in the future
