### ISSUE TITLE
bash auto-completion with directories as argument

### ISSUE THREAD

**Issue by aanm** [urfave/cli#388]
Hey,
I'm trying to build something that uses a directory as first argument. Something like:
`command sub-command [flags] directory-argument` 

If I enable bash auto-completion, it doesn't show up the directories that I can use as argument.

I was looking that `command sub-command [flags] fo[TAB]` would present
`foo/ foo2/ foo3/` and `command sub-command [flags] foo/[TAB]` would present `bar/ bar2/ bar3/` (being `bar*` the directories inside `foo`.

Is this possible or is it too hard to implement?

**Comment by jszwedko** [comment]
It seems reasonable to me to fall through to listing files in the working directory if the current command being tabbed completed has no additional subcommands.

**Comment by meatballhat** [comment]
(untested) Perhaps this can be managed by using `compgen -o dirnames -o plusdirs` in the `./autocomplete/bash_autocomplete` file and equiv for zsh.

**Comment by meatballhat** [comment]
(somewhat tested) afaict, `compgen`'s options for filename, dirname, and "default" completion gets partway there, but the exact behavior @aanm is describing may require a solution inside cli.

**Comment by meatballhat** [comment]
Getting closer, maybe: https://gist.github.com/meatballhat/3e732779539fff1866df5b966e3490e5

This solution is only for `bash`, and I'm using version 4.3.42.  I still tend to think that a solution that works consistently across shells and versions of said shells may require dipping into the cli layer, but I also think that the amount of `bash` code involved here isn't too terrible.

**Comment by aanm** [comment]
I'm not sure if I was clear or not. But I only want to show directories not files. I thought when we ran `command sub-command [flags] foo/[TAB]` that my own BashComplete function would receive `foo/` as the first program argument, but it doesn't. If it did I would do something like:

```go   
     BashComplete: func(c *cli.Context) {
      for _, file := range ioutil.ReadDir(c.Args.FirstArg()) {
        if file.IsDir() {
         fmt.Println(file.Name())
       }
      }
    },
```

**Comment by aanm** [comment]
Accidentally closed the issue sorry.

**Comment by jszwedko** [comment]
I think the real issue here is that the `BashComplete` function doesn't appear to be called on subcommands. E.g.:

```go
package main

import (
        "fmt"
        "os"

        "github.com/codegangsta/cli"
)

func main() {
        app := cli.NewApp()
        app.Name = "greet"
        app.Commands = []cli.Command{
                {
                        Name:        "english",
                        Aliases:     []string{"en"},
                        Usage:       "sends a greeting in english",
                        Description: "greets someone in english",
                        Action: func(c *cli.Context) {
                                fmt.Println("Hello,", c.String("name"))
                        },
                },
        }
        app.BashComplete = func(c *cli.Context) {
                fmt.Printf("%+v\n", c.Args())
        }
        app.EnableBashCompletion = true
        app.Run(os.Args)
}
```

Where

`foo --generate-bash-completion some-dir/`

prints

`[some-dir/]`

but

`foobar english --generate-bash-completion some-dir/`

prints nothing (i.e. the completion function isn't called).

**Comment by jszwedko** [comment]
Of note,

```go
package main

import (
        "fmt"
        "os"

        "github.com/codegangsta/cli"
)

func main() {
        app := cli.NewApp()
        app.Name = "greet"
        app.Commands = []cli.Command{
                {
                        Name: "english",
                        Subcommands: []cli.Command{
                                {
                                        Name: "english2",
                                },
                        },
                },
        }
        app.BashComplete = func(c *cli.Context) {
                fmt.Printf("%+v\n", c.Args())
        }
        app.EnableBashCompletion = true
        app.Run(os.Args)
}
```

When called as `foobar english --generate-bash-completion some-dir/` prints:
```
english2
help
h
```

Which implies that the default autocompleter is used for subcommands.

**Comment by HarrisonMc555** [comment]
Has there been any work on this? If I understand the issue that @jszwedko was bringing up I think it's fixed; I've been able to get the autocompleter to work for sub-commands.

However, I still don't know of a way to get completion for directories and/or files. Is there a way to tell a sub-command "revert back to the shell's default completion mechanism"? It was previously mentioned that this might mean something different for different shells, but I think it would still be worth it.

Or is what I want different enough from this issue to warrant opening a new one?

**Comment by lynncyrin** [comment]
Given that this is from last year, I think I'm comfortable closing it 🙂 feel free to re-open / open a new issue / comment in support if there's still interest here!
