### ISSUE TITLE
altsrc/yaml parser uses LGPLv3

### ISSUE THREAD

**Issue by gaffo** [urfave/cli#391]
Which isn't really the same as the MIT license that codegangsta/cli comes under. I'm not a license master but since go is compiled from source this feels like it needs to be a fully optional dependency or a different yaml parser should be used. Or  just change the license to LGPLv3.

**Comment by jszwedko** [comment]
Good catch, I didn't realize that. There is a provision in the library's license, https://github.com/go-yaml/yaml/blob/v2/LICENSE#L6-L13, that makes seems to allow a bit more flexible usage of the library, but it does seem like the `altsrc` package should be licensed under LGPLv3 to comply (also not a license expert).

The `altsrc` package is a fully optional dependency that is only compiled in if you use it.

**Comment by gaffo** [comment]
Sure... I would say tho that because of the way go-get works you're basically opting into GPLv3 (or vairant) by go get where the root LICENSE file says MIT which means you're stealth accepting GPLv3. I haven't seen a go packge that has different sections under different licenses before. What would really suck is if you pulled in say some high level package and it slurped down this dependency and then the GPLv3. I know that you should be reading all your imports if you have to deal with this stuff so you should probbably catch it with a grep.

I would vote that you should move it to a package that depends on this. I know this kinda sucks. Licensing is hard. 

For my use of it I removed the use of the optional part and since the rest if MIT. But I'm not a legal expert and so I'll validate it with lawyers. So you are saying that this would be okay and under the part of your use of MIT?

**Comment by meatballhat** [comment]
fwiw, I'd be happy with keeping a single top-level LICENSE file with the MIT license and ensuring that the explanation of the optional yaml dependency in the README mentions that the yaml project declares its own license, and that this is expected to be the case with *any* compile-time dependencies.  We don't vendor their source code, nor do we distribute binaries generated from their source code, so I don't see why we should be changing anything about *our* license.

**Comment by meatballhat** [comment]
Related:

``` shell-session
$ go get github.com/pmezard/licenses/...
$ licenses github.com/codegangsta/cli
github.com/codegangsta/cli  MIT License
$ licenses github.com/codegangsta/cli/...
github.com/codegangsta/cli/altsrc  MIT License
gopkg.in/yaml.v2                   GNU Lesser General Public License v3.0 (95%)
```

**Comment by mattfarina** [comment]
First, I am not a lawyer and this is not legal advice.

With that said, it's important to note the yaml.v2 package is LGPLv3 and not GPLv3. For anyone who doesn't know, there are important significant differences. The difference in the part were discussing is summed up well at http://programmers.stackexchange.com/a/141848.

The first point blank question to answer is... is the YAML handling in `altsrc` a derivative work of `yaml.v2` or a package that uses `yaml.v2`? If it is a derivative work can you please explain how it is one?

**Comment by meatballhat** [comment]
@mattfarina the YAML handling in `altsrc` is not a derivative work, afaict.  The differences between LGPLv3 and GPLv3 are one of the reasons why I stick to MIT whenever possible :smile_cat: :heart: :trollface:

**Comment by mattfarina** [comment]
@meatballhat if it's not a derivative work then `altsrc` should be fine as MIT.

I tend to find a bit of confusion on this point. I used to be one of the confused people. I still am far too often.

_Disclaimer: I'm not a lawyer so please consult yours or make your own call._

**Comment by meatballhat** [comment]
Yep, that's my (shaky) understanding of how this works.  We're not
distributing binaries, either, so I think our current license situation is
good and legal.

**Comment by jszwedko** [comment]
I believe this to be correct -- I imagine that users distributing binaries that use the `altsrc` package would, however, need to be LGPLv3 licensed. I think including this information in the README / the top level license would suffice for informing users.

Maybe @niemeyer can weigh in? I imagine they have a better command of the intention of the license given that they chose it.

**Comment by meatballhat** [comment]
I'm closing this out for now, but please yell if you feel that it needs more discussion!
