### ISSUE TITLE
No default value for options in help message

### ISSUE THREAD

**Issue by hqhq** [urfave/cli#416]
Now in cli help message, if an option takes value, it'll show like:
```
--root value          description for root option
```

Even if I have a default value when define this option:
```
cli.StringFlag{
    Name: "root",
    Value: "/run/myroot",
    Usage: "some descriptions",
}
```

I suppose if we have default `Value` assigned, it should be shown in help message like:
```
--root /run/myroot            description for root option
```

And I remember it used to work like this, so maybe this is a regression?

**Comment by jszwedko** [comment]
HI @hqhq,

With

```
package main

import (
        "os"

        "github.com/urfave/cli"
)

func main() {
        app := cli.NewApp()
        app.Name = "greet"
        app.Flags = []cli.Flag{
                cli.StringFlag{
                        Name:  "root",
                        Value: "/run/myroot",
                        Usage: "some descriptions",
                },
        }
        app.Run(os.Args)
}
```

I see the following in the output:

```
   --root value         some descriptions (default: "/run/myroot")
```

which does include the default.

This behavior did change relatively recently in https://github.com/urfave/cli/pull/381 so you may just need to update your local copy of `cli`.

Please let me know if this resolves your issue!

**Comment by hqhq** [comment]
Ah, I didn't notice it's in description, it works for thank.

But I found another issue,

```
package main

import (
        "os"

        "github.com/urfave/cli"
)

func main() {
        app := cli.NewApp()
        app.Name = "greet"
        app.Flags = []cli.Flag{
                cli.StringFlag{
                        Name:  "root",
                        Value: "/run/myroot",
                        Usage: "some descriptions, set `-1` for test",
                },
        }
        app.Run(os.Args)
}
```

If I change Usage as above, help message will show:
```
GLOBAL OPTIONS:
   --root -1            some descriptions, set -1 to test (default: "/run/myroot")
   --help, -h           show help
   --version, -v        print the version
```

Is this a bug?

**Comment by jszwedko** [comment]
@hqhq this is actually the placeholder feature described here: https://github.com/urfave/cli#placeholder-values

**Comment by hqhq** [comment]
@jszwedko Thanks, got it now, closing the issue.
