### ISSUE TITLE
Unexpected "Incorrect usage" message

### ISSUE THREAD

**Issue by fgblomqvist** [urfave/cli#426]
I have been trying to make cli work as intended, but all I get when I set my custom flags is "Incorrect usage" without any explanation as to what went wrong.

Here's the code:

```
	app.Flags = []cli.Flag {
		cli.StringFlag{
			Name: "db, d",
			Usage: "Name of the database",
		},
		cli.StringFlag{
			Name: "user, u",
			Value: "postgres",
			Usage: "Username for the database",
		},
		cli.StringFlag{
			Name: "password, p",
			Value: "",
			Usage: "Password for the database",
		},
	}
```

I have tried to set them both using the shorthand, -p, -u etc. and using the longer --password, --user etc. What am I doing wrong?

EDIT: I am also confused as to why the dash is missing from my shorthands in the help output:
```
GLOBAL OPTIONS:
   --db, d value        Name of the database
   --user, u value      Username for the database (default: "postgres")
   --password, p value  Password for the database
   --help, -h           show help
   --version, -v        print the version
```

I'm using the v2 branch.

**Comment by fgblomqvist** [comment]
Both these problems were solved by switching to the v1 branch, sorry I did not realize v2 was that much alpha. I'll wait with closing this in case the developers working on v2 did not know about these problems.

**Comment by meatballhat** [comment]
@fgblomqvist Thanks for the report!  Yes please leave this open :smiley:

**Comment by meatballhat** [comment]
@fgblomqvist I think I've found it.  Both the "Incorrect Usage" message and unexpected help text happen when using the comma-separated form for `Name:`, which is not supported in `v2`, although this is not at all obvious, not really documented, and the error you got doesn't help you at all 😕.  I'd like to keep this open as a bug until the situation is improved.

**Comment by fgblomqvist** [comment]
Okay, thank you, I'm glad I could help :smiley:
