### ISSUE TITLE
Add positional arguments to command usage

### ISSUE THREAD

**Issue by LLParse** [urfave/cli#449]
It would be incredibly nice to document positional arguments somehow, maybe by adding an 'Args' field to Command struct.

This may already be possible, but looking at the code/readme it was not obvious. Thanks for your help.

**Comment by meatballhat** [comment]
@LLParse I think you're looking for the `ArgsUsage` string, present on both the App and Command structs :smiley:

**Comment by LLParse** [comment]
How sill am I, that plain english eludes me! Thanks for your quick reply @meatballhat
