### ISSUE TITLE
Panic being swallowed

### ISSUE THREAD

**Issue by mattmc3** [urfave/cli#451]
Within a CLI Action function, I have some code that called a library method and it had a panic: "runtime error: invalid memory address or nil pointer dereference". The Action function never reported the issue and just swallowed the panic and exited.

I finally traced it down by putting a panic call in the action function directly and got:
"ERROR unknown Action error: See https://github.com/urfave/cli/blob/master/CHANGELOG.md#deprecated-cli-app-action-signature", which finally led me to discover that CLI is just eating panics when they don't happen directly in the Action function. Eating panics is just not an acceptable way to handle errors.

I was able to work around the issue by putting the following code at the top of all my actions methods:

```
defer func() {
	if r := recover(); r != nil {
		fmt.Println("ERROR: ", r, string(debug.Stack()))
	}
}()
```

I'm not sure where of why the CLI library is doing its bad behaving `recover` yet, but I wanted to submit the bug report to help anyone else who can't trace down their error. Hope this behavior is easily corrected.

**Comment by meatballhat** [comment]
@mattmc3 Yikes!  This definitely was not the intent.  For what it's worth, this behavior doesn't exist on the `v2` branch, as the compatibility code for `Action interface{}` has been removed in favor of `Action ActionFunc`.  I'll look into getting this behavior changed to (correctly) bubble up unknown panics.
