### ISSUE TITLE
cannot use cli.IntFlag literal (type cli.IntFlag) as type cli.Flag in array or slice literal: cli.IntFlag does not implement cli.Flag (Apply method has pointer receiver)

### ISSUE THREAD

**Issue by andreynering** [urfave/cli#459]
_**Here is the fix for this issue! => https://github.com/urfave/cli/issues/459#issuecomment-555077623**_

---

I updated today and can't build my app (luckily I do vendoring). Am I missing any API change? The error is below:

``` go
cannot use cli.IntFlag literal (type cli.IntFlag) as type cli.Flag in array or slice literal:
        cli.IntFlag does not implement cli.Flag (Apply method has pointer receiver)
```

---

Also, why the change from `codegangsta/cli` to `urfave/cli`? I couln't find any information on README or anywhere.

Cheers.

---

_edited by @lynncyrin!_

**Comment by epaulet** [comment]
Also getting it for other flag types as well (although it builds locally for me so it must be a recent change?)

```
cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in array element:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
```

```
cannot use cli.StringSliceFlag literal (type cli.StringSliceFlag) as type cli.Flag in array element:
	cli.StringSliceFlag does not implement cli.Flag (Apply method has pointer receiver)
```

**Comment by meatballhat** [comment]
Are both of you pinning to the v2 branch?

**Comment by epaulet** [comment]
Yes. I forgot to mention that in my original post.

**Comment by andreynering** [comment]
Yes, v2

**Comment by meatballhat** [comment]
Ah cool. Sorry about the surprise.  The v2 branch is volatile, and recently
received a patch to introduce a lot more pointer receivers.  Switching from
struct literals to pointers to struct literals should do the trick.  The
change log for v2 changes should cover everything, and please yell if it
doesn't.  There is also a migration script in the repo root that may help.
Please provide feedback!  :smile_cat:

**Comment by meatballhat** [comment]
related: thoughts on renaming the `v2` branch to `v2pre` or equiv?

**Comment by andreynering** [comment]
My fault that I thought the `v2` was stable. Downgrading to `v1` fixed for me. Thank you.

**Comment by meatballhat** [comment]
@andreynering :+1:

**Comment by Tengoru** [comment]
Hi, I have the same problem but with version 1. I tried to copy the code snippets from the documentation but no luck... Any ideas what the problem could be?

**Comment by Tengoru** [comment]
For everyone having the same problem... Just add a "&" at the beginning of the IntFlag or StringFlag (or whatever flag you have)... Yeah... Took me 1 hour to realise that... Example:
```
func flags() {
	flag1 := cli.IntFlag{
		Name:        "id",
		Usage:       "id for identification",
		Destination: &id,
	}
	flag2 := cli.StringFlag{
		Name:        "token",
		Usage:       "token verification",
		Destination: &token,
	}
	app.Flags = []cli.Flag {
		&flag1,
		&flag2,
	}
}
```

**Comment by poupas** [comment]
On v1, just got bit by this right now. @Tengoru's example fixed it for me.

**Comment by whirlwin** [comment]
`  app.Flags = []cli.Flag{
    &cli.StringFlag{
      Name:  "config, c",
      Usage: "Load configuration from `FILE`",
    },
  }`

Worked for me.

**Comment by djfemz** [comment]
app.Flags = []cli.Flag{
    &cli.StringFlag{
      Name:  "name, n",
      Usage: "Print Hello World`",
    },
  }
works just fine
