### ISSUE TITLE
questions for multi options 

### ISSUE THREAD

**Issue by joyhope** [urfave/cli#471]
curl supports options appears multi times.

e.g curl  -H "xx1:yy1" -H "xx2:yy2", ...

whether the cli support such style?

**Comment by jszwedko** [comment]
Hi @joyhope!

This is the supported behavior for all `*Slice` flags, e.g. `StringSlice`. Example:

```go
package main

import (
        "fmt"
        "os"

        "github.com/urfave/cli"
)

func main() {
        app := cli.NewApp()
        app.Flags = []cli.Flag{
                cli.StringSliceFlag{Name: "names, N"},
        }
        app.Action = func(c *cli.Context) error {
                fmt.Printf("%#v\n", c.StringSlice("names"))

                return nil
        }

        app.Run(os.Args)
}
```

Let me know if that answers your question!

**Comment by jszwedko** [comment]
Closing this out, but please reopen if you don't feel that the issue was addressed @joyhope
