### ISSUE TITLE
Simplify cli.NewExitError

### ISSUE THREAD

**Issue by gravis** [urfave/cli#475]
Hi,

I need to update a CLI tool because we have some deprecation warnings in the output.
While I thought I could simple return errors from commands, I end up with things like:

```go
 f, err := os.Create("config.yml")
 if err != nil {
     return cli.NewExitError(err.Error(), 1)
 }
 defer f.Close()
 err:= project.Configure(project.Slug, os.Stdin, f)
 if err != nil {
     return cli.NewExitError(err.Error(), 1)
 }
 [...]
 return nil
```

It would be so much easier to simply return `err` in case of error, and cli would display the error, and exit with code 1. Sounds like a very reasonable default, doesn't it?

**Comment by gravis** [comment]
ie, I would like to write:

```go
 f, err := os.Create("config.yml")
 if err != nil {
     return err
 }
 defer f.Close()
 err:= project.Configure(project.Slug, os.Stdin, f)
 if err != nil {
     return err
 }
 [...]
 return nil
```

instead.
It would be the icing on the cake if we could define an Exiter func to change the behaviour when an action returns a non-nil error (like using red text).

**Comment by jszwedko** [comment]
Hi @gravis,

You can achieve this behavior yourself by doing something like:

```go
// define and instantiate a `cli.App`

err := app.Run(os.Args)
if err != nil {
  fmt.Println(err)
  os.Exit(1)
}
```

I can see the argument that you are making though -- I think it makes sense, but would want to think through the drawbacks. Do you have thoughts about this @meatballhat (as the original implementer of this behavior :smile:)?

(It would basically just mean adding a default behavior to https://github.com/urfave/cli/blob/1d47addf284836c9eeaa4c11a0fc24ce37b9d2d8/errors.go#L74-L91)

**Comment by gravis** [comment]
Exactly was I was looking for. I wasn't obvious to me that the error was forwarded to `Run`. It probably needs a small example somewhere in the doc? 
Thanks :)

**Comment by jszwedko** [comment]
@gravis behavior was updated in #496 to match what you described (after discovering that that was the original intent). Thanks for the report!

**Comment by gravis** [comment]
Awesome!
Thanks :)
