### ISSUE TITLE
NewApp missing in v2 branch

### ISSUE THREAD

**Issue by fgblomqvist** [urfave/cli#476]
Tried to create an app using the v2 branch, but directly got an error that cli.NewApp() does not exist?

**Comment by meatballhat** [comment]
@fgblomqvist That is correct, it was removed in `v2` in favor of moving closer to a fully declarative approach.  Are you seeing mention of `NewApp` somewhere in `v2` docs?

**Comment by fgblomqvist** [comment]
Of course I forgot to check the v2 docs instead of the v1 docs....my bad, thanks!
