### ISSUE TITLE
Show help for command

### ISSUE THREAD

**Issue by fgblomqvist** [urfave/cli#477]
I have been trying to figure out how to show the help for a command.
I have tried both `app -h` and `app cmd -h` without success.

`app cmd subcmd -h` works for subcomands, so I would assume `app cmd -h` would work?

**Comment by meatballhat** [comment]
@fgblomqvist What branch/release are you using? 😸

**Comment by fgblomqvist** [comment]
I'm on the latest release on the v1 branch (v1.18).

**Comment by meatballhat** [comment]
@fgblomqvist So far I'm unable to reproduce the problem you're describing, which means I must not understand 😺❤️  https://gist.github.com/meatballhat/5ad61bdb9b72e8729dd6c88dd3a1d278

I *do* see some inconsistencies in there that bother me, but that's another issue ...

**Comment by fgblomqvist** [comment]
@meatballhat Hmm interesting. Clearly it's working in your example.
I ran some more tests and concluded the following:
`app cmd help` works
`app help cmd` works
`app cmd -h` doesn't work (it runs the Action function)
`app cmd --help` doesn't work (it runs the Action function)
I will try to replicate this with an example program...

**Comment by fgblomqvist** [comment]
Here:
https://gist.github.com/fgblomqvist/16336cec3377bf30223ecce11f1d2ff6
Very odd behavior.

**Comment by jszwedko** [comment]
Thanks for the report @fgblomqvist ! Oddly enough, I tried to do a `git bisect` and couldn't find a working version with your test code so it is possible that this never worked. Either way, #481 should address it -- let me know what you think

**Comment by fgblomqvist** [comment]
No problem, happy to help! The changes look good to me. Will go get it as soon as the PR has been merged. Thanks for fixing it!
