### ISSUE TITLE
some commands decide not to respect `--help`

### ISSUE THREAD

**Issue by whyrusleeping** [urfave/cli#478]
I'm not sure what causes it, but some of the commands i write execute their action when run with `--help`.

Repro:
```
go get github.com/whyrusleeping/gx
gx deps --help
```

**Comment by meatballhat** [comment]
@whyrusleeping Hey!  Is this on `master`, `v2`, or something else?

**Comment by meatballhat** [comment]
Also, dupe of #477 looks like, so closing in favor
