### ISSUE TITLE
flag arguments without an intervening space

### ISSUE THREAD

**Issue by deorth** [urfave/cli#488]
Traditionally in unix commands I'm used to being able to do something like -n8, where 8 is the argument to -n.

With this library it seems I can only do -n 8, -n8 will result in an "Incorrect Usage."

Forgive me if I've missed something obvious in the docs and this is user error :)

**Comment by jszwedko** [comment]
Hi @deorth,

Unfortunately that is a limitation of the Golang `flag` package we are leveraging for the actual parsing, but I agree that it would be nice to support this for shortflags if we were to replace the parser with our own. Will tag as an enhancement.

Thanks for the report!

**Comment by lynncyrin** [comment]
Given that this is from last year, I think I'm comfortable closing it 🙂 feel free to re-open / open a new issue / comment in support if there's still interest here!
