### ISSUE TITLE
missing argument leads to vexing behavior

### ISSUE THREAD

**Issue by tychoish** [urfave/cli#503]
First off, thanks for a great package that's saved me a lot of time and frustration. I've recently run into a situation where, I have two string flags, but managed to omit an argument to the first option, which `cli` handled without error, in a situation where I wouldn't have expected it. Consider the following sample program:

```
package main

import (
    "fmt"
    "os"

    "github.com/codegangsta/cli"
)

func main() {
    app := cli.NewApp()
    app.Name = "missing-opt-test"
    app.Flags = []cli.Flag{
        cli.StringFlag{
            Name:  "one",
            Usage: "string flag one",
        },
        cli.StringFlag{
            Name:  "two",
            Usage: "string flag two",
        },
    }
    app.Action = func(c *cli.Context) error {
        fmt.Println("one:", c.String("one"))
        fmt.Println("two:", c.String("two"))
        return nil
    }

    err := app.Run(os.Args)
    if err != nil {
        fmt.Println(err.Error())
        os.Exit(1)
    }
}
```

Then, running this program, I got the following results: 

```
$ ./opt-test --one --two foo 
one: --two
two: 
```

It would be nice if this was an error, or at least produce some sort of warning, but I would expect that one would have been an empty string and two would be "foo". Otherwise, its incumbent on the application to check the value of every string captured by the program to see if its another option (or starts with `--` or `-`, which is a bit bothersome.

Please let me know if there's anything I can do to help out or clarify this case.

**Comment by jszwedko** [comment]
Hi @tychoish!

I admit that this may be slightly confusing to the end user, but I would ask: if we made the above error, what would the invocation look like if I actually wanted to pass `--two` as the value to `--one`? Given the tradeoffs I think the current approach outweighs the negatives, but I'm definitely open to other opinions.

FWIW the current flag parsing behavior is consistent with some other commandline tools I spot checked (specifically `git` and `grep`).

Thanks for starting this conversation!

**Comment by GrantSeltzer** [comment]
Just ran into this same behavior. Perhaps a check to see if arguments passed to flags, are themselves, other flag options and error out if so is the solution, but I think leaving the design on the actual project using cli makes more sense.

**Comment by jszwedko** [comment]
That is a good point, if this is desired behavior it is something that could be could be done by building a list of flags and checking if any of the arguments to other flags match a defined flag with something like:

```golang
for _, flag := cmd.Flags {
  parts := strings.Split(longName, ",")
  for _, name := range parts {
    names = append(names, strings.Trim(name, " "))
  }
}

# iterate over passed values and check if any are in `names`
```

**Comment by lynncyrin** [comment]
Given that this is from last year, I think I'm comfortable closing it 🙂 feel free to re-open / open a new issue / comment in support if there's still interest here!
