### ISSUE TITLE
Vanity url gopkg.in/urfave/cli.v1 doesn't map to v1 branch

### ISSUE THREAD

**Issue by rmg** [urfave/cli#513]
I'm not sure if it is intentional or an oversight, but the README.md says gopkg.in/urfave/cli.v1 points to the v1 branch, but it actually points to the latest v1.x tag because of how gopkg.in works.

If the intention is for it to point to the latest tag, then the README.md should probably be updated to say that it points at the latest 1.x tag, which may or may not be the latest code on the v1 branch.

If the intention is for this to point to the HEAD of the v1 branch then all the 1.x tags would have to be deleted, which isn't really an option.. so this approach just isn't supported to gopkg.in :-(

Of course since I discovered this little quirk while trying to make use of #496, what I'm really looking for is a new 1.x release? 😄

**Comment by meatballhat** [comment]
I agree that the wording in the `README.md` about `gopkg.in/urfave/cli.v1` is incorrect.  Are you willing to submit a PR? 😸

**Comment by rmg** [comment]
@meatballhat I'll try to remember to, but no promises (Go is part of my evening/weekend life so a typo-PR might slip through the cracks).

**Comment by jszwedko** [comment]
@rmg opened #521 to update the wording -- let me know if this makes sense to you. I'll also tag a new release :smile:

**Comment by rmg** [comment]
@meatballhat @jszwedko thanks for rewording.

[Belated] LGTM :ship it:
