### ISSUE TITLE
c.IsSet returns true for empty env vars

### ISSUE THREAD

**Issue by vikstrous** [urfave/cli#517]
I want to be able to differentiate between empty env vars and unset env vars, but they are treated the same right now:

```
package main

import (
    "fmt"
    "os"

    "github.com/urfave/cli"
)

func main() {
    app := cli.NewApp()
    app.Name = "boom"
    app.Usage = "make an explosive entrance"
    app.Flags = []cli.Flag{
        cli.StringFlag{
            Name:   "thing",
            EnvVar: "THING",
        },
    }
    app.Action = func(c *cli.Context) error {
        fmt.Printf("isset: %t\n", c.IsSet("thing"))
        return nil
    }
    os.Setenv("THING", "")
    //os.Setenv("THING", "set")

    app.Run(os.Args)
}
```

This prints

```
isset: false
```

If you uncomment the commented out line it prints:

```
isset: true
```

I need both cases to be treated as set. Right now I have some ugly workarounds to do this.

**Comment by jszwedko** [comment]
Hi @vikstrous,

Thank you for bringing this up. I've gone back and forth on how to treat empty env vars, but I think I agree with you that they should be treated as set and override any defaults defined on the flag. I could see applications depending on this behavior, but given that `IsSet` only actually worked with env vars (#502) as of this past month (and hasn't been officially released), I'm OK with modifying it.
