### ISSUE TITLE
BUG: cli.v1/altsrc

### ISSUE THREAD

**Issue by dixonwille** [urfave/cli#518]
The import statement in `altsrc` on the latest `v1` tag is pointing to the master branch `github.com/urfave/cli` not `gopkg.in/urfave/cli.v1`

**Comment by jszwedko** [comment]
This is a duplicate of #505 (and fixed by #512) and will be included in the next release. Please let me know if this doesn't address your concerns.

Thanks!

**Comment by dixonwille** [comment]
Thanks didn't realize they had the same issue on V2?
