### ISSUE TITLE
Add a way to pass variables from app.Before to an Action

### ISSUE THREAD

**Issue by joshdekock** [urfave/cli#520]
Maybe this is a design issue on my part, but I do some checks in the app.Before (which all the subcommands would require to pass), and I also set some variables based on these checks. Currently I'm using global variables to pass these to the action, but I don't think this is a very good solution. The other way I thought was to call the check function at the start of every single subcommand/command action, but this seems like a lot of potentially unnecessary code duplication. A way to set variables in the context so that you can pass things from app.Before to the action without global variables would be very helpful. (Maybe this is already possible, I just couldn't see how it would be able to be done).

**Comment by jszwedko** [comment]
Hi @joshdekock,

It isn't terribly well documented, but `App.Metadata` can be used for this (https://godoc.org/github.com/urfave/cli#App). Let me know if you this satisfies your use cases.

Cheers!

**Comment by joshdekock** [comment]
This looks like it'd work, thanks!
