### ISSUE TITLE
Don't want any commands in the CLI interface (including help)

### ISSUE THREAD

**Issue by nthnca** [urfave/cli#523]
Is it possible to use cli for tools without subcommands?

Currently the help always prints out something like this in the usage:
scratch [global options] command [command options] [arguments...]

Is there anyway to get rid of the help command and have it print something more like:
scratch [global options] [arguments...]

It appears if I set "app.HideHelp = true" it gets close to what I want but I would still like to keep the global options of -h, --help.

**Comment by nthnca** [comment]
So I have figured out how to get close to what I want:

        app.HideHelp = true                                                     
        app.Flags = []cli.Flag{                                                 
                cli.BoolFlag{Name: "help, h", Usage: "show help"},              
        }                                                                       
                                                                                
        app.Action = func(c *cli.Context) error {                               
                if c.Bool("help") {                                             
                        cli.ShowAppHelp(c)                                      
                        return nil                                              
                }                                                               
                fmt.Println("Hello!")                                           
                return nil                                                      
        } 

There are just two problems:
1. The help output still uses the wording "Global Options".
2. It feels like this is a lot of code for what is for many simple tools should be the default behavior.

Solutions (I am happy to write the code if these are wanted behaviors)
1. The help output should only use the word "Options" if there are no subcommands defined.
2. I would suggest that the "help" command should not be added unless there are user defined commands.

**Comment by npcode** [comment]
My workaround is calling `app.Setup()` and empty `app.Commands` before calling `app.Run()`. e.g.
```
app.Setup()
app.Commands = []cli.String{}
if err := app.Run(os.Args); err != nil {
    fmt.Fprintf(os.Stderr, "%+v\n", err)
    os.Exit(1)
}
```

**Comment by jszwedko** [comment]
@nthnca I agree (apologies for the delay in triaging this!).

I'm definitely happy to review PRs augmenting this behavior. For the current version, I think we could probably introduce another property for controlling this to keep compatibility, but, in the `v2` branch, I could see us doing something more drastic like not automatically adding the `help` subcommand or `-h` flag, but instead just provide them as package level variables (they are currently private) and let the user add them when initializing the `App` struct.

**Comment by sorsasampo** [comment]
Any update on this? Not having any commands at all seems like a really popular usecase.

**Comment by twlz0ne** [comment]
Just set [CustomAppHelpTemplate](https://github.com/urfave/cli/blob/8e01ec4cd3e2d84ab2fe90d8210528ffbb06d8ff/help.go#L139):
```go
app.CustomAppHelpTemplate = `NAME:
   {{.Name}}{{if .Usage}} - {{.Usage}}{{end}}
USAGE:
   {{if .UsageText}}{{.UsageText}}{{else}}{{.HelpName}} {{if .VisibleFlags}}[global options]{{end}}{{if .Commands}} command [command options]{{end}} {{if .ArgsUsage}}{{.ArgsUsage}}{{else}}[arguments...]{{end}}{{end}}{{if .Version}}{{if not .HideVersion}}
VERSION:
   {{.Version}}{{end}}{{end}}{{if .Description}}
DESCRIPTION:
   {{.Description}}{{end}}{{if len .Authors}}
AUTHOR{{with $length := len .Authors}}{{if ne 1 $length}}S{{end}}{{end}}:
   {{range $index, $author := .Authors}}{{if $index}}
   {{end}}{{$author}}{{end}}{{end}}{{if .VisibleCommands}}
OPTIONS:
   {{range $index, $option := .VisibleFlags}}{{if $index}}
   {{end}}{{$option}}{{end}}{{end}}{{if .Copyright}}
COPYRIGHT:
   {{.Copyright}}{{end}}`
```

**Comment by twlz0ne** [comment]
Just set the [CustomAppHelpTemplate](https://github.com/urfave/cli/blob/8e01ec4cd3e2d84ab2fe90d8210528ffbb06d8ff/help.go#L139):
```go
app.CustomAppHelpTemplate = `NAME:
   {{.Name}}{{if .Usage}} - {{.Usage}}{{end}}
USAGE:
   {{if .UsageText}}{{.UsageText}}{{else}}{{.HelpName}} {{if .VisibleFlags}}[global options]{{end}}{{if .Commands}} command [command options]{{end}} {{if .ArgsUsage}}{{.ArgsUsage}}{{else}}[arguments...]{{end}}{{end}}{{if .Version}}{{if not .HideVersion}}
VERSION:
   {{.Version}}{{end}}{{end}}{{if .Description}}
DESCRIPTION:
   {{.Description}}{{end}}{{if len .Authors}}
AUTHOR{{with $length := len .Authors}}{{if ne 1 $length}}S{{end}}{{end}}:
   {{range $index, $author := .Authors}}{{if $index}}
   {{end}}{{$author}}{{end}}{{end}}{{if .VisibleCommands}}
OPTIONS:
   {{range $index, $option := .VisibleFlags}}{{if $index}}
   {{end}}{{$option}}{{end}}{{end}}{{if .Copyright}}
COPYRIGHT:
   {{.Copyright}}{{end}}`
```

**Comment by AkihiroSuda** [comment]
no stale

**Comment by lynncyrin** [comment]
Glancing over the issue, it looks like it's waiting for someone to put a proposal together? Anyone is free to take point on that!

**Comment by AkihiroSuda** [comment]
PR: https://github.com/urfave/cli/pull/1083
