### ISSUE TITLE
Version behavior is inconsistent

### ISSUE THREAD

**Issue by nthnca** [urfave/cli#524]
In https://github.com/urfave/cli/issues/248 there was a change made so if a user empties the app.Version then the version is not printed as part of the help output.

This has left the -v, --version flags though which then creates the somewhat strange output of "app version" with no version number.

I would really prefer that the Version string is not initialized at all in cli.NewApp and then if the app.Version string is empty set `HideVersion = true`

**Comment by jszwedko** [comment]
I agree, thank you for bringing this up (I somehow missed this fact being pointed out in the comments in #248).

**Comment by lynncyrin** [comment]
Un-assigning this since >1 month has passed without any movement

Anyone else is now free to work on this!

**Comment by lynncyrin** [comment]
Resolved via https://github.com/urfave/cli/pull/954 and https://github.com/urfave/cli/pull/955
