### ISSUE TITLE
A sort of readline implementation ?

### ISSUE THREAD

**Issue by LeaklessGfy** [urfave/cli#525]
Hello,

I'm working on a sort of command line interface for a program and was wondering if there's a sort of infinite loop to stay in program (like readline offer or the implementation of CMD in python).

Because for now I just succeed to launch the go app with arguments but when function is finished I return back to the shell and the program shut. What I would like is to stay in a sort readline program.

Do you provide this ? Thanks

**Comment by jszwedko** [comment]
Hi @LeaklessGfy,

It isn't natively supported by the library, but you can compose it pretty easily in a manner similar to https://github.com/codegangsta/hip/blob/master/hip.go#L64-L78 -- see #220 and #44 for further discussion. Let me know if this helps!

**Comment by LeaklessGfy** [comment]
Hi @jszwedko ,

With a bit of searching and hacking aroung (without even look at your post) I succeed in making it and work pretty well ! Your example will help me to probably make a better code.

Thanks for your time ! :)

**Comment by jszwedko** [comment]
Awesome, I'm glad this helped, @LeaklessGfy
