### ISSUE TITLE
Default value on Flag ?

### ISSUE THREAD

**Issue by LeaklessGfy** [urfave/cli#532]
Hello, ... it's me again 
:D 
Was wondering if there's a method to get Default value on Flag (define it). I noticed that on IntFlag there's the (default : 0) that show up. Is it possible to do the same thing with StringFlag for example ?

Thank you ! Have a good day

**Comment by chazzly** [comment]
Yes, set "Value" within the definition:

`
cli.StringFlag{Name: "file, f", Value: "default.txt", Usage: "The file you want."},
cli.StringFlag{Name: "repository, r", Value: "https://github.com/urfave/cli", Usage: "Your Repository"},
`

**Comment by jszwedko** [comment]
Hi @LeaklessGfy,

As @chazzly notes, if you set `Value` that will be the default.

It looks as though if the default value is `""` this `(default: )` is suppressed though I can't see a great reason for that (and am inclined to change it to output `(default: "")`. Do you have thoughts @meatballhat? The commit that line points to is some refactoring you did with moving around way the defaults are displayed.

**Comment by lynncyrin** [comment]
Given that this is from last year, I think I'm comfortable closing it 🙂 feel free to re-open / open a new issue / comment in support if there's still interest here!
