### ISSUE TITLE
Stop the cli from interpreting flag

### ISSUE THREAD

**Issue by LeaklessGfy** [urfave/cli#537]
Hello Guys !

I was wondering if it's possible to stop the cli from interpreting flag or characters. 

Use case:
I use the cli with readline. I have a command with the name "sys" when user type = `sys {smth}`
The command will start a local command with exec.Command. Example : `sys ls` will simply make a ls and display the result.

Now I want to be able to put : `sys ls -l` for example. But the cli is telling me it's not possible. Is there a way to stop this behavior and let the action execute ? I also try to find out if in before function there was a way to bypass this behavior by getting the full command as a string ... Without success.

Thanks again !

**Comment by jszwedko** [comment]
Hi @LeaklessGfy,

You can use `SkipFlagParsing` for this behavior if the command doesn't itself take any flags, otherwise you can use the recently added, but unreleased, `SkipArgReorder` (https://github.com/urfave/cli/pull/528). Let me know if this helps!

**Comment by lynncyrin** [comment]
Given that this is from last year, I think I'm comfortable closing it 🙂 feel free to re-open / open a new issue / comment in support if there's still interest here!
