### ISSUE TITLE
Why is codegangsta/cli urfave/cli now?

### ISSUE THREAD

**Issue by iamthemuffinman** [urfave/cli#539]
Just curious as I can't find information on it anywhere.

**Comment by jszwedko** [comment]
Hi @iamthemuffinman!

We took over maintainership from Jeremy and, rather than bugging him every time we needed to take administrative action on the repository, it made more sense to move it to a separate org. I'm sure he's happy to have less notifications too :smile:

Let me know if this answers!

**Comment by iamthemuffinman** [comment]
Hi @jszwedko!

Good enough for me. Thanks! He seems pretty inactive this year looking at his Github Activity...
