### ISSUE TITLE
v2 branch status

### ISSUE THREAD

**Issue by nlewo** [urfave/cli#552]
It seems some fix/features in the v1 branch are not merged in the v2 branch which is then diverging. 
Do you have a status or a plan regarding the switch to the v2 branch?

I can help a bit in this process if required. 
Thx

**Comment by jszwedko** [comment]
Hi @nlewo,

The merge up has been mostly adhoc and as-needed, but you are correct that it is a bit stale -- I'll merge up now.

As for the `v2` release -- I think it is pretty close; there was only one other major change I wanted to get in (which had previously just existed in my head, but now exists as https://github.com/urfave/cli/issues/554). I'll do another survey to make sure there isn't anything else we can clean up for this initial backwards incompatible release (further ideas welcome!).

Thank you for your continued interest in the project!

**Comment by jszwedko** [comment]
#555 is the merge up

**Comment by nlewo** [comment]
@jszwedko ok, cool. Thanks for the status;)

**Comment by jszwedko** [comment]
:+1: I'll close this this out, but feel free to open new issues of this sort in the future!
