### ISSUE TITLE
App.Action being called when nil or subcommands exist

### ISSUE THREAD

**Issue by vivace-io** [urfave/cli#562]
The documentation for `App.Action` ([found here](https://github.com/urfave/cli/blob/master/app.go#L63)) notes that it is called only if no sub-commands exist. This is under the assumption that the term subcommand applies to commands attached to `App.Commands`.

However, when setting up an app with subcommands but leaving `App.Action` unset, App.Action is still being called on `App.Run` and results in a panic runtime error.

I do understand that creating a new app by calling `NewApp()` resolves this issue, but maybe the maintainers might consider putting a check around [the offending line](https://github.com/urfave/cli/blob/master/app.go#L245)? Even if it just plops back in the default action `helpCommand.Action` if `App.Action` is nil.

I do apologize if this seems a tad bit frivolous for an issue. I just came across it earlier and thought I might bring it to someone's attention if it was unintended.

**Comment by jszwedko** [comment]
Hi @vivace-io,

Thanks for the report! I've created #563 to address this.

**Comment by jszwedko** [comment]
Merged early since I'm cutting a release, but please let me know if this doesn't address your issue!

**Comment by vivace-io** [comment]
Perfect! Thank you so much. I know it was a tiny fix and basically a matter of package convention, but I appreciate the quick turn around!
