### ISSUE TITLE
GitCommit hash

### ISSUE THREAD

**Issue by gedw99** [urfave/cli#572]
I can see the buildtime param, but nothing for gitCommit hash.

Here is an example from jiri:
https://fuchsia.googlesource.com/jiri/+/master/version/version.go

When a build occurs in CI, its importart the githash is altered

**Comment by jszwedko** [comment]
@gedw99 I'm not sure I completely follow, `urfave/cli` does allow automated display of the version via `--version` (and in the `--help`) output, but it is up to the developer to set `.Version` on the `cli.App` instance.

**Comment by gedw99** [comment]
I am just suggesting a githash is useful.

**Comment by meatballhat** [comment]
@gedw99 Can you set `cli.VersionPrinter` to do what you need?  [This is what I usually to do](https://github.com/travis-ci/worker/blob/0e3fae54188d343418d3be346ac65d2520d17994/version.go#L24-L34), fwiw.

**Comment by gedw99** [comment]
yep i can. too true.

**Comment by gedw99** [comment]
thansk all. got it
