### ISSUE TITLE
Flags could use explicit UsageValue field

### ISSUE THREAD

**Issue by theory** [urfave/cli#574]
Sometimes, the text I want to see in the example usage is not text I want included in the usage. For example:

		&cli.UintFlag{
			Name:        "sid",
			Aliases:     []string{"s"},
			Value:       0,
			Usage:       "Requesting `subscriber ID`: Required for password auth",
		},

This configuration yields:

    --iss subscriber ID, -i subscriber ID  Requesting subscriber ID: Required for password auth (default: 0)

Which is too long. I'd love to tell it to use a different value in the usage statement. If it was called UsageValue, it might be configured like this:

		&cli.UintFlag{
			Name:        "sid",
			Aliases:     []string{"s"},
			Value:       0,
			Usage:       "Requesting subscriber ID: Required for password auth",
			UsageValue: "subid",
		},

And then the output would be:

    --iss subid, -i subid  Requesting subscriber ID: Required for password auth (default: 0)

Which is much shorter, even though "subid" is not a string I'd want to appear in the usage statement part.

**Comment by jszwedko** [comment]
:+1: seems like a reasonable use case

**Comment by lynncyrin** [comment]
Given that this is from last year, I think I'm comfortable closing it 🙂 feel free to re-open / open a new issue / comment in support if there's still interest here!
