### ISSUE TITLE
does it support optional flag?

### ISSUE THREAD

**Issue by etsangsplk** [urfave/cli#576]
There are some options that are not always required, and if not required, a builtin default value is set.
fro example when --optionalflag is not entered
the effect of 
somecommand --required 1223 
is the same as if entered
somecommand --requiredflag 1223 --optionalflag default345 

The documentation is not clear wheterh this is supported or not and if so, how that be used.

**Comment by jszwedko** [comment]
Hi @etsangsplk,

Required flags are not currently supported, they are all optional and have defaults (the `Value` field on the structs).

Let me know if this helps!

**Comment by shadiakiki1986** [comment]
For my optional flags, I just set it to an empty string by default, and check if the string is not empty to check if the optional flag is set

**Comment by jszwedko** [comment]
Indeed, going to close this in lieu of https://github.com/urfave/cli/issues/85 -- put please reopen if I misunderstood you @etsangsplk

**Comment by lynncyrin** [comment]
Given that this is from last year, I think I'm comfortable closing it 🙂 feel free to re-open / open a new issue / comment in support if there's still interest here!
