### ISSUE TITLE
Make %+v formatting of ErrorFormatter optional

### ISSUE THREAD

**Issue by cyphar** [urfave/cli#578]
Not all users want, by default, to have their `pkg/error` errors' stack traces printed. This should be handled by a `--debug` flag or `Debug` option in the App, so that you only get a stack trace if the user actually asked for one.

**Comment by jszwedko** [comment]
:+1: I can definitely see that argument, apologies for not conceiving of it when reviewing #560.

I'll mark this as a bug.

**Comment by lynncyrin** [comment]
Given that this is from last year, I think I'm comfortable closing it 🙂 feel free to re-open / open a new issue / comment in support if there's still interest here!
