### ISSUE TITLE
Suggestion: Provide Compiled Go Version in Help

### ISSUE THREAD

**Issue by sethgrid** [urfave/cli#579]
Suggestion that I've found valuable in my apps: provide the version of Go used to compile. Ex:

```
$ greet help
NAME:
    greet - fight the loneliness!

USAGE:
    greet [global options] command [command options] [arguments...]

VERSION:
    0.0.0 (Go1.7)

COMMANDS:
    help, h  Shows a list of commands or help for one command

GLOBAL OPTIONS
    --version Shows version information
```

(or as a new line).

**Comment by jszwedko** [comment]
@sethgrid the version string is free text so you could set it to include the Go version if desired with something like:

`app.Version = fmt.Sprintf("0.0.0 (%s)", runtime.Version())`

Let me know if that helps!

**Comment by sethgrid** [comment]
Good point; and, yeah, I can do that for sure. I was thinking it would be a
good standard to adopt. Cheers!

**Comment by jszwedko** [comment]
:+1:

I hesitate to make it the default since the end-users of most tools aren't concerned with the version of the language it was built with, but I definitely think it could be a good pattern for certain applications.

Closing this out, but please feel free to re-open if you disagree.
