### ISSUE TITLE
trying to populate stringslice from yaml or toml failed.

### ISSUE THREAD

**Issue by demoze** [urfave/cli#580]
I'am trying to load configuration from yaml or toml. It 's work very well except for StringSlice.
Could someone help me to catch the issue ?

here is e very simple sample app to test

I'have tried many format for the list, with no succes :-(

```
# example config file 

test : 200

names: 
  - one
  - two

```

```
package main

import (
  "fmt"
  "os"


  "gopkg.in/urfave/cli.v1"
  "gopkg.in/urfave/cli.v1/altsrc"

)


func main() {
  app := cli.NewApp()

  flags := []cli.Flag{
    altsrc.NewIntFlag(cli.IntFlag{Name: "test"}),
    altsrc.NewStringSliceFlag(cli.StringSliceFlag{
      Name: "names",
    }),

    cli.StringFlag{Name: "load"},
  }

  app.Action = func(c *cli.Context) error {
    fmt.Println("yaml ist rad")
    fmt.Printf("test:%d\n", c.Int("test"))

    //dump_config(c)
    return nil
  }

  app.Before = altsrc.InitInputSourceWithContext(flags, altsrc.NewYamlSourceFromFlagFunc("load"))
  app.Flags = flags

  app.Run(os.Args)
}
```

**Comment by jszwedko** [comment]
Definitely a bug, thank you for the report @demoze 

I believe https://github.com/urfave/cli/pull/582 addresses this, please give it a shot and let me know if it doesn't work (I did test your basic use case here).

**Comment by demoze** [comment]
Thank for the fix,   #582 appears to fix slice input.

However, this only works for  yml, not for toml. 



```
#load.toml
test = 200
names = [ 
  "one",
  "two"
]
```

```
#load.yml
test : 200
names: 
  - one
  - two
```


package main

import (
  "fmt"
  "os"


  "gopkg.in/urfave/cli.v1"
  "gopkg.in/urfave/cli.v1/altsrc"
)


func main() {
  app := cli.NewApp()

  flags := []cli.Flag{
    altsrc.NewIntFlag(cli.IntFlag{Name: "test"}),
    altsrc.NewStringSliceFlag(cli.StringSliceFlag{
      Name: "names",
    }),
    cli.StringFlag{
        Name: "loadyml",
        Value: "load.yml",
    },
    cli.StringFlag{
        Name: "loadtoml",
        Value: "load.toml",
    },

  }

  app.Action = func(c *cli.Context) error {
    fmt.Printf("test:%d\n", c.Int("test"))

    for _, name := range c.StringSlice("names") {
     fmt.Printf("name:%s\n", name)
    }

    return nil
  }

  app.Before = altsrc.InitInputSourceWithContext(flags, altsrc.NewYamlSourceFromFlagFunc("loadyml"))
  app.Flags = flags

  app.Run(os.Args)


  app.Before = altsrc.InitInputSourceWithContext(flags, altsrc.NewTomlSourceFromFlagFunc("loadtoml"))
  app.Flags = flags

  app.Run(os.Args)

}


```
go build tests.go
@:~/gmrpropre$ ./tests 
test:200
name:one
name:two
Unable to create input source with context: inner error: 
'Unable to load TOML file 'load.toml': inner error: 
'Unsupported: type = 0x17''

NAME:
   tests - A new cli application
   ...

Unable to create input source with context: inner error: 
'Unable to load TOML file 'load.toml': inner error: 
'Unsupported: type = 0x17''

```

**Comment by jszwedko** [comment]
Turned out to not be too bad via https://github.com/urfave/cli/pull/582/commits/e87dfbb6bb85250206841a9576e51b1323910356. Let me know if that doesn't work for you.

**Comment by demoze** [comment]
Sorry for this delay, (very long holiday) thank for the fix, it;s works for me.
