### ISSUE TITLE
Newbie question to cli

### ISSUE THREAD

**Issue by phreddrick** [urfave/cli#584]
Is there a way to specify a set of allowed strings on a string flag?

**Comment by jszwedko** [comment]
Hi @phreddrick,

You can accomplish this a couple of ways:

* Check the value in a `Before` function
* Define a new `GenericFlag` type whose `.Set()` method validates the value and returns an error if it isn't one part of your set

If either of those is unclear and I'm happy to put together an example or two.

Hope this helps!

**Comment by phreddrick** [comment]
Before works quite well! Thanks!
