### ISSUE TITLE
How to parse a complicated command line, like an array of multi items.

### ISSUE THREAD

**Issue by fanux** [urfave/cli#588]
I want to get  parameters from command line to set an array like this:

```
type Item struct {
      Env []string                                   // using flag -e
      Labels map[string]string             // using flag -l
}

items := new([]Item)
```

Which is a better way to fill my array?

My app need handle multiple items,  if only one item, it is simple:
```
$ app -e key=value -e key2=value2 -l foo=bar
```

But I don't know how to handle multiple items because Env and Labels must not deranged

**Comment by jszwedko** [comment]
Hi @fanux,

I'd also suggest using `GenericFlag` to create your own key/value flag that could wrap a `map[string]string` to do the validation and build the map. E.g. something like:

```golang
type KeyValueFlag struct{
  m map[string]string
}

func (k *KeyValueFlag) Set(value string) error {
  if k.m == nil {
    k.m = make(map[string]string
  }
  parts := strings.SplitN(value, "=", 1)
  // TODO error handling if there is no `=`
  k.m[parts[0]] = parts[1]
  return nil
}

...


app.Flags = []cli.Flag{cli.GenericFlag{Name: "env, e", Value: &KeyValueFlag{}},}
```

(note that I didn't test the above, but it should get you on the right path)

Let me know if this helps!

**Comment by fanux** [comment]
My config file is like this:
```
{
  "Items": [
      {
         "Filters": ["service==online"],
         "Number": 3,
         "ENVs": ["constraint:storage==ssd", "affinity:app!=offline"],
         "Labels": {
            "app":"scale-up-nginx",
         }
      },
      {
         "Filters": ["service==offline"],
         "Number": -3,
         "ENVs": ["constraint:storage==ssd", "STOP_HOOK="www.iflytek.com/stop""],
         "Labels": {
            "app":"scale-down-nginx",
         }
      }
  ]
}
```

I also want to provide a command line tool to receive parameters.

One item the command line like this:
```
$ cattle scale -e key=value -l foo=bar -f service==online -n 5      
```

How to design a multiple command line, like this?

```
$ cattle scale -e key=value -l foo=bar -f service==online -n 5 scale -e key1=value1 -l foo1=bar1 -f service==offline -n -5 
```

PS : [My project](https://github.com/fanux/cattle#scale-up-or-down)  a fork of swarm with scale.

**Comment by jszwedko** [comment]
Hi @fanux,

What I described above should allow you to achieve the parsing of those key/value flags. Unfortunately this library doesn't support multiple command invocations during the same execution. You could probably workaround that by doing some up front parsing of the command line to break up each subcommand invocation and pass those to `app.Run()` individually.

**Comment by fanux** [comment]
Okay, thank you, I got it.
