### ISSUE TITLE
cli.ShowCommandHelp() has no effect when called from a non terminal command

### ISSUE THREAD

**Issue by vadmeste** [urfave/cli#590]
Hello,

I wonder if it is correct to have this behavior in the cli package: `cli.ShowCommandHelp()` doesn't work when called in `admin` command's action. Notice that `admin` has a subcommand called `service`.

```
package main

import (
        "os"

        "github.com/urfave/cli"
)

func main() {

        adminServiceCmd := cli.Command{
                Name: "service",
                Action: func(c *cli.Context) {
                        cli.ShowCommandHelp(c, "service") // it works
                },
        }

        adminCmd := cli.Command{
                Name:        "admin",
                Subcommands: []cli.Command{adminServiceCmd},
                Action: func(c *cli.Context) {
                        cli.ShowCommandHelp(c, "admin") // it doesn't work
                },
        }

        app := cli.NewApp()
        app.Name = "lookup"
        app.Commands = []cli.Command{adminCmd}

        app.Run(os.Args)
}
```

Output:

```
$ ./a.out admin service
NAME:
   lookup admin service - 

USAGE:
   lookup admin service [arguments...]
$ ./a.out admin
.. (nothing) ..
$
```

Best regards,

**Comment by jszwedko** [comment]
Hi @vadmeste, the documentation doesn't quite make this clear, but if you want to print the help for the command you are currently in the context of, you can actually use `cli.ShowCommandHelp(c, "")`. In subcommands, you actually want to use `cli.ShowSubcommandHelp`. I realize this difference in interface is quite confusing so will tag this as something to correct in the `v2` branch where we are prepping backwards incompatible changes for version 2.

Please let me know if this helps!

**Comment by lynncyrin** [comment]
Given that this is from last year, I think I'm comfortable closing it 🙂 feel free to re-open / open a new issue / comment in support if there's still interest here!
