### ISSUE TITLE
App shouldn't exit if error doesn't implement ExitCoder

### ISSUE THREAD

**Issue by awsmsrc** [urfave/cli#594]
## Current behavior:

Even if the error returned doesn't implement ExitCoder the app exits with an exit status of 1

- introduced here: https://github.com/urfave/cli/commit/e9688813
- further info here: https://github.com/urfave/cli/issues/565

## Expected behavior 

the app will return the error but not exit so it can be introspected as follows

``` 
err := app.Run()
if err != nil {
  if err.IsInterestingToMe() {
    reportInterestingData()
  } else {
    exit(1)
  }
}
```

## Usecase
if the users token has expired, prompt for a email/password, generate a new token and re run the command

## Alternative option 
Allow for a custom HandleExitCoder to be specified

**Comment by awsmsrc** [comment]
Happy to help with whatever implementation is decided here, if it can help get things moving :)

**Comment by jszwedko** [comment]
@awsmsrc :+1: thanks for filing this -- it reminded me to take a deeper dive into #565 and I came to the same conclusion you did. #595 adjusts this behavior to only exit for `ExitCoder`s.

**Comment by kklipsch** [comment]
So #595 has the effect of ignoring errors coming out of the action function unless they meet the ExitCoder interface? That seems weird and wrong.  Why not change the action function to explicitly require an ExitCoder?

**Comment by jszwedko** [comment]
@kklipsch it doesn't ignore the errors, rather it propagates them up to the `App.Run()` method so that the caller can decide what to do. You can use `App.RunAndExitOnError` as a convenience to exit with a code of `1` if desired.

Closing this since #595 has been merged in.
