### ISSUE TITLE
Enum Support

### ISSUE THREAD

**Issue by coen-hyde** [urfave/cli#602]
Option values often only support a limited set of valid values. It would be helpful to have CLI enforce valid options and auto generate help docs listing valid options.

**Comment by jszwedko** [comment]
:+1: this is possible via the `GenericFlag`, but I'll mark this as a possible enhancement.

Thanks!

**Comment by BlueBeN82** [comment]
+1

**Comment by maheshvra** [comment]
+1

**Comment by doronbehar** [comment]
I'd still like to see this dear bot.

**Comment by dearchap** [comment]
Duplicate of #786 . Enum is a special case of flag validation in that the input is restricted to a certain set of strings.
