### ISSUE TITLE
Passing glob arguments

### ISSUE THREAD

**Issue by DrGo** [urfave/cli#606]
Hope this is the right place to ask this question,
I cannot figure out how to receive a file name argument that could have a pattern eg myfolder/*

Thanks

**Comment by jszwedko** [comment]
Hi @DrGo,

The shell (for example `bash`) will do the expansion before you even see the arguments. E.g. if someone typed `myfolder/*` as the argument you might see arguments like `myfolder/1.txt myfolder/2.txt myfolder/3.txt`. They could quote the argument to avoid the expansion at which point you could use https://golang.org/pkg/path/filepath/#Glob to do the expansion yourself.

Let me know if this helps!

**Comment by DrGo** [comment]
Thanks Jesse,
This makes sense, 
Out of laziness I was hoping that Cli will have a flag type (fileNameSlice) that takes care of retrieving the list for me :) 
Cheers,
Salah

**Comment by jszwedko** [comment]
No worries! I'm happy to review a PR adding a flag type like that, but I think most programs rely on the shell to do expansion.

**Comment by DrGo** [comment]
I agree, Jesse,
I have another question for you, 
What is the best way to validate the global arguments and exit with a specific message re any invalid arguments?
I tried an app.before func but returning non nil error prints the entire usage message!
I know I could set a valid flag and exit if it is false but I will have to do this in all actions. I am sure there is a better way, just I can't find it.

Thanks

**Comment by lynncyrin** [comment]
Given that this is from last year, I think I'm comfortable closing it 🙂 feel free to re-open / open a new issue / comment in support if there's still interest here!
