### ISSUE TITLE
Thank You!

### ISSUE THREAD

**Issue by themccallister** [urfave/cli#607]
I know you might not hear this enough, but I really wanted to say thank you for releasing and maintaining this package. This has been an incredibly helpful tool to build my side project on. Plus you clearly spent a lot of time on the documentation...

So again, thank you very much! If we ever meet, I owe you a coffee/beer - whatever your poison.

💯

**Comment by jszwedko** [comment]
Thank you @themccallister et. al.!

We, maintainers, definitely appreciate hearing positive feedback.
