### ISSUE TITLE
Does it support POSIX-style short flag combining?

### ISSUE THREAD

**Issue by chensongz** [urfave/cli#617]
I want to use flag `-lh` for `-l` `-h`.
How to support this?

**Comment by SCKelemen** [comment]
I don't think this can be compatible. The aliases are just a collection of strings. There is no requirement that they be one character in length. Therefore, it seems like there would be considerable overhead and searching arguments, and parsing them into valid flags.

**Comment by jszwedko** [comment]
This was added as optional behavior in #684 -- thanks for raising the issue @chensongz !
