### ISSUE TITLE
Slice Flags help output is unexpected/confusing

### ISSUE THREAD

**Issue by cab** [urfave/cli#62]
Using a flag such as 

```
cli.StringSliceFlag{"lang", &cli.StringSlice{"english", "spanish"}, "language for the greeting"},
```

results in help output like this:

```
OPTIONS:
   --lang [english spanish] `-lang option -lang option` language for the greeting
```

What exactly is the intended meaning of "`-lang option -lang option`"? Am I just uninformed or is this a WIP? I'd be happy to work on it if I know what it's supposed to do! :)

**Comment by jszwedko** [comment]
@vieux agreed, but how would you also display the short name there (in non-slice types it has `--lang, l 'english'`, but something like `--lang, -l english, --lang, -l spanish    language for the greeting` looks weird). I guess this would be solved by specifying the defaults after the usage (or allowing the user to template in the defaults like in Python's `optparse`), but I'm not sure if that would be breaking the API of this library.

**Comment by meatballhat** [comment]
The help output for slice types has been changed (significantly?) since this issue was last updated, and I don't think it's relevant anymore.  Please yell if you disagree!

**Comment by porjo** [comment]
Current help output for slice flags is not intuitive. It does not provide any hint that the flag should be specified multiple times. For example, the following is a slice flag
```
   --domains value, -d value   Add domains to the process
```
...how will the user know that they should include this multiple times if they want to pass in multiple domains!? A naive user might attempt to put all the domains together e.g. `--domains example1.com example2.com`

This form makes more sense to me:
```
  --domains, -d [--domains option --domains option]            Add domains to the process
```

**Comment by jszwedko** [comment]
Agreed, reopening

**Comment by RafPe** [comment]
I will jump to the discussion and say that I would agree with @jefferai something like 
```
--items=1.2.3.4/32,2.3.4.5/32
```
or ... 
```
--items="1.2.3.4/32 2.3.4.5/32"
```
Would make more sense in my use case scenarios.

**Comment by lynncyrin** [comment]
\\\ bump ^^ I think there's definitely something we could do here

**Comment by dearchap** [comment]
Fixed and merged. https://github.com/urfave/cli/commit/b80ff3d32f03cb2d992f1e28f7ddb0881de40460
