### ISSUE TITLE
limit possible values for parameters + required vs optional parameters

### ISSUE THREAD

**Issue by jeroenjacobs79** [urfave/cli#620]
Hi,

I'm going to be honest, I'm a newbie at Go development and I mostly used Python + its argparse module for my commandline tools.

I've been going through the documentation, but I'm struggling with a few concepts:

- How can I limit a certain commandline parameter to certain values? Eg: I have a commandline parameter "--type" which can only accept the following values: picture,sound or video. so "--type=video" would be valid, but "--type=program" will not. Is there a way to specify these constraints? Python's argparse module can solve this with the "choices" option.

- How can I dictate a certain commandline should always be specified? Eg: "--type" should always be specified, with a value.

**Comment by jszwedko** [comment]
Hi @jeroenjacobs1205!

* Restricting flag options is not directly supported by this library currently, but is achievable via the exposed `GenericFlag` interface (declaring a struct implementing the `GenericFlag` interface that validates the value during the `.Set()` operation).
* Required flags have been the topic of much discussion, but are also not currently directly supported by the library (see #85 for more) . You can achieve similar results by validating that the flags are set after parsing using `Context.IsSet`..

Thank you for your interest! Just let me know if any of this is unclear.

I'll mark this as an enhancement with regard to the flag value restriction.

**Comment by lynncyrin** [comment]
Given that this is from last year, I think I'm comfortable closing it 🙂 feel free to re-open / open a new issue / comment in support if there's still interest here!

**Comment by rliebz** [comment]
@abdennour I re-opened and pinned #1154 (so it won't go stale), let me know if there's anything from this issue that warrants re-opening in addition.

**Comment by abdennour** [comment]
Thank you @rliebz  ! should this answer  https://github.com/urfave/cli/issues/602#issuecomment-416000118 cover this issue ?

**Comment by rliebz** [comment]
I think so, seems pretty straightforward.
