### ISSUE TITLE
No Error and exist code when using pkg/errors standard package

### ISSUE THREAD

**Issue by ehernandez-xk** [urfave/cli#632]
Hi All, 

Here is the snippet to reproduce the error

```go
package main

import (
	"errors"

	"github.com/urfave/cli"
)

var testCMD = cli.Command{
	Name: "test",
	Action: func(c *cli.Context) error {
		return errors.New("Error detected")
	},
}
```

Command line: (The error is not printed)
```bash
$ myApp test
$ echo $?
0
```

This issue was added in  https://github.com/urfave/cli/commit/9e5b04886c4bfee2ceba1465b8121057355c4e53 commit
and mentioned in https://github.com/urfave/cli/pull/496 PR

By the way, Thanks for this awesome package.

**Comment by ehernandez-xk** [comment]
I have noticed that only the errors of type ExitCoder interface will be managed
and the errors from the standard library are ignored

For example:

```go
  return cli.NewExitError("Error message", 1)
```

```go
  err := errors.New("errors")
  return cli.NewMultiError(err)
```

I think the standard errors should be used as well

**Comment by wenchma** [comment]
I  encountered this issue in mac system, but it is OK in linux system.

**Comment by jszwedko** [comment]
Hi @ehernandez-xk,

Apologies for the delay. #496 added functionality which was later deemed to be backwards incompatible and less flexible for users of the library, backed out in #595. Presently, if you want to have the application exit automatically, you should use `cli.NewExitError` as you note.

The error is bubbled up so you can still exit at the top-level if desired with something like:

```
package main                         

import (                             
        "errors"                     
        "fmt"                        
        "os"                         

        "github.com/urfave/cli"      
)                                    

var testCMD = cli.Command{           
        Name: "test",                
        Action: func(c *cli.Context) error {                               
                return errors.New("Error detected")                        
        },                           
}                                    

func main() {                        
        app := cli.NewApp()          

        app.Commands = []cli.Command{testCMD}                              

        err := app.Run(os.Args)      
        if err != nil {              
                fmt.Println(err)     
                os.Exit(1)           
        }                            
} 
```

`app.RunAndExitOnError` is provided as a convenience wrapper to automatically do this.

Let me know if this helps!

**Comment by ehernandez-xk** [comment]
Thank you @jszwedko
