### ISSUE TITLE
ERROR invalid Action type. 

### ISSUE THREAD

**Issue by Goooooooooogle** [urfave/cli#637]
I use `glide` to manage my dependency.

here is my code in `main.go`:
```
package main

import (
	"github.com/urfave/cli"
	"tmptest/service"
	"os"
)

func main() {
	app := cli.NewApp()
	app.Flags = []cli.Flag{
		cli.StringFlag{
			Name: "name, n",
		},
	}
	app.Action = service.RunAction
	app.Run(os.Args)
}

```

and bellow is `service` package:

```
package service

import (
	"github.com/urfave/cli"
	"fmt"
)

func RunAction(c *cli.Context) error {
	fmt.Println("Hello" + c.String("n"))
	return nil
}

```

when I run `go build` or `go install` ,no errors tips. and the command works fine. 

but when I push my project to github,and run `go get xxx` then run the command ,it tips me that:
```
ERROR invalid Action type. Must be `func(*Context`)` or `func(*Context) error).  This is an error in the application.  Please contact the distributor of this application if this is not you.See https://github.com/urfave/cli/blob/master/CHANGELOG.md#deprecated-cli-app-action-signature

```

what's wrong with that?

**Comment by josephlr** [comment]
So I was not able to reproduce this error.
I created https://github.com/josephlr/urfave-cli-test and used glide with your code, and then the following worked;
```bash
joerichey ~ > go get github.com/josephlr/urfave-cli-test
joerichey ~ > urfave-cli-test 
Hello
joerichey ~ > 
```

Perhaps the version of `github.com/urfave/cli` you are using is old or broken. I was using `v1.19.1`.

**Comment by Goooooooooogle** [comment]
my fault! thank you very much!  it's my first time push code to github ,and I place my code in `$GOPATH/src/test`, the right path is `$GOPATH/src/github/username/projectname`
