### ISSUE TITLE
Wildcard throw no matches found

### ISSUE THREAD

**Issue by rohmanhm** [urfave/cli#640]
What I do is just print the action `fmt.Println(action)`.
I want to get `*` string, but got error.

```bash
❯ go run calcall.go --action=*
zsh: no matches found: --action=*
```
Actually this fixed by changing `*` to `\*`. But I don't want this. Looks dirty.
```bash
❯ go run calcall.go --action=\*
*
```

Any solution please?

**Comment by meatballhat** [comment]
@rohmanhm Hello!  Your error message in the first example is coming from `zsh`. You will have to quote or escape the `*` in order for it to be considered by `calcall.go` 😃
