### ISSUE TITLE
[flags] Default value as defined ?

### ISSUE THREAD

**Issue by nikkolasg** [urfave/cli#642]
Hi,

I'm wrapper a wrapper around different sources for key/value pair and there's one problem I stumbled upon playing with cli.
When I defined a default value on a flag, and then call `IsSet(key)` on the context, it always return true. 
Is this intended ? Is there a way to know if somebody actually wrote the flag on the command line instead of just taking the default value ?
I would have expected this behavior instead:
+ returns `false` if the key has not been defined on the command line (at all) , even with default values
+ returns the default value when retrieving the value if the flag has not been written down on the command line by the user.

Nitpick aside, I think it's a very good framework, keep up the good work !

Nicolas

**Comment by jszwedko** [comment]
Hi @nikkolasg!

It is not intentional that `IsSet()` returns true for flags that have a default value (as all flags technically have a default value even if not explicitly set), could you provide an example failure case?

**Comment by nikkolasg** [comment]
Well, reading up on your answer one week after the fact, I re-read my code with a fresh mind and ... discovered this behavior is due to a bug of mine -_-"

Sorry for the false positive ;)

Nicolas
