### ISSUE TITLE
altsrc.NewStringSliceFlag won't parse the values from inputSource

### ISSUE THREAD

**Issue by VMitov** [urfave/cli#648]
I'm trying to get StringSliceFlag from file but it is failing to parse the values. 
The error I'm getting is `Mismatched type for flag 'list'. Expected '[]string' but actual is ''`

main.go:
```
func main() {
	app := &cli.App{
		Flags: []cli.Flag{
			altsrc.NewStringSliceFlag(&cli.StringSliceFlag{Name: "list"}),
			&cli.StringFlag{Name: "config", Value: "config.yaml"},
		},
		Action: func(c *cli.Context) error {
			fmt.Println(c.StringSlice("list"))
			return nil
		},
	}

	app.Before = altsrc.InitInputSourceWithContext(app.Flags, altsrc.NewYamlSourceFromFlagFunc("config"))
	app.Run(os.Args)
}
```
config.yaml : 
```
list:
    - s1
    - s2
```

**Comment by VMitov** [comment]
It looks like this is fixed in v1. Any idea when it will be merged in to v2?

**Comment by meatballhat** [comment]
@VMitov We're working on the latest v1 :arrow_right: v2 merge over in #655 :smiley_cat:

**Comment by VMitov** [comment]
Thanks!
