### ISSUE TITLE
update stable release on gopkg.in/urfave/cli.v1

### ISSUE THREAD

**Issue by MaximilianMeister** [urfave/cli#658]
there have been some commits to the `v1` branch which would be great to have in the stable release on `gopkg.in/urfave/cli.v1`

@jszwedko this is more of a ping than a real issue, sorry for the noise, it's a follow up of https://github.com/urfave/cli/pull/622#issuecomment-298846622

**Comment by jszwedko** [comment]
@MaximilianMeister apologies, I know this has been a long time coming, but I've finally tagged a new release as `v1.20.0`. I've captured all of the changes in the [CHANGELOG](https://github.com/urfave/cli/blob/master/CHANGELOG.md).

Thanks for keeping me honest!

**Comment by MaximilianMeister** [comment]
@jszwedko no worries, and thanks a lot
