### ISSUE TITLE
Is there a way to allow any arbitrary flags for a particular command?

### ISSUE THREAD

**Issue by treeder** [urfave/cli#663]
Currently you get: `Incorrect Usage: flag provided but not defined: -v` if a flag isn't defined, but what if you just want to accept anything so I can pass them along to another command?  That possible?

**Comment by ustcliao** [comment]
I have the same problem. When i tested main func with some test flag (go test  ***_test.go -v -x)
I got "Incorrect Usage. flag provided but not defined: -test.v"

Can I run app with unkown parameter?

**Comment by treeder** [comment]
I actually figured it out, set `SkipFlagParsing: true,` on the command.
