### ISSUE TITLE
Save state/context/history

### ISSUE THREAD

**Issue by carnufex** [urfave/cli#669]
Hi

I'd like to somehow save stuff(history/context/state?) in my cli application, is this in some way possible?

Example:
the variable "name" is default a string "test".

Cli command "change arg0"changes the name variable to whatever argument is provided.
Cli command "show" prints the name variable.

When running:

cli change WhatEver 
    -> "name is set to WhatEver"
cli show
    -> "name is test"

I'd like this to instead show me the name I earlier entered, in other words I want it to save the history.
cli show
    -> "name is WhatEver"

**Comment by jszwedko** [comment]
Hi @carnufex!

The library does not have direct support for state management / persistence (nor do I believe it would fall in the scope of this library). You will need to persist the information you care about yourself. I might recommend persisting it as a file; JSON, YML, or similar.

**Comment by carnufex** [comment]
I see, thank you for getting back to me @jszwedko .

**Comment by jszwedko** [comment]
No problem! Feel free to file issues for any additional questions.
