### ISSUE TITLE
Generate a Markdown Readme text based on commands and subcommands

### ISSUE THREAD

**Issue by Southclaws** [urfave/cli#671]
I'm not sure if this is a feature already but I couldn't find it.

I think it would be really cool if I could automatically generate some documentation for my CLI tool using this library. Documentation always has the risk of being out of date so generating it from source code is a great solution.

I'm not sure the best way of doing it but I was thinking a function you could bind to a built-in command much like `--version` that would output the generated markdown to stdout. It could then be run (either in CI or by hand) by compiling the app and running itself with `--generate-synopsys=README.md` or something!

It should be quite simple from what I can see:

```go

for _, command := range c.App.Commands {
    // output "## `<command name>`
    // iterate flags, output ### flags followed by a list with descriptions
    // iterate subcommands, output similar to above
    // maybe generate basic examples...?
}
```

**Comment by jszwedko** [comment]
This feature doesn't exist yet, but was also suggested in #340. I'll close this in lieu of that one, but please continue the discussion there! I think this would be a nice feature.
