### ISSUE TITLE
Limit help line length

### ISSUE THREAD

**Issue by vbogretsov** [urfave/cli#674]
Hello,

Is there a way to limit the help line length and automatically split help of an argument
or a command  on multiple lines with the correct indentation?

**Comment by jszwedko** [comment]
Hi @vbogretsov,

No, not currently, though it would be a good enhancement. I'll make this as such. Thanks for bringing it up!

**Comment by mostynb** [comment]
I added line-wrapping support in #287, but the terminal's width detection is not automatic (to avoid adding new dependencies/adding binary size). Here's an example of how client code can specify the line-wrap length: https://github.com/urfave/cli/pull/1119/files#diff-4d3f36d62cad94424544bb84fc93b33b73ffe3491a4ddca81a7f825539afc19cR1161-R1169

So I think we can close this now.
