### ISSUE TITLE
Somehow command help stopped showing up

### ISSUE THREAD

**Issue by stevenroose** [urfave/cli#678]
I have no idea what made it change, but somehow `myexec mycommand -h` does nothing while it used to print.

It happens with using v1.20.0 but not in latest master. However, `git diff v1.20.0` did not make me wiser..

**Comment by stevenroose** [comment]
Adding a custom `Before` function to the main app variable that checks the flag and calls `cli.ShowCommandHelp` doesn't work either. So something is ruining the help.

Again, in current master it works, but in v1.20.0 it doesn't. So releasing a v1.20.1 right now would be perfect (I'm using gopkg.in), even though I have no idea what code change causes this :D

**Comment by jszwedko** [comment]
Hi @stevenroose!

I'm unable to reproduce this with `v1.20.0`:

```
go run /tmp/tmp.go add -h
NAME:
   tmp add - add a task to the list

USAGE:
   tmp add [arguments...]
```

Using the subcommand example: https://github.com/urfave/cli#subcommands

Are you able to provide a more complete example that reproduces this issue? I want to make sure I understand the issue as I also don't see anything suspect in the diff.

Thanks!

**Comment by stevenroose** [comment]
@jszwedko Is there a reason not to release a v1.20.1? All users using gopkg.in are still on Aug 11, 2017 currently.
