### ISSUE TITLE
Escaping special characters in a user input

### ISSUE THREAD

**Issue by dmigwi** [urfave/cli#688]
Is there a mechanism in place to escape special characters like an apostrophe in the user input? If there is, how can I configure my cli implementation to escape an apostrophe and other special characters in a user input?

<img width="770" alt="screen shot 2017-11-25 at 22 25 25" src="https://user-images.githubusercontent.com/22055953/33233975-17c1e1c2-d230-11e7-867d-fd2145ac3854.png">

**Comment by jszwedko** [comment]
Hi @dmigwi,

Unfortunately, quoting characters are handled by the shell before the program (`amity-golang` in your case) is ever invoked so there isn't a way to disable their interpretation from the code itself. It may be possible to disable it at the shell level, but I haven't seen that done before.

Hope this helps!

**Comment by lynncyrin** [comment]
Given that this is from last year, I think I'm comfortable closing it 🙂 feel free to re-open / open a new issue / comment in support if there's still interest here!
