### ISSUE TITLE
PersistentFlags support

### ISSUE THREAD

**Issue by nkprince007** [urfave/cli#692]
Something similar to cobra's `PersistentFlag` would be a nice addition to save configuration to files.

**Comment by asahasrabuddhe** [comment]
@urfave/cli 

I think we already can achieve the `PersistentFlag` functionality through the global lookup functions in the cli context. Does any of you have any other use case in mind or can we close this?

**Comment by lynncyrin** [comment]
I don't quite grasp the use case, so I'm fine closing this until someone explicitly requests it again.

**Comment by AudriusButkevicius** [comment]
I guess this is saving a flag that was set in the previous invocation of the cli

**Comment by lynncyrin** [comment]
> I guess this is saving a flag that was set in the previous invocation of the cli

This what it sounds like 👍  this sounds like a nice feature, but given the age of this issue i'd like to close it until someone requests it again.

**Comment by AudriusButkevicius** [comment]
I don't think this should be a problem of this library. Users can implement their own persistence.

**Comment by chirino** [comment]
That's not what persistent flags do.  A persistent flag is a flag defined in a parent command, that can be use in any of the sub commands without having to repeat the flag in the sub command.  These a really useful for common  flags like `--verbose` that all sub commands will implement.
