### ISSUE TITLE
Subcommand short and long help

### ISSUE THREAD

**Issue by JordanKnott** [urfave/cli#694]
Is it possible to have a short and long version of help for a subcommand?

What I mean by this is for example, say I have a sub command called ```start```.
Whenever a user types ```--help```, it shows a shorten version of the usage like:

``` bash
$ tool --help
...
COMMANDS:
    start, s  Shorten version of usage goes here!
```

But if a user adds the ```--help``` flag to the command then it shows a longer version of the help text that
goes into more detail about the command.

Is this currently possible in cli?

**Comment by jszwedko** [comment]
Hi @JordanKnott,

I don't believe this is currently possible, but I'll mark it as an enhancement.
