### ISSUE TITLE
log bug

### ISSUE THREAD

**Issue by wuxiaoxiaoshen** [urfave/cli#695]
i use golang/log module （structure encapsulates）,  then go run main.go --help or go run main.go -h , something wrong like this:

Usage of /tmp/go-build241149055/command-line-arguments/_obj/exe/main:
  -plogdir=".": If non-empty, write log files in this directory
  -plogtostdout=true: log to standard error instead of files
  -pthreshold="DEBUG": threshold for logs output,e.g INFO,WARNING,ERROR,FATAL
exit status 2

how can i handle this ?

**Comment by jszwedko** [comment]
Hi @wuxiaoxiaoshen,

It's not clear to me what you are asking for. Would it be possible to provide a code sample, expected, and actual behavior?

**Comment by lynncyrin** [comment]
Closing pending more user feedback! If anyone wants to give more details here, I'll totally re-open this 👍
