### ISSUE TITLE
TimeFlag

### ISSUE THREAD

**Issue by LeonB** [urfave/cli#696]
I'd like to add a `cli.TimeFlag`. Is this something that would be accepted as a pull request?

Also, I would like to be able to specify the format of the time in the flag.

``` go
cli.TimeFlag{
	Name:  "date",
	Usage: "date",
	Format: "2016-01-02",
}
```

However, I can't specify an extra field `flag-types.json`. Should I create custom flag type in flag.go or should I add the possibility of adding extra fields in `generate-flag-types`?

**Comment by jszwedko** [comment]
Hi @LeonB,

I'd welcome the addition of a `TimeFlag` with a format specifier. I think we could modify the schema in `flag-types.json` to allow the specification of additional struct fields. To make it agnostic, we could just do something like:

```json
    {
      "name": "TimeFlag",
      "type": "time.Time",
      "context_default": "nil",
      "extra_fields": {
           "Format": "string",
       },
    }
```

What do you think?

Curious if you have any thoughts on that @meatballhat

**Comment by meatballhat** [comment]
@jszwedko I agree with you! :sparkling_heart:

**Comment by cgebe** [comment]
Would also welcome this feature!

**Comment by LeonB** [comment]
I don't know if the timeflag can be added because of the dependency on [`flag.FlagSet`](https://golang.org/pkg/flag/#FlagSet) which doesn't support time flags.

**Comment by lynncyrin** [comment]
Given that this is from last year, I think I'm comfortable closing it 🙂 feel free to re-open / open a new issue / comment in support if there's still interest here!
