### ISSUE TITLE
Alternate flags are counted in NumFlags()

### ISSUE THREAD

**Issue by parsiya** [urfave/cli#698]
Consider this minimal example:

``` go
package main

import (
	"fmt"
	"os"
	"github.com/urfave/cli"
)

func main() {
	app := cli.NewApp()
	os.Args = []string{"main", "-f1", "123"}
	app.Flags = []cli.Flag{
		cli.StringFlag{
			Name: "flag1, f1",
		},
		cli.StringFlag{
			Name: "flag2",
		},
	}
	app.Action = func(c *cli.Context) error {
		// Print number of flags
		fmt.Printf("c.NumFlags() = %d", c.NumFlags())
		return nil
	}

	app.Run(os.Args)
}
```

Output: `c.NumFlags() = 2`, meaning both `f1` and `flag1` are counted.

For `go run main.go -flag2 123` it will print `1`.

I could not see anything in the docs about this. After a brief look inside the source I see it returns `flagSet.NFlag`. And `eachName` function inside `ApplyWithError` sets a flag for each of the names (e.g. we are setting 2 flags for flag1).

``` go
func eachName(longName string, fn func(string)) {
	parts := strings.Split(longName, ",")
	for _, name := range parts {
		name = strings.Trim(name, " ")
		fn(name)
	}
}
```

Inside ApplyWithError

``` go
func (f GenericFlag) ApplyWithError(set *flag.FlagSet) error {
	val := f.Value
	if fileEnvVal, ok := flagFromFileEnv(f.FilePath, f.EnvVar); ok {
		if err := val.Set(fileEnvVal); err != nil {
			return fmt.Errorf("could not parse %s as value for flag %s: %s", fileEnvVal, f.Name, err)
		}
	}

	eachName(f.Name, func(name string) {
		set.Var(f.Value, name, f.Usage)
	})

	return nil
}
```

This looks like intended behavior. Is there a way to get the number of distinct flags set or do I have check manually? I did not see anything in godocs.

Thanks for a great package.

**Comment by jszwedko** [comment]
Hi @parsiya,

Thanks for the detailed explanation of the issue! I believe you are correct that it is a side-effect of the way that `cli` applies the flags to allow look-up by either name (i.e. `c.String("flag1")` or `c.String("f1")`), but I do not believe this behavior is intentional. I'll mark this issue as a bug to be investigated (a PR is welcome if you feel like taking a stab!).

Thanks!

**Comment by lynncyrin** [comment]
@asahasrabuddhe I'm un-assigning this since it's been sitting for a while, feel free to re-assign it to yourself if you stand up a PR for it

**Comment by lynncyrin** [comment]
This issue is currently marked as `help wanted` for anyone who wants to create a bug to update the behavior or add documentation! If nobody's interested in making the change here, I'll let this issue close as stale.
