### ISSUE TITLE
How to set the default setting

### ISSUE THREAD

**Issue by mingyard** [urfave/cli#700]
While I run .go file via Cli, I need key in "run web" command to start the web server. My question is how to set the default setting, so that the web server will start running automaticlly when I execute a .go file?

**Comment by jszwedko** [comment]
Hi @mingyard,

This is possible by pulling the command definition out and setting it as both the `app.Action` as well as the `Action` for the subcommand (see example on https://github.com/urfave/cli/issues/657).

Hope this helps!

**Comment by mingyard** [comment]
Oh, it does work. Cheers :)

**Comment by jszwedko** [comment]
Great! Thanks @mingyard
