### ISSUE TITLE
Print help message when no arguments provided

### ISSUE THREAD

**Issue by berkil** [urfave/cli#702]
Hi, 
- I would like to see an option to print the help usage when no arguments provided.
I have tried to use :
~~~
app.Action = func(c *cli.Context) error {
  if len(os.Args) == 1 {
    cli.ShowCommandHelp(c, "")
    return nil
}
~~~

---

But the output is not the same when using the `help` argument.
When using the `help` argument, I get this output:  
~~~
NAME:
   New CLI app

USAGE:
   cli [global options] [arguments...]

VERSION:
   0.1.2

AUTHOR:
   Boris Bakshiyev

COMMANDS:
     help, h  Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --help, -h                        show help
   --version, -v                     print the version
~~~

When I run it without any flags, it produces this output:
~~~
NAME:
   New CLI app

USAGE:
   cli [global options] [arguments...]

COMMANDS:
     help, h  Shows a list of commands or help for one command

OPTIONS:
   --help, -h                        show help
   --version, -v                     print the version
~~~

---

* The `GLOBAL OPTIONS` becomes `OPTIONS`.
* `VERSION` is missing.
* `AUTHOR` is missing.

---

Thanks in advance :-)

**Comment by jszwedko** [comment]
Hi @berkil ,

I'll admit the help system in `cli` is pretty confusing. I believe what you want is `c.ShowAppHelp(c)`.

Hope this helps!

**Comment by boristunity** [comment]
@jszwedko Thanks thats what I looked for 👍

**Comment by jszwedko** [comment]
Awesome, thanks @boristunity !
