### ISSUE TITLE
add a verbose mode for autocompletion on zsh

### ISSUE THREAD

**Issue by rautesamtr** [urfave/cli#708]
It would be great if `cli` could offer a more verbose autocompletion on zsh similar so the following examples:
![tar_interactive](https://user-images.githubusercontent.com/1131371/35619704-2237be8c-067f-11e8-8e57-fb635da66afd.png)
![pacman_interactive](https://user-images.githubusercontent.com/1131371/35619708-253d1ce4-067f-11e8-83a1-cc16d6c82563.png)

**Comment by jszwedko** [comment]
Agreed!

**Comment by dearchap** [comment]
@rautesamtr I think this could be implemented by the cli user by using a custom app/Command.BashCompletionFunc which would be triggered when completion is needed. cli gives users the choice to format completion in whatever way they need.
