### ISSUE TITLE
Only environment variables

### ISSUE THREAD

**Issue by devnut** [urfave/cli#709]
Is there a way to have a variable that is only set through an environment variable?

Thanks!

- Greg

**Comment by jszwedko** [comment]
Hi @devnut,

Unfortunately, not currently as the flags need to have a name to in order to fetch their value. I'd be open to a PR to support this behavior, but I expect it to be a little non-trivial given this and the fact that the help output would need to be reworked.

**Comment by lynncyrin** [comment]
Given that this is from last year, I think I'm comfortable closing it 🙂 feel free to re-open / open a new issue / comment in support if there's still interest here!

**Comment by axetroy** [comment]
Is there any plan? this is really useful

**Comment by dearchap** [comment]
Why even define it as a flag then ?
