### ISSUE TITLE
command flags usage

### ISSUE THREAD

**Issue by emicklei** [urfave/cli#716]
I found unexpected behavior when working with command related flags. Perhaps I misunderstand it. I wrote a minimal example.

```
go run main.go test -s flag -g
```

and read

```
2018/02/21 14:29:25 s= false
2018/02/21 14:29:25 g= true
```
Why is s not set ?  or what should the command line be ?

```
package main

import (
	"log"
	"os"

	"github.com/urfave/cli"
)

func main() {
	app := cli.NewApp()
	app.Commands = []cli.Command{
		{
			Name: "test",
			Flags: []cli.Flag{
				cli.BoolFlag{
					Name: "set, s",
				},
			},
			Subcommands: []cli.Command{
				{
					Name:   "flag",
					Action: cmdTestFlag,
					Flags: []cli.Flag{
						cli.BoolFlag{
							Name: "get, g",
						},
					},
				},
			},
		},
	}
	if err := app.Run(os.Args); err != nil {
		log.Fatalln(err)
	}
}

func cmdTestFlag(c *cli.Context) error {
	log.Println("s=", c.Bool("s"))
	log.Println("g=", c.Bool("g"))
	return nil
}
```

**Comment by daniel-nichter** [comment]
Had similar issue and `c.GlobalBool` worked. I can't find mention the docs but I think each `Command` has its own context, so `s` doesn't exist in the (sub)command context, and given,
> Bool looks up the value of a local BoolFlag, returns false if not found
accessing the bool var returns false not because it's actually false but because it doesn't exist in the context.

**Comment by juztin** [comment]
Just ran into this too... Expected a string flag from a parent being available from `GlobalString()` within a subcommand, but no dice =(

**Comment by lynncyrin** [comment]
I'm marking this as a bug since it's a bug from a user PoV! From the PoV of the CLI, it'd be nice if all flags were functionally "global" 👍  I would be very interested in reviewing any PRs for this! 🙏

**Comment by lynncyrin** [comment]
I've been thinking about this more, and I think we want to achieve this

> it'd be nice if all flags were functionally "global" 

with a config option, and then make that option the default value in v3. I'm tracking V3 here https://github.com/urfave/cli/issues/833

**Comment by lynncyrin** [comment]
I'm going to bucket this as a part of potential V3 work, and close this specific issue - but I fully intend on following up on this problem!
