### ISSUE TITLE
Why isn't MapInputSource.valueMap Exposed?

### ISSUE THREAD

**Issue by sargun** [urfave/cli#719]
If I want to write my own input sources, I need to either implement the full inputsource interface, or I can leverage MapInputSource. How come it's impossible to instantiate map input source from packages outside altsrc?

**Comment by sargun** [comment]
See a "fix" for this here: https://github.com/urfave/cli/pull/720

**Comment by lynncyrin** [comment]
Given that this is from last year, I think I'm comfortable closing it 🙂 feel free to re-open / open a new issue if there's still interest here!
