### ISSUE TITLE
Detect whether running in cli or as a service?

### ISSUE THREAD

**Issue by sssilver** [urfave/cli#725]
Hi,

Is there a mechanism to check whether my Go app has been invoked from the command-line interface directly, or spawned by systemd/sysvinit/etc as a service?

Thanks.

**Comment by asahasrabuddhe** [comment]
As far as I can tell, init or systemd have a PID of 1. I think we can use this for the check. Can anyone share an example usecase for this? I would be glad to take a look.

**Comment by xordspar0** [comment]
I don't think checking for PID 1 as a parent is necessarily a good idea in general. There could be other ways to start services. For example, desktop environments could autostart an application as a background service.

What kinds of thing would you want to do differently on the command line vs when running as a service? Many Unix applications check things like stdin and out: are they a terminal or just pipes? You could use that to change how log messages are displayed. [Logrus](https://github.com/sirupsen/logrus#logrus-) does this. There are probably many other ways to detect the environment around the app and react accordingly that don't involve checking the parent PID and making assumptions based on that.

**Comment by AudriusButkevicius** [comment]
https://github.com/mattn/go-isatty is what you want.
