### ISSUE TITLE
Unknown field 'FilePath' in struct literal of type cli.StringFlag

### ISSUE THREAD

**Issue by jooola** [urfave/cli#726]
When I try to add the FilePath element to a cli.StringFlag struct, I get the following message: 
```
Unknown field 'FilePath' in struct literal of type cli.StringFlag
```
Here is a part of the code : 
```go
        // [...]
	app.Flags = []cli.Flag{
		cli.BoolFlag{
			Name:   "verbose, v",
			Usage:  "Enable verbose mode",
			EnvVar: "AIRSONICCLI_VERBOSE",
		},
		cli.StringFlag{
			Name:     "config, c",
			Usage:    "Load configuration from `<file>`",
			EnvVar:   "AIRSONICCLI_CONFIG_PATH",
			FilePath: config.CONFIGPATH,
		},
		cli.StringFlag{
			Name:   "server, s",
			Usage:  "Specify server location `<server>[:<port>]`",
			EnvVar: "AIRSONICCLI_SERVER",
		},
        // [...]
```
I think there is something wrong on my side, but can't find anything wrong.

**Comment by VMitov** [comment]
I think what you want to do is:
```		cli.StringFlag{
			Name:     "config, c",
			Usage:    "Load configuration from `<file>`",
			EnvVar:   "AIRSONICCLI_CONFIG_PATH",
			Value: config.CONFIGPATH,
		},```

**Comment by jooola** [comment]
Yes this is what I had before. But how could I prevent using the configuration file when the flag isn't even used ?

I mean when I run : 
```sh
go run main.go ping
```
It automatically uses the configuration file if present and write a new one if doesn't exist. How can I do to not use the configuration file at all ?

**Comment by VMitov** [comment]
Don't put it at all or I'm missing something?

**Comment by jooola** [comment]
Here is what I need : 
If flag isn't used at all => Don't use configuration
If flag is used but without the file path (as boolean flag) => Use default value
If flag is used with the file path = > Use the specified value

But while writing this comment, it looks like I'm asking a bit too much.
Should I use a boolean flag and a string flag ?

Something like : 
```
-c                      Whether to use a configuration
--config-file        Path of the configuration file
```

**Comment by lynncyrin** [comment]
Given that this is from last year, I think I'm comfortable closing it 🙂 feel free to re-open / open a new issue / comment in support if there's still interest here!
