### ISSUE TITLE
Nested help: help config set vs config help set

### ISSUE THREAD

**Issue by arranubels** [urfave/cli#733]
Client has asked for same behaviour in both forms:
```help config set```
and
```config help set```
Unsure how to achieve this.

(They also want:
```config set help ```
But I'm sure I can just add it as a sub command)

**Comment by lynncyrin** [comment]
This sounds like a good feature to add at some point, if it's not possible already 👍

**Comment by lynncyrin** [comment]
This feature is now `in review`, @urfave/cli please add a 👍 or 👎 to the top post if you're in favor or against this feature being added!

**Comment by arranubels** [comment]
Aww

**Comment by dearchap** [comment]
@urfave/cli I think we need some policy on how to implement help. For example should we allow

```
app help cmd1 subcmd1 
```

alongside

```
app cmd1 help subcmd1 
app cmd1 subcmd1 help
app cmd1 subcmd1 -h
```

All of these should provide the same output and it is nontrivial to achieve that with current design

**Comment by abitrolly** [comment]
In my Python projects I never needed `help` command. But I needed `-h/--help` option to work correctly

```
app cmd1 subcmd1 -h      - show help for subcmd1
app cmd1 -h subcmd1      - show help cmd1
```

And make it both regardless of any other flags or arguments, which doesn't work this way.

I placed :-1: not because I am against extension of `help`, but because right now I believe `help` command should be opt-in.

**Comment by dearchap** [comment]
This has been fixes as part of multiple PRs, The following command sequences generate same output

App Help
```
app                      # shows app help if no action is defined
app -h                 
app help             
```

Command help
```
app help cmd1   
app cmd1 -h      
app cmd1 help   
```

Subcommand help
```
app cmd1 subcmd1 -h    
app cmd1 subcmd1 help
app cmd1 help subcmd1
```

Note that the help is only one nesting level deep so the following shows help only for cmd1
```
app help cmd1 subcmd1               # shows help for cmd1
```
