### ISSUE TITLE
Errors returned by subcommands are ignored by ExitErrHandler

### ISSUE THREAD

**Issue by roobre** [urfave/cli#736]
When a subcommand receiver outputs an error, app.ExitErrHandler is not called.

```go
func main() {
	app := cli.NewApp()
	app.Commands = []cli.Command{
		{
			Name:        "firstlevel",
			Action:      firstlevel,
		},
		{
			Name:        "parent",
			Subcommands: []cli.Command{
				{
					Name:        "sub1",
					Action:      sub1,
				}, {
					Name:        "sub2",
					Aliases: []string{"d"},
					Action:      sub2,
				},
			},
		},
	}

	app.ExitErrHandler = func(context *cli.Context, err error) {
		fmt.Println(err)
	}

	app.Run(os.Args)
}

// [...] all receivers return an error for this example
```

When an error is returned on firstlevel `firstlevel()`, it gets printed. However, if either sub1 or sub2 return it it is not. Not sure if this is a bug or I'm trying to do some weird things, but some insights would be appreciated anyway :)

**Comment by jkanywhere** [comment]
AppVeyer build is failing `go vet` failure which is also in master.
```
python runtests vet
45# github.com/urfave/cli
46.\command_test.go:328:3: value declared but not used
47vet: typecheck failures
48runtests: go vet ./...
...
```

**Comment by jkanywhere** [comment]
I opened https://github.com/urfave/cli/pull/763 to address the `go vet` error.

**Comment by lynncyrin** [comment]
Given that this is from last year, I think I'm comfortable closing it 🙂 feel free to re-open / open a new issue / comment in support if there's still interest here!
