### ISSUE TITLE
altsrc: Set flags without erroring out.

### ISSUE THREAD

**Issue by HaoZeke** [urfave/cli#742]
Basically I was wondering if there is a method to set flags only if the `.yml` file exists.

Currently it errors out (naturally, as the call is in app.Before) if the file is missing.

Is there any other way other than creating a default `.yml` file before checking for it?

**Comment by lynncyrin** [comment]
Hiya! There's a known issue with the current implementation of the CLI, where altsrc is generally clunky and poorly documented. My current idea is that I'm going to move all of the `altsrc` functionality into the main package in some way, and that's how all of the _"altsrc is weird and different???"_ issues people are having will get resolved. I'm tracking that work here => https://github.com/urfave/cli/issues/833

**Comment by HaoZeke** [comment]
I don't know if it's a good idea to close a bunch of issues without discussing and implementing fixes. It's counter intuitive and goes against the whole point of opening and reporting issues in the first place.

**Comment by HaoZeke** [comment]
These should ideally be kept open until they are resolved. It streamlines the discussion. A meta issue like the one you opened is not a bad idea either but not at the cost of the focused discussions which might take place on the original issue.

**Comment by AudriusButkevicius** [comment]
I disagree, if there is a general theme in a lot of issues, they should follow a general issue.

**Comment by HaoZeke** [comment]
Well, `altsrc` being weird and needing to be fixed is far too general a theme in my opinion, but then I've not used `cli` in ages anyway.

**Comment by lynncyrin** [comment]
It qualifies as a general theme in this particular case because I'm proposing we completely remove `altsrc` - which would make all the altsrc issues either disappear ✨ or become invalid since the code has changed so much 🌀
