### ISSUE TITLE
Misleading user error message when using flags

### ISSUE THREAD

**Issue by MichaelMure** [urfave/cli#744]
Hi,

As far as I understand, `cli` expect the root/global flags to be provided between the binary name and the subcommand name, and the command flags to be provided at the end:

```
binary-name [global options] command [command options] [arguments...]
```

As this pattern is not that common, it's easy for a new user to try to provide the root flags at the end of the command. In this case, he will be greeted with a rather unhelpful error message:

```
Incorrect Usage: flag provided but not defined: -host
```
Note that the message is the same when trying a flag that doesn't exist.

Would it be possible to get a more explanatory message in these cases ? I tried to make a workaround using `OnUsageError` but it's impractical for several reasons:
- you have to match and parse the error message
- it's not a simple error message rewrite, it's a different code path inside `cli` and you have to emulate some behavior like printing the help text manually
- you have to plug this workaround in every single command

**Comment by thedoc31** [comment]
Agreed. This format is not globally recognized and goes against how most CLIs work, where global options are not position-sensitive. This is extremely confusing, especially for experienced CLI end users.

**Comment by lynncyrin** [comment]
I understand that's going on here 👍 I would be happy to help someone with a pull request for this issue!

**Comment by lynncyrin** [comment]
I definitely agree that what we want is to allow global flags to be specified at any position. I'd love to see a PR for that, or for the issue of the misleading error message, or both!

**Comment by AudriusButkevicius** [comment]
Thats not true, I think kubectl also has position sensitive global flags, so we're not the only ones.

**Comment by lynncyrin** [comment]
Hey @MichaelMure & @thedoc31, this issue may have been fixed by our [v2 release](https://github.com/urfave/cli/releases/tag/v2.0.0)? Check it out and let me know what you think.

**Comment by thedoc31** [comment]
@lynncyrin I'll see if the internal project using the framework has plans to upgrade to v2. Thanks for following up!

**Comment by lynncyrin** [comment]
This issue is still waiting for someone to investigate if it's still a problem, and stand up a PR if so 🙏

**Comment by carhartl** [comment]
> This issue is still waiting for someone to investigate if it's still a problem

Still seeing it with v2:

```
go run main.go cmd --global foo
Incorrect Usage: flag provided but not defined: -global

NAME:
   main cmd

USAGE:
   main cmd command [command options] [arguments...]
```

with:

```go
package main

import (
	"fmt"
	"log"
	"os"

	"github.com/urfave/cli/v2"
)

func main() {
	app := &cli.App{
		Flags: []cli.Flag{
			&cli.StringSliceFlag{
				Name: "global",
			},
		},
		Commands: []*cli.Command{
			{
				Name: "cmd",
				Action: func(cCtx *cli.Context) error {
					fmt.Printf("Global flag: %s", cCtx.String("global"))
					return nil
				},
			},
		},
	}

	if err := app.Run(os.Args); err != nil {
		log.Fatal(err)
	}
}
```

**Comment by dearchap** [comment]
@carhartl Yes there havent been any fixes in this area so the issue will still be present. What is your expectation on the error in cases like this ?

**Comment by dearchap** [comment]
@carhartl That feature is present in v3 already. A flag can be marked persistent in which case it will flow through subcommands as well.

**Comment by bartekpacia** [comment]
Closing as per the comment above.
