### ISSUE TITLE
Display help menu

### ISSUE THREAD

**Issue by tochka** [urfave/cli#746]
I have a problem with print help information. I added arguments condition in  before function of parent command but when I wont to see help menu for subcommand it's show error.
```go
rootCmd:= &cli.Command{
   Name:"test",
  Flags: []*cli.Flag{
       &cli.StringFlag{
             Name:"path",
      },
   },
   Before: func (ctx *cli.Context) error{
       if !ctx.IsSet("path"){
             return fmt.Errorf("Path is required argument");
        }
       return . nil
   }
   Subcommands: []*cli.Command{
        &cli.Command{
             Name:"run",
        },
   }
}
```
Test
```bash
$ cli test run -h
Path is required argument
$
```

**Comment by lynncyrin** [comment]
Given that this is from last year, I think I'm comfortable closing it 🙂 feel free to re-open / open a new issue / comment in support if there's still interest here!
