### ISSUE TITLE
Missing HelpName in help text of the help command

### ISSUE THREAD

**Issue by genieplus** [urfave/cli#754]
The help text of the `help` command is not printing the command name:
```
$ go run urfavecli.go help help
NAME:
    - Shows a list of commands or help for one command

USAGE:
    [command options] [command]

OPTIONS:
   --help, -h  show help (default: false)
```

Rather, I am expecting something like: 
```
$ go run urfavecli.go help help
NAME:
   urfavecli help - Shows a list of commands or help for one command

USAGE:
    urfavecli help [command options] [command]

OPTIONS:
   --help, -h  show help (default: false)
```

This works fine with user command.

**Comment by lynncyrin** [comment]
Given that this is from last year, I think I'm comfortable closing it 🙂 feel free to re-open / open a new issue / comment in support if there's still interest here!
