### ISSUE TITLE
Arbitrarily get executed command info from Before/After function

### ISSUE THREAD

**Issue by Southclaws** [urfave/cli#756]
I'm integrating some basic analytics into a tool of mine and I'm wondering if there's a way to get the name of the command/subcommand purely via the Context in `app.Before` or `app.After`? I want to do this to avoid adding the analytics code to every single `Action` for every subcommand. Is there a way to do this?

I tried searching docs/issues but couldn't find anything, it's a bit of an odd query!

**Comment by lynncyrin** [comment]
Given that this is from last year, I think I'm comfortable closing it 🙂 feel free to re-open / open a new issue / comment in support if there's still interest here!
