### ISSUE TITLE
alias panics with uint64 flag

### ISSUE THREAD

**Issue by jeffrom** [urfave/cli#759]
noticed a similar issue to https://github.com/urfave/cli/issues/430, but with uint64 flags. when a uint64 flag has a name and an alias, running your command using the alias causes a panic. For example:

```go
var offsetFlag = &cli.Uint64Flag{
    Name:        "offset",
    Aliases:     []string{"s"},
    Usage:       "start reading messages from `OFFSET`",
    Value:       client.DefaultConfig.Offset,
    EnvVars:     []string{"LOG_OFFSET"},
    Destination: &tmpConfig.Offset,
}
```

causes:

```sh
panic: flag provided but not defined: -s
```

I have a working fix, similiar to https://github.com/urfave/cli/pull/432, but I'm not sure of the best way to test. It looks like it's probably a good idea to create use something similar to the `uint64FlagTests`, except using a flag struct as the input instead of just the name string.

**Comment by lynncyrin** [comment]
Given that this is from last year, I think I'm comfortable closing it 🙂 feel free to re-open / open a new issue / comment in support if there's still interest here!
