### ISSUE TITLE
Non-english / Other Languages (i18n) in CLI Apps ?

### ISSUE THREAD

**Issue by jsmith-dev** [urfave/cli#760]
Is there a 'standard' pattern / way to support multiple languages for the CLI msg out that the user interacts with?

We are using this library and want to support our users in 12+ languages used in message output.

**Comment by JimmyNovember** [comment]
Yeah, I think it would be good to have a systematic way to support multiple languages.

**Comment by lynncyrin** [comment]
Given that this is from last year, I think I'm comfortable closing it 🙂 feel free to re-open / open a new issue / comment in support if there's still interest here!
