### ISSUE TITLE
GO1.11: 1.20.0 unit tests do not pass

### ISSUE THREAD

**Issue by nim-nim** [urfave/cli#768]
golang-1.11-1.fc30.x86_64

```
Testing: "/builddir/build/BUILD/cli-1.20.0/_build/src/gopkg.in/urfave/cli.v1"
+ GOPATH=/builddir/build/BUILD/cli-1.20.0/_build:/usr/share/gocode
+ go test -buildmode pie -compiler gc -ldflags '-extldflags '\''-Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld '\'''
# gopkg.in/urfave/cli.v1
./app_test.go:500:6: parsedOption declared but not used
./app_test.go:500:20: firstArg declared but not used
vet: typecheck failures
FAIL	gopkg.in/urfave/cli.v1 [build failed]

```

**Comment by ffooffer** [comment]
> golang-1.11-1.fc30.x86_64
> 
> ```
> Testing: "/builddir/build/BUILD/cli-1.20.0/_build/src/gopkg.in/urfave/cli.v1"
> + GOPATH=/builddir/build/BUILD/cli-1.20.0/_build:/usr/share/gocode
> + go test -buildmode pie -compiler gc -ldflags '-extldflags '\''-Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld '\'''
> # gopkg.in/urfave/cli.v1
> ./app_test.go:500:6: parsedOption declared but not used
> ./app_test.go:500:20: firstArg declared but not used
> vet: typecheck failures
> FAIL	gopkg.in/urfave/cli.v1 [build failed]
> ```

**Comment by nim-nim** [comment]
I see it's fixed in a later commit, so I'll clode, it's a bit unfortunate this kind of fix does not get in a stable release, when you start skipping releases to use intermediary commits projects owners (rightfully) complain the result is not supposed to be stable
