### ISSUE TITLE
Error on default value

### ISSUE THREAD

**Issue by sunit-joshi** [urfave/cli#770]
I've a flag defined with default value of "n",

cli.StringFlag{
			Name:        "update, u",
			Usage:       "Load csv files into database `y/n`",
			Destination: &doUpdate,
			Value:       "n",
		}

However on running with -u (go run main.go -u) flag it prompts for a value.
ERROR: flag needs an argument: -u

thanks
SJ

**Comment by lynncyrin** [comment]
Given that this is from last year, I think I'm comfortable closing it 🙂 feel free to re-open / open a new issue if there's still interest here!
