### ISSUE TITLE
doing --version or --help prints version/help but doesn't Exit from program

### ISSUE THREAD

**Issue by ngashok** [urfave/cli#771]
When writing a simple program after including cli, the program doesn't exit after doing  ./commandline --version
I also tried, inside Action like this , but still doesn't exit from program
        if c.Bool("version") == true {
            return cli.NewExitError("", 86)
        }

# ./commandline --version
commandline version 1.0
**Hello Word**

**Comment by ddnomad** [comment]
Just checked, seems it exits correctly in my case. Your issue would definitely benefit from better formatting and a proper source code snippet (the one that causes a problem).

**Comment by lynncyrin** [comment]
Hiya! I'm not totally sure what the issue is here? If you can get back to us with a more thorough example + context, we can totally look into it 👍

**Comment by acrisci** [comment]
I'm getting this too. I should really fix this for you instead of posting my crappy workaround.

Anyway, here's my crappy workaround:

```go
	oldHelpPrinter := cli.HelpPrinter
	cli.HelpPrinter = func(w io.Writer, templ string, data interface{}) {
		oldHelpPrinter(w, templ, data)
		os.Exit(0)
	}

    oldVersionPrinter := cli.VersionPrinter
    cli.VersionPrinter = func(c *cli.Context) {
        oldVersionPrinter(c)
        os.Exit(0)
    }
```

**Comment by lynncyrin** [comment]
@acrisci can you create a new issue and link to this one? thank you!

**Comment by ayoisaiah** [comment]
@acrisci Thanks, this was helpful :)
