### ISSUE TITLE
Complete file name when there are no completion matches

### ISSUE THREAD

**Issue by segevfiner** [urfave/cli#780]
A common behavior for inaccurate/incomplete/auto-generated completion scripts is to complete file names when there are no completion matches, like the shells default behavior.

To enable for Bash, you simply add `-o default` to the `complete` call in the completion script. For Zsh, you can add something like this after trying to add the completions (There might be a better way to replicate this behavior in Zsh, but I didn't find any):
```zsh
if [[ $compstate[nmatches] -eq 0 && $words[$CURRENT] != -* ]]; then
    _files
fi
```

**Comment by yahavi** [comment]
Thank you sir!

**Comment by dearchap** [comment]
Works with latest release.
