### ISSUE TITLE
Is this project still maintained? It looks like it's in stale mode.

### ISSUE THREAD

**Issue by svett** [urfave/cli#789]
What are the plans for this project? Are you planing to release a new version? There are a lot of PRs and Issues that are neglected.

**Comment by michaeljs1990** [comment]
It does look dead to me. Hopefully someone on the project can hand it over to someone who cares or the community can just fork it and start merging in some of the outstanding PRs.

**Comment by michaeljs1990** [comment]
I emailed one of the maintainers to try and get some more info. I will let people know if I hear anything back.

**Comment by Xopherus** [comment]
Let me know if you ever receive a response @michaeljs1990, I'd be interested in helping.

**Comment by svett** [comment]
No worries guys. Actually I made my own implementation from scratch that I maintain.

**Comment by sssilver** [comment]
I don't think this issue should be closed. Is this project maintained or not?

**Comment by lynncyrin** [comment]
👀 in case news hasn't reached any of ya'll yet, the project is very well maintained now ✨
