### ISSUE TITLE
V2: Making `altsrc` flag optional in `Before:`

### ISSUE THREAD

**Issue by johnwyles** [urfave/cli#793]
Is there a way we can get an `altsrc` wrapper function to accomplish the following? Given that all of these features (env variables, flags, and config files) all override each other you do not want to mandate a configuration file be specified and instead make it OPTIONAL that it is specified:

In `test.go`:
```go
package main

import (
	"fmt"
	"os"

	cli "gopkg.in/urfave/cli.v2"
	"gopkg.in/urfave/cli.v2/altsrc"
)

func main() {
	flags := []cli.Flag{
		altsrc.NewStringFlag(
			&cli.StringFlag{
				Name:  "foo",
				Value: "BAR",
			},
		),
		&cli.StringFlag{
			Name: "load",
		},
	}

	app := &cli.App{

		Action: func(c *cli.Context) error {
			fmt.Printf("load: %s\n", c.String("load"))
			fmt.Printf("foo: %s\n", c.String("foo"))
			return nil
		},

		// This is seen all over and works but REQUIRES you provide "--load" and a TOML file
		// Before: altsrc.InitInputSourceWithContext(flags, altsrc.NewTomlSourceFromFlagFunc("load")),

		// Instead something like this would be desired:
		Before: altsrc.InitInputSourceWithContext(
			flags,
			func(context *cli.Context) (altsrc.InputSourceContext, error) {
				if context.IsSet("load") {
					return altsrc.NewTomlSourceFromFile(context.String("load"))
				}

				return &altsrc.MapInputSource{}, nil
			},
		),

		Flags: flags,
	}

	if err := app.Run(os.Args); err != nil {
		fmt.Errorf("An error occurred: %#v", err)
		os.Exit(1)
	}
}
```

In `test.toml`:
```toml
foo = "FOO"
```

And the above `test.go` will work as expected:

```shell
# Works as expected:
$ go run test.go
load:
foo: BAR

# Works as expected:
$ go run --foo OOF
load:
foo: OOF

# Works as expected:
$ go run test.go --load test.toml --foo OOF
load: test.toml
foo: OOF

# Works as expected:
$ go run test.go --load test.toml
load: test.toml
foo: FOO
```

**Comment by johnwyles** [comment]
I've actually run *further* into problems in that I would like to do more initialization in `Before:` after the configuration is loaded, but still before additional commands are loaded, so this is something I think that could be useful.

**Comment by johnwyles** [comment]
Note this issue may be resolved in https://github.com/urfave/cli/issues/800 and in PR https://github.com/urfave/cli/pull/801

**Comment by lynncyrin** [comment]
Hiya! There's a known issue with the current implementation of the CLI, where altsrc is generally clunky and poorly documented. My current idea is that I'm going to move all of the `altsrc` functionality into the main package in some way, and that's how all of the _"altsrc is weird and different???"_ issues people are having will get resolved. I'm tracking that work here => https://github.com/urfave/cli/issues/833
