### ISSUE TITLE
Will V2 ever be released? 

### ISSUE THREAD

**Issue by marwan-at-work** [urfave/cli#805]
The last commit in the v2 branch was over a year ago. Will v2 ever be officially released?

**Comment by cvigo** [comment]
Many think the project is abandoned

**Comment by marwan-at-work** [comment]
That's unfortunate. The V2 API is by far my favorite in comparison to other CLIs

**Comment by yihuaf** [comment]
Is there a fork being maintained? What's the alternative? I really like the api as well and would hate to see this get's abandoned.

**Comment by asahasrabuddhe** [comment]
This library is one of my favorites! I'll try to fork and do my bit. Let's see how it goes!

**Comment by marwan-at-work** [comment]
I think if any of the `urfave` team members could give those who like to maintain this project admin access, as that would ideal so that people will continue to use the same exact package and not forks of it.

**Comment by asahasrabuddhe** [comment]
I will try to contact the original team members and see where it leads to.

**Comment by patrickbsf** [comment]
@asahasrabuddhe any news?  I agree that this is one the nicer CLI libraries available.  It would be nice to get it back into a maintained fork with proper go modules and go context support.

**Comment by kneal** [comment]
We still waiting to here from maintainers?

**Comment by lynncyrin** [comment]
:wave: heya! We've got a few people who'd be interested in contributing to this project _(including myself!)_ Might any of the existing maintainers be able to help us along / provide context? I'm gonna cast a wide net with my pings here - I like this CLI and definitely want to see it be improved!

cc @codegangsta / @meatballhat / @AudriusButkevicius / @blaubaer / @jszwedko / @gravis / @jamescun / @muraty / @thesyncim / @tianon / @txgruppi

**Comment by marwan-at-work** [comment]
one more try: 

cc @codegangsta / @meatballhat / @AudriusButkevicius / @blaubaer / @jszwedko / @gravis / @jamescun / @muraty / @thesyncim / @tianon / @txgruppi

**Comment by klauern** [comment]
Whatever the end result is, please link to the fork in this issue so I know where to update my import paths. This is a fun, useful library, and I'll go wherever the developers are.

**Comment by AudriusButkevicius** [comment]
Everyone is free to fork it, have a v2 and maintain it.
There is a ton of PRs outstanding and no clear maintainer.

If you want to maintain this, you should speak up.
Sadly, I don't think I qualify as someone who can hand admin rights over, as my contribution was a single PR early on.

If there are particular PRs you want me to have a look shout, but I do not intend to properly maintain this.

**Comment by marwan-at-work** [comment]
@AudriusButkevicius see this comment: https://github.com/urfave/cli/issues/805#issuecomment-506621304

It would be best to hand over admin rights than to fork it so that we don't break users

That said, forking the repo is not a bad back up if no maintainer is willing to hand over rights to those in the community willing to maintain it. 

Thanks

**Comment by AudriusButkevicius** [comment]
I can see there are 5 people with owner rights, one of them is me, other two haven't had any activity in the last year, the two that had activity, which is @meatballhat  and @jszwedko. 

I guess I could add new members as non-admins and let them drive this and see how this goes.

**Comment by AudriusButkevicius** [comment]
I've created a new team, enabled enforcement of PR review by atleast 2 people, so ideally would like to gather multiple people, ideally from different companies etc to drive this forward. 

If we don't get the candidates stepping up, I guess we can drop it down to 1.
I don't however want "yolo I do whatever I want, self approve PRs and force push to master" stuff.

**Comment by gravis** [comment]
I don't see myself maintaining the V2, I just won't have enough time :(

**Comment by marwan-at-work** [comment]
@AudriusButkevicius that sounds great. We can start with adding @lynncyrin to the team (if you are still willing to contribute!) and whoever was also willing to make the version 2 release happen.

**Comment by asahasrabuddhe** [comment]
I am willing to put in the effort and contribute!

**Comment by lynncyrin** [comment]
> We can start with adding @lynncyrin to the team (if you are still willing to contribute!) and whoever was also willing to make the version 2 release happen.

🤚  I'm very interested! I've been wanting a go package to work on ^^

**Comment by lynncyrin** [comment]
> I've created a new team, enabled enforcement of PR review by atleast 2 people, so ideally would like to gather multiple people, ideally from different companies (or rather, unrelated with no shared agenda to plant backdoors) etc to drive this forward.

This is great thinking @AudriusButkevicius 👍👍👍

**Comment by lynncyrin** [comment]
If anyone interested in having a lower latency convo here, I'm in the `gophers` slack! It's pretty nice https://invite.slack.golangbridge.org/

**Comment by AudriusButkevicius** [comment]
I've invited you two to the team, let me know if you are able to review and close PRs. I thimk the first step would be to deal with the backlog of PRs.

**Comment by lynncyrin** [comment]
🎉📈🎉

I also consider open PRs my top priority! The triage order that I used when working on Bundler was

1. new open PRs
2. old open PRs
3. new issues
4. old issues
5. epics (like V2)

So it may be a while before I starting this particular issue (eg. V2), but "a while" here means "just a few weeks" 🙂

**Comment by lynncyrin** [comment]
To answer the title,

> Will V2 ever be released?

Yes it will be! You can talk about that here => https://github.com/urfave/cli/issues/826
