### ISSUE TITLE
better example of how to use altsrc

### ISSUE THREAD

**Issue by 4avka** [urfave/cli#807]
I had to look for quite a while to find something that was sufficiently clear that I felt confident I could use the feature. I found this, it looks quite new and even though it's half in chinese you can see how the thing works:

https://github.com/web-skeleton/skeleton

I also discovered that yaml at least v1 doesn't understand duration values. I switched to toml but I suspect yaml v2 understands durations?

What I have learned is it doesn't matter if the flag a config loads from is wrapped in an altsrc new flag (my configs contain their file location, for example) and this seems to be the best way to get a config to load from a file, but not directly from a flag string value (it uses it to construct one):

```go
		Before: func(c *cli.Context) error {

			fmt.Println("loading configuration")
			Configure(&podConfig)
			if FileExists(*podConfig.ConfigFile) {

				inputSource, err := altsrc.NewTomlSourceFromFile(*podConfig.ConfigFile)

				if err != nil {
					fmt.Println("error -", err)
					panic(err)
				}
				return altsrc.ApplyInputSourceValues(c, inputSource, c.App.Flags)
			}
			return nil
		},
```

**Comment by johnwyles** [comment]
@l0k1verloren Please also look at: https://github.com/urfave/cli/issues/800 https://github.com/urfave/cli/issues/793 and PR's https://github.com/urfave/cli/pull/802 https://github.com/urfave/cli/pull/803

**Comment by lynncyrin** [comment]
Hiya! There's a known issue with the current implementation of the CLI, where altsrc is generally clunky and poorly documented. My current idea is that I'm going to move all of the `altsrc` functionality into the main package in some way, and that's how all of the _"altsrc is weird and different???"_ issues people are having will get resolved. I'm tracking that work here => https://github.com/urfave/cli/issues/833
