### ISSUE TITLE
add autoloading zsh completion

### ISSUE THREAD

**Issue by gnowxilef** [urfave/cli#810]
`#compdef $PROG` needs to be added to the first line of the zsh completion file to support autoloading.

https://github.com/urfave/cli/blob/master/autocomplete/zsh_autocomplete

**Comment by lynncyrin** [comment]
I don't know how zsh completion works offhand, but it looks like this should be an easy change! Do you want to add it @gnowxilef?

**Comment by gnowxilef** [comment]
sure, i'll work on it when i get some time.

**Comment by lynncyrin** [comment]
Unassigning since it's been a few weeks! This issue is up for grabs again ^^

**Comment by ruzaikr** [comment]
Let me give this a shot! @lynncyrin

**Comment by lynncyrin** [comment]
@ruzaikr after https://github.com/urfave/cli/pull/984 is done, sure!

**Comment by gnowxilef** [comment]
oh, this is already taken care of by https://github.com/urfave/cli/pull/906.
