### ISSUE TITLE
unknown field 'FilePath' in struct literal of type cli.StringFlag

### ISSUE THREAD

**Issue by coderdba** [urfave/cli#811]
Error during compilation: 
unknown field 'FilePath' in struct literal of type cli.StringFlag

Code: (similar to the one in readme.md)
    cli.StringFlag{
      Name: "password, p",
      Usage: "password for the database",
      FilePath: "/tmp/dbpass",
    },

**Comment by kentaro-a** [comment]
Are you currently using v2 branch?
Assume above,I think there are no field like "FilePath" in cli.StringFlag in v2 composite to v1. 
Try v1 with $ go get gopkg.in/urfave/cli.v1

**Comment by lynncyrin** [comment]
@coderdba hiya! I don't if this is still an issue, but I'll try and verify that soon (unless someone else gets to this first)

**Comment by liamchampton** [comment]
@coderdba with the latest update `v1.21.0` this is fixed!
