### ISSUE TITLE
subcommand doesn't support custom usage

### ISSUE THREAD

**Issue by fred214** [urfave/cli#813]
When I defined UsageText in subcommand, I found it doesn't work.
Is that subcommand doesn't support custom usage?

**Comment by lynncyrin** [comment]
I don't know the answer to this offhand, but my experience is that the help text could definitely use a lil bit of cleanup 👍

**Comment by dearchap** [comment]
Unable to reproduce. We have unit tests for this and the template engine supports UsageText from App & Command as well.
