### ISSUE TITLE
Exit code

### ISSUE THREAD

**Issue by huanlingkeji** [urfave/cli#820]
package main

import (
  "log"
  "os"

  "github.com/urfave/cli"
)

func main() {
  app := cli.NewApp()
  app.Flags = []cli.Flag{
    cli.BoolTFlag{
      Name:  "ginger-crouton",
      Usage: "is it in the soup?",
    },
  }
  app.Action = func(ctx *cli.Context) error {
    if !ctx.Bool("ginger-crouton") {
      return cli.NewExitError("it is not in the soup", 86)
    }
    return nil
  }

  err := app.Run(os.Args)
  if err != nil {
    log.Fatal(err)
  }
}

the line of 13 should be 		cli.BoolFlag{   not 		cli.BoolTFlag{

**Comment by xordspar0** [comment]
This is about [the exit code section of the README](https://github.com/urfave/cli/blob/master/README.md#exit-code).

I agree. The purpose of this example is to show that you can exit with an error code if a flag is unspecified, but with the code as it is, the only way to cause a non-zero exit is by adding the flag `--ginger-crouton=false`, which is not explained in the example.

I made a PR for this change:
