### ISSUE TITLE
Man page generation

### ISSUE THREAD

**Issue by saschagrunert** [urfave/cli#821]
Hey there :wave:, do you think it would be possible to generate a man page directly from the command line flags?

**Comment by lynncyrin** [comment]
Hiya @saschagrunert! It sounds like you're looking for the same feature that this issue describes? https://github.com/urfave/cli/issues/340

**Comment by saschagrunert** [comment]
Yeah then let’s close this one.

**Comment by saschagrunert** [comment]
Yeah then let’s close this one.
