### ISSUE TITLE
Release 1.21.0

### ISSUE THREAD

**Issue by lynncyrin** [urfave/cli#824]
The last release was `1.20.0` about 2 years ago https://github.com/urfave/cli/commit/cfb38830724cc34fedffe9a2a29fb54fa9169cd1 - so releasing a new version of the CLI (`1.21.0`) will be a bit of an "event". I'm creating this ticket to track it, so people know it's coming - can collect feedback and any potential hotfixes.

**Comment by lynncyrin** [comment]
I'll create the release this weekend 👍

**Comment by tsingson** [comment]
this gopkg.in/urfave/cli.v2 is working fine for me in product about half year.

**Comment by lynncyrin** [comment]
@tsingson thanks for that feedback! I'm going to try to make v2 that "canonical" version as soon as I have capacity for that work (definitely in the next month or so).

**Comment by russoj88** [comment]
@lynncyrin I'm trying to use this in a new project (using go modules), but am receiving the following error.  I also tried updating an existing project, but it failed with a similar error.
```shell
# go get gopkg.in/urfave/cli.v1
go: gopkg.in/urfave/cli.v1@v1.21.0: go.mod has non-....v1 module path "github.com/urfave/cli" at revision v1.21.0
go: error loading module requirements
```

**Comment by lynncyrin** [comment]
@russoj88 can you open a new issue describing your problem? This is issue is closed, so your comment is likely to get lost.

**Comment by russoj88** [comment]
@lynncyrin done: #859
