### ISSUE TITLE
Documenting the intention of `altsrc`

### ISSUE THREAD

**Issue by lynncyrin** [urfave/cli#825]
Speaking as someone who is now partially responsible for helping with this project (along with everyone else) - it would be nice if there was a canonical document describing `altsrc`. Is it:

- intended to be merged into the "main" package eventually?
- do people think of it as a separate package, or an extension?
- should every PR we create be updating both "main" and `altsrc`?

**Comment by Project0** [comment]
Personally i would like to see `altsrc` as an "extension" (interface) which can be used by developers to add more config sources. I have a common use case to retrieve parameters first in AWS SSM and then continue with environment vars and flags. 
For creating an own altsrc package (i guess you mean a split to a new repo?) wouldn't this mean some kind of API stability?

**Comment by lynncyrin** [comment]
> Personally i would like to see altsrc as an "extension" (interface) which can be used by developers to add more config sources. I have a common use case to retrieve parameters first in AWS SSM and then continue with environment vars and flags.

I also understand it as an extensions interface, yeah. I think it we renamed the functionality to revolve around extensions, it would help with understanding and adoption.

> For creating an own altsrc package (i guess you mean a split to a new repo?) wouldn't this mean some kind of API stability?

I'm not sure what this means 🙂

**Comment by lynncyrin** [comment]
I think I'm going to bucket this into #833
