### ISSUE TITLE
Test for auto-generated code diffs in CI

### ISSUE THREAD

**Issue by lynncyrin** [urfave/cli#835]
this should happen after https://github.com/urfave/cli/issues/834

**Comment by asahasrabuddhe** [comment]
Already taken care of!

https://github.com/urfave/cli/blob/ac5c97b41844032ae47d5f94d7f73533af629f11/build/build.go#L162-L179

Notice that in the above function, we are calling the `git diff --exit code` command after code generation ensuring that in case of any diff, the command exits with error code 1 thereby failing the build.
