### ISSUE TITLE
StringFlag splits on $ sign

### ISSUE THREAD

**Issue by dkns** [urfave/cli#838]
Hello!

When reading input from string flag it splits on $ sign. E.g. running

`go run main.go --myflag foo$bar`

and then in code

`myFlag := c.String("myflag")`

returns `foo`

I was wondering if this is intended behaviour? Or is there a way to tell flag to parse it's value literally?

**Comment by asahasrabuddhe** [comment]
@dkns thanks for reporting this. I'll be taking a look into this shortly

**Comment by asahasrabuddhe** [comment]
Hi @dkns 

I have taken a look at this issue and I can confirm this is not a bug. What happens here is that your shell tries to parse $bar as a variable and as it is not defined, it evaluates to blank.

The following command confirms this theory:

```
go run main.go --myflag foo$bar
// foo

 bar="bar";go run main.go --myflag foo$bar
// foobar
```

Now, if you want to parse the foo$bar string literally, the solution is quiet simple. Wrap it in quotes!

```
go run main.go --myflag 'foo$bar'
// foo$bar
```

Regards,
Ajitem

**Comment by dkns** [comment]
@asahasrabuddhe thanks, that works! I tried passing string but wrapped in " which for some reason didn't work. Wrapping string in single quote works perfectly.
