### ISSUE TITLE
Remove python dependency in the build process (v2)

### ISSUE THREAD

**Issue by asahasrabuddhe** [urfave/cli#842]
implement #834 fir v2 branch

**Comment by lynncyrin** [comment]
✨ I believe this is finished! ✨

**Comment by marwan-at-work** [comment]
@lynncyrin is this done for `v2`? I still see the python script :) 

Not sure if this will work, but maybe merging v2 into master will automatically take care of things? I haven't looked into how the python script works but just hoping this is true.

**Comment by lynncyrin** [comment]
V2 is currently actively WIP => https://github.com/urfave/cli/pull/892, and yeah merging it into master will close this.

Similarly to other V2 specific feature PRs, this issue should be rolled up into https://github.com/urfave/cli/issues/826, so I'm gonna close this.
