### ISSUE TITLE
Required Flags

### ISSUE THREAD

**Issue by slantview** [urfave/cli#85]
It would be really nice to have required flags and required arguments.  I'm mostly putting this here as a place holder to discuss although I would be willing to put some work in on this if we can talk about how we would like to implement it.

I was thinking the easiest would just add a new field to the struct called "Required".  Internally we could have some checking and fail if the required flag is not set.

``` Go
type Flag interface {
    fmt.Stringer
    Required bool
    // Apply Flag settings to the given flag set
    Apply(*flag.FlagSet)
    getName() string
}

func (f *Flag) IsRequired() bool {
  return f.Required
}
```

**Comment by jhiemer** [comment]
+1

**Comment by assimovt** [comment]
:+1:

**Comment by radeksimko** [comment]
:+1:

**Comment by bbiskup** [comment]
+1

**Comment by stevvooe** [comment]
@codegangsta I am going to go against the tide here: if a flag is required, it should be a positional argument. Having required flags in the package promotes this anti-pattern. The suggestion in https://github.com/codegangsta/cli/issues/85#issuecomment-48777510 covers the use case. Perhaps, some helper functions could be added to cover the required use case, as well as cases where certain flags are required when others are set.

**Comment by szank** [comment]
I did check comment https://github.com/codegangsta/cli/issues/85#issuecomment-48777510, and for a StringFlag named "comment" I get : 
```go
fmt.Printf("comment : %#v\n", c.Generic("comment"))
```
```sh
#run app
./go run main.go
#result
comment : (*flag.stringValue)(0xc20802a9f0)
```
Is there any other way to check if flag is set ?
I wouldn't mind forking the code, adding 'required

**Comment by frodopwns** [comment]
I'd like to see a required flag that either automatically prints the command help when not present or prompts the user for the value.

**Comment by bwiggs** [comment]
Also looking for this feature. 

As for @stevvooe positional arguments: This becomes unfriendly to the user if there are more than a few required parameters. Imaging a cli app that needs to connect to a database, like `psql`. That would require a bunch of required parameters like username, password, host, port. If these were to be positional arguments, then the user would have to remember what order to append these when running the CLI. Using required params has the added benefit of providing labels for the user. This is more user friendly.

ex: 
```
$ psql localhost postgres postgres 5434
vs
$ psql -h localhost -d postgres -U postgres -p 5434
```

**Comment by jszwedko** [comment]
@bwiggs while I concede that this feature has some uses, your example of `psql` is slightly misleading because there are defaults for all of those flags, i.e. running `psql` with no args is the same as:

`psql -h /var/run/postgresql -d jszwedko -U jszwedko -p 5432` (using my username as an example).

I think, wherever possible, flags with default values are a better approach than required flags, but I can imagine use cases (some of which have been described above) where there are no sensible defaults and the value must be provided by the user.

I'm happy to review any pull request introducing this behavior (see #155 for a possible start).

Thanks!

**Comment by jingweno** [comment]
+1 to required flags

**Comment by stevvooe** [comment]
> As for @stevvooe positional arguments: This becomes unfriendly to the user if there are more than a few required parameters. Imaging a cli app that needs to connect to a database, like psql. That would require a bunch of required parameters like username, password, host, port. If these were to be positional arguments, then the user would have to remember what order to append these when running the CLI. Using required params has the added benefit of providing labels for the user. This is more user friendly.

@bwiggs pointed it out, but I wanted to expand on what I said above. `psql` is a perfect example of great cli design. With no arguments, it does something. username, password, host and port are not required parameters in psql. The only positional parameter is the database and username, which are not required. I can configured my environment or .pgsql such that the correct configuration can be picked up.

There are use cases, such as mutually exclusive parameters. Most of the time, these are just easier to implement directly in the command itself, as there may be a lot of application logic to make that decision and emit the correct error.

My main issue with required options is that we too often see tools like this:

```
cmd subcmd --path foo
```

Why should I have to write `--path` when it could be provided by a positional parameter? One may ask, what about more required parameters? Consider a way to do it with less parameters. I've never enjoyed using a tool with more than 3 required parameters that I enjoyed using. Notice that 3 is well within the bounds of using positional arguments. In tools that require such a ridiculous number of parameters (and they do sometimes), more than half of them tend to be the same on each invocation. At that point, just make a configuration file or pull options from the environment.

Required options just tend to lead to bad CLI design.

**Comment by charneykaye** [comment]
+1

**Comment by charneykaye** [comment]
+1.

I understand that for many, CLI primarily means a tool used by a single developer on the command line.

However, please consider applications that are deployed using other means yet still take "command line" arguments. My use case is an application that hosts a micro-service with HTTP hooks and connections to databases. I have three required flags:

    OPTIONS:
       --port                               REQUIRED <number> port to serve HTTP endpoints
       --redis-host                         REQUIRED <host:port> of Redis DB
       --mysql-dsn                          REQUIRED <user:pass@host/dbname> of MySQL DB

**Comment by obourdon** [comment]
+1

Most CLI libraries for other languages do support required arguments to ease up burden of CLI development and focusing on real added value ;-)

https://commons.apache.org/proper/commons-cli/apidocs/index.html
http://jcommander.org/#Required_and_optional
https://pholser.github.io/jopt-simple/examples.html

**Comment by wottah** [comment]
+1

**Comment by Asoseil** [comment]
+1

**Comment by krancour** [comment]
My biggest argument in favor of this feature is that sometimes a command or subcommand may require _many_ inputs. Allowing these inputs to be provided as the values of flags (as opposed to arguments) has a benefit in that no one needs to be aware of or honor a specific order in which they are entered. If one were to use flags in this manner, it follows that one would want the ability to define a flag as required.

+1

**Comment by jszwedko** [comment]
Agreed, #155 attempts to address this, but I haven't had the time to circle back around to finish the remaining issues with it.

**Comment by deepujain** [comment]
+1

**Comment by sirkon** [comment]
Github needs a way to put an unstar to project. Lack of `--required` and further opposition to this option deserves to be downvoted.

**Comment by gtaylor** [comment]
@sirkon This software is provided for free for yours (and everyone else's) benefit. There is nothing stopping you from contributing to the situation constructively by submitting a PR.

**Comment by brunson** [comment]
https://github.com/urfave/cli/pull/155  

This MR is about to turn 3 years old.  We should organize a party.

**Comment by jszwedko** [comment]
❤️ 

I'd love to see this feature added as there appears to be a pretty clear need. I unfortunately don't have the time lately to contribute it myself, but I'm happy to review PRs (I recommend starting from #155).

**Comment by wencan** [comment]
+1

**Comment by lynncyrin** [comment]
Oh hi 👋  I just noticed the `helpwanted` tag! I use this packages quite extensively @ work, and just finished a PR (https://github.com/sirupsen/logrus/pull/977) to a package I use in a similar context. So I'd like to help with this!

I'll start from here https://github.com/urfave/cli/pull/155 👍 Via creating a branch off on the most recent commit, rebasing, and working through the review comments 🔧

**Comment by lynncyrin** [comment]
I've started on this over here ~> https://github.com/urfave/cli/pull/819 feel free to drop me a comment if there's anything large that I've missed!

**Comment by lynncyrin** [comment]
If anyone is interested in helping with this, come check out my PR here https://github.com/urfave/cli/pull/819. It's ready for review 👀

**Comment by lynncyrin** [comment]
FYI for anyone that's only following this GitHub issue - I added this feature to the latest release https://github.com/urfave/cli/releases/tag/v1.21.0

**Comment by marwan-at-work** [comment]
@lynncyrin can we re-open this issue for the v2 branch? :)

**Comment by lynncyrin** [comment]
@marwan-at-work we'll be bringing v2 up to date "automatically" via merging master into it. Open issues are generally reserved for unique instances of work, that won't happen via other means.

So for instance, there would be a _"merge master into v2"_ issue - but not a _"merge feature 1, feature 2, feature 3, ... into v2"_ set of issues. The idea is that the _"merge feature"_ issues essentially duplicate the _"merge master"_ issue.

So I just updated the V2 release tracker issue (https://github.com/urfave/cli/issues/826) to reflect the fact that nobody is currently working on bringing V2 up to date with master, and that we could use some help with that. If nobody picks it up, I'll work on it after I fix this issue https://github.com/urfave/cli/issues/850.
