### ISSUE TITLE
Implement an interface for all errors, so they can be redefined by callers

### ISSUE THREAD

**Issue by lynncyrin** [urfave/cli#853]
Currently we return some error messages to end users, like

- "flag provided but not defined"
- "required flag not set"

But do not provide a way for people to re-define those error messages. We should implement some public interfaces for our errors, and provide documentation on how to implement custom error messages.

Related issues / PRs

- https://github.com/urfave/cli/issues/852
- https://github.com/urfave/cli/pull/656

**Comment by anberns** [comment]
I'd really like to work on this, but I'll probably need some guidance.

**Comment by lynncyrin** [comment]
That's fine! We can collaborate a bit, I need to do some learning here too 👩‍🎓

**Comment by lynncyrin** [comment]
Here's the best post I could find about error interfaces https://dave.cheney.net/2016/04/27/dont-just-check-errors-handle-them-gracefully

Here's a PR where I added an interface that essentially what I describe in the title https://github.com/urfave/cli/pull/819/, `requiredFlagsErr`.

The idea is that you would set `Flag.RequiredFlagsErr` (capital R now ^^) on a flag, and that interface would get called if there was an error with that flag. Feel free to ignore any complexities with your initial implementation, like the error message when there are errors with multiple flags.

**Comment by anberns** [comment]
Awesome! Thanks for the info. Starting on it now.

**Comment by anberns** [comment]
Quick question when you get a chance. Now that the `flag_generated.go` file is generated with `flag-gen` instead of the python script, what's the process for incorporating the necessary struct field and function for `RequiredFlagsErr`? Thanks.

**Comment by lynncyrin** [comment]
I reviewed that code but I don't specifically know what to point you to. You could ask @asahasrabuddhe, but it may be easier for both if ya'll if you dive into the code and explore it a bit. Or looking at the PR https://github.com/urfave/cli/pull/836

**Comment by anberns** [comment]
Yeah I spent several hours getting to know the codebase by investigating
this question. Don't worry, I don't reach out for things like this unless I
absolutely can't figure it out. I'll take another look at the PR you
mentioned and contact @asahasrabuddhe if necessary. Thanks!

**Comment by lynncyrin** [comment]
Also for context, I just made this issue => https://github.com/urfave/cli/issues/870

**Comment by anberns** [comment]
Ok cool. I'll just bypass the generation for now.

**Comment by lynncyrin** [comment]
Dropping this into the `status: in review` bucket, @urfave/cli please add a 👍 or 👎 to the top post if you're in favor or against this feature being added!

_(I'm counting the existing PR by `@anberns` as an exception here)_

**Comment by lynncyrin** [comment]
Closing this pending more buy in from maintainers
