### ISSUE TITLE
Dynamic autocompletion

### ISSUE THREAD

**Issue by zx8** [urfave/cli#855]
It would be fantastic if we could natively support https://github.com/posener/complete for more dynamic/self-contained autocompletion.

For reference, https://github.com/mitchellh/cli does this.

**Comment by lynncyrin** [comment]
@zx8 hi! I'm not totally sure what adding this would look like, but it sounds interesting! I would be happy to see a PR for this 🙏

**Comment by zx8** [comment]
I can probably put together a proposal/PR for this myself as I've implemented it before in another library.

That said, I'm slightly confused about the different branches/versions and where to branch off/merge back to? Could you clarify the difference between the following:
- `master`
- `v1` (assuming this == `master`?
- `v2`
- `v3`

Thanks!

**Comment by lynncyrin** [comment]
Create a branch off master, which is v1 yes

**Comment by lynncyrin** [comment]
Dropping this into the `status: in review` bucket, @urfave/cli please add a 👍 or 👎 to the top post if you're in favor or against this feature being added!

**Comment by lynncyrin** [comment]
FYI I'm working on a new policy where new feature suggestions need two 👍's before someone starts working on it, so don't stand up a PR for this now @zx8!

I have also proposed via https://github.com/urfave/cli/issues/826 that we not add any new features into `v1`. Given that nobody but me has chimed in on this issue yet, I'm comfortable moving it to the `v2` considerations. After `v2` is merged into master, I'll work on grabbing some other maintainers to see if they'd be interested in having this feature 📝

**Comment by lynncyrin** [comment]
Does this overlap with https://github.com/urfave/cli/pull/977 at all?

**Comment by dearchap** [comment]
Dynamic autocomplete is already present in 2.x.
