### ISSUE TITLE
Cannot Start New Project with Modules

### ISSUE THREAD

**Issue by russoj88** [urfave/cli#859]
I'm trying to use this in a new project (using go modules), but am receiving the following error. I also tried updating an existing project, but it failed with a similar error.  This is on PopOS 19.04 (Ubuntu 19.04), go 1.12.7.

main.go:
```go
package main

import (
	"gopkg.in/urfave/cli.v1"
	"log"
	"os"
)

func main() {
	err := cli.NewApp().Run(os.Args)
	if err != nil {
		log.Fatal(err)
	}
}
```
```shell
# go get gopkg.in/urfave/cli.v1
go: gopkg.in/urfave/cli.v1@v1.21.0: go.mod has non-....v1 module path "github.com/urfave/cli" at revision v1.21.0
go: error loading module requirements
```

This worked with cli 1.20.0.

**Comment by AudriusButkevicius** [comment]
You should use the github url, rather than gopkg.in

**Comment by lynncyrin** [comment]
👍 for using the GitHub URL, I have no idea how the gopkg.in url works

**Comment by russoj88** [comment]
That does work, but like the documentation says, that'll cause issues when v2 becomes master.

This is the section I'm referring to: https://github.com/urfave/cli#pinning-to-the-v1-releases

**Comment by lynncyrin** [comment]
The readme is outdated, pinning github has nothing to do with `v1` vs `v2`

**Comment by russoj88** [comment]
Got it.  Mind if I make an issue for outdated docs?

**Comment by AudriusButkevicius** [comment]
A pr would be more welcome

**Comment by russoj88** [comment]
I'd like to do a pr as well, but I think it'd just be me asking someone here what to put in.  If that's ok, I can start that now.

**Comment by lynncyrin** [comment]
@russoj88 yeah totally! go for it 👍
