### ISSUE TITLE
Bash completion: documentation not understandable

### ISSUE THREAD

**Issue by Osram-Gru** [urfave/cli#863]
Hello,

maybe it's just me, but I completely fail to understand https://github.com/urfave/cli#bash-completion .

Maybe you could put an end-to-end example in the documentation?

**Comment by lynncyrin** [comment]
That documentation was written quite some time ago, so it's likely aged :) I would appreciate any PRs updating it!

**Comment by masonj88** [comment]
I'm new here, but I'd love to help with this.  I can add a note for zsh too if that's still supported.

**Comment by lynncyrin** [comment]
@masonj88 go for it!
