### ISSUE TITLE
Panic on Unparsed arguments?

### ISSUE THREAD

**Issue by per9000** [urfave/cli#865]
I might have missed something trivial -- but it seems that unparsed arguments are silently swallowed. I would really appreciate if (1) unparsed arguments result in panic, or (2) I could manually detect unparsed arguments.

Basically my issue is that this panics (which is fine):
```text
$ ./unparsed hi --offset 7 --pickaxe diamond
Incorrect Usage: flag provided but not defined: -pickaxe
[...]
```

...but these two examples don't trigger panic when I would like them to (typically a user forgot the -- before the argument):
```text
$ ./unparsed hi offset 5
hello.

$ ./unparsed hi --offset 7 pickaxe diamond
hello.
```

Example code:
```go
package main

import (
	"fmt"
	"log"
	"os"

	"github.com/urfave/cli"
)

// myAction says hello
func myAction(ctx *cli.Context) error {
	fmt.Println("hello.")
	return nil
}

// Entry point
func main() {

	// setup the cli app
	app := cli.NewApp()

	offset := cli.Int64Flag{
		Name:  "offset, o",
		Usage: "Set offset.",
		Value: 0}

	// Commands
	app.Commands = []cli.Command{
		{
			Name:   "hi",
			Usage:  "Say hi.",
			Action: myAction,
			Flags: []cli.Flag{
				offset,
			},
		},
		{
			Name:   "hej",
			Usage:  "Say hej.",
			Action: myAction,
		},
	}

	// Run the program
	err := app.Run(os.Args)
	if err != nil {
		log.Fatal(err)
	}
}

```

**Comment by lynncyrin** [comment]
I understand that general idea of what you're asking for, and think it would be a good feature to have at some point 👍

_(I'm assuming we don't already have a feature that accomplishes this. We might? Someone should check!)_

There's just two clarifications I want to make:

- traditionally we want to `error` here, rather than `panic`
- we would want to add a configuration option to enable this behavior

**Comment by lynncyrin** [comment]
I was looking into something else, and I realized this

>  I could manually detect unparsed arguments

Is already possible! You can do this

```
	if len(c.Args()) != 0 {
		panic("unparsed arguments!")
	}
```

The contents of `c.Args` are any arguments that weren't converted to flags, so "unparsed arguments" like you mention @per9000

**Comment by lynncyrin** [comment]
Let me know if that doesn't work, and I'll re-open this ^_^

**Comment by per9000** [comment]
Works perfectly! Thanks!
