### ISSUE TITLE
glide install error

### ISSUE THREAD

**Issue by peterwillcn** [urfave/cli#866]
```
[ERROR]   Error scanning github.com/russross/blackfriday/v2: cannot find package "." in:
        /Users/mac/.glide/cache/src/https-github.com-russross-blackfriday/v2
[ERROR]   Failed to retrieve a list of dependencies: Error resolving imports
```
should use https://github.com/russross/blackfriday/releases/v2.0.1 instead?

**Comment by lynncyrin** [comment]
Hi @peterwillcn! Can you setup a github repo that reproduces this issue? I can't tell offhand what the problem is.

**Comment by peterwillcn** [comment]
@lynncyrin try this https://github.com/elastos/Elastos.ELA/tree/release_v0.3.2

**Comment by AudriusButkevicius** [comment]
Sadly we only commit to supporting go.mod, so you have to take this to glide developers, and if they say it's a package problem, take it to the problematic package.
