### ISSUE TITLE
Find out who uses this CLI

### ISSUE THREAD

**Issue by lynncyrin** [urfave/cli#869]
I'm interested in which popular OSS projects use this CLI! I just spotted `lego` https://github.com/go-acme/lego/blob/e820634e0e43baff0ef61728cb8379f804913b72/go.mod#L43

This list is super helpful https://godoc.org/github.com/urfave/cli?importers although I wish I could sort it but github stars

**Comment by lynncyrin** [comment]
Large Projects (>1k stars)

- https://github.com/go-acme/lego/blob/e820634e0e43baff0ef61728cb8379f804913b72/go.mod#L43
- https://github.com/go-gitea/gitea/blob/a678ea44b80812aaa97f8be2b94176bceaa8db4c/go.mod#L105
- https://github.com/docker/swarm/blob/6188ef5493c0561b9fbaaf8527f429583b99cbf0/vendor.conf#L9

**Comment by AudriusButkevicius** [comment]
syncthing uses it, yet not for the main process.

**Comment by saschagrunert** [comment]
CRI-O uses it too: https://github.com/cri-o/cri-o

**Comment by gesellix** [comment]
https://github.com/gesellix/couchdb-prometheus-exporter uses it

**Comment by lynncyrin** [comment]
👀 noticed another one! [aws/aws-lambda-go](https://github.com/aws/aws-lambda-go/blob/f7dba3f79cca0ce775c07c38db419e0da8d7ca64/go.mod)

**Comment by lynncyrin** [comment]
I'm gonna close this as a housekeeping thing, feel free to keep commenting on it though 🙏

**Comment by lynncyrin** [comment]
Another list, similarish to godoc's https://pkg.go.dev/github.com/urfave/cli?tab=importedby
