### ISSUE TITLE
Short flag name don't trigger required setting

### ISSUE THREAD

**Issue by errashe** [urfave/cli#878]
``` go
app.Flags = []cli.Flag{
    cli.StringSliceFlag{
      Name: "names, N",
      Required: true,
    },
  }
```

For example, flag setted as described, and i can write in terminal something like `cli --names qwe --names asd` - and that's fine. But also i should be able to write `cli -N qwe -N asd` and that's should work too, but i've got error.

`Required flag "names" not set`

**Comment by AudriusButkevicius** [comment]
A small repro would be nice, so we don't have to spend time crafting it up ourselves.

**Comment by errashe** [comment]
https://gist.github.com/errashe/2523b86554350a5e721ad015aecae796

Here we can run `go run t.go --names qwe --names asd` and that's will be fine. But if we try to use short tag - `go run t.go -N qwe -N asd` - got error (Required flag "names" not set).

**Comment by lynncyrin** [comment]
Thanks @errashe! That repro makes sense, I'm marking this as `help wanted` since it's a pretty obvious bug.
