### ISSUE TITLE
"Did you mean" hint on wrong command or flag

### ISSUE THREAD

**Issue by saschagrunert** [urfave/cli#895]
We could tell the user what the closest command or argument match is by calculating the [levenshtein distance](https://en.wikipedia.org/wiki/Levenshtein_distance) between them.

What to do you think?

**Comment by AudriusButkevicius** [comment]
Should be optional tho

**Comment by asahasrabuddhe** [comment]
Good idea for a new feature. I always loved how `git` suggests this to us in case of a typo. I also agree that this needs to be optional where a user can enable this probably by a boolean flag if they feel they need it for their CLI.

**Comment by lynncyrin** [comment]
I'd love this!!!

**Comment by lynncyrin** [comment]
Related to the conversation in https://github.com/urfave/cli/issues/826, I'd like to propose we only consider this feature for `v2` 🙏

**Comment by saschagrunert** [comment]
Sounds good, I suggest to use a third party library to provide the necessary algorithms around it.

**Comment by lynncyrin** [comment]
> Sounds good, I suggest to use a third party library to provide the necessary algorithms around it.

I'm in strong agreement here!

**Comment by saschagrunert** [comment]
I found three main packages which all seem a bit unmaintained:
- https://github.com/toldjuuso/go-jaro-winkler-distance
- https://github.com/xrash/smetrics
- https://github.com/antzucaro/matchr

From an implementation perspective I tend to use the [Jaro-Winkler distance](https://en.wikipedia.org/wiki/Jaro%E2%80%93Winkler_distance) to match the closet command/flag.

To start with a clean state I added go module support to matchr: https://github.com/antzucaro/matchr/pull/10

**Comment by lynncyrin** [comment]
This issue has a PR here! => https://github.com/urfave/cli/pull/977
