### ISSUE TITLE
ApplyInputSourceValues and subcommands

### ISSUE THREAD

**Issue by gchaincl** [urfave/cli#897]
Is it possible to ApplyInputSourceValues to every subcommand?
Meaning that each sub-command will ApplyInputSourceValues for it's own key on the file.

What I need to do is to be able to parse flags on each sub-commands using the same config file.

**Comment by lynncyrin** [comment]
I don't know offhand, and `altsrc` in general is poorly supported. I've created an issue describing a V3 release where we consider removing it => https://github.com/urfave/cli/issues/833

In the meantime, @gchaincl is there any workaround you can do to achieve the same behavior that you describe here?

**Comment by gchaincl** [comment]
@lynncyrin not really, but thanks for the response :+1:
