### ISSUE TITLE
Having arguments on a command with subcommands

### ISSUE THREAD

**Issue by mullerch** [urfave/cli#899]
As I understand how the framework works, if the argument matches a subcommand, it's executed as a subcommand. If not, the action is used and the argument is passed as an argument.

Is there a way to use have an argument on a command and using the second (or number n) argument as subcommand ?

This would allow to have such kind of syntax:

`directory person arnold address`

Where:
- directory: app name
- person: command of the app
- arnold: argument of the command 'person'
- address: subcommand of person

Actually the "only" possibilities are:

`directory person address arnold`

or

`directory person -p arnold address`

Is this possible in the actual implementation ?

**Comment by AudriusButkevicius** [comment]
https://github.com/urfave/cli/pull/112

Not sure if its still available, but shout if you can't work it out.
