### ISSUE TITLE
Create an automated version release system

### ISSUE THREAD

**Issue by coilysiren** [urfave/cli#923]
Because manual releases are boring to do.

**Comment by lynncyrin** [comment]
This will almost certainly be solved as a part of https://github.com/urfave/cli/issues/965 👀so I'm gonna assign @@j0n3lson to this too 📝

**Comment by j0n3lson** [comment]
Yeauuuuuuhhhh!

**Comment by meatballhat** [comment]
I'd like to call this something between done and wontfix since the current tooling available is _pretty OK_ (imho). [This doc](https://github.com/urfave/cli/blob/8996374f79c16d2bddff34778ffedc3e3262c13a/docs/RELEASING.md) talks about it in more detail.
