### ISSUE TITLE
Switch CI from travis?

### ISSUE THREAD

**Issue by lynncyrin** [urfave/cli#931]
My impression of CI systems in the recent past (eg. end of 2019) is that circleci has begun to surpass travis as the first choice for open source projects? Primarily because travis has started having very very long build queues.

This issue is about considering a switch from travis to circleci, all discussion and feedback is welcome!

**Comment by AudriusButkevicius** [comment]
There is also github actions, which can do builds and all of that stuff.

**Comment by lynncyrin** [comment]
Ah, and Github Actions just hit general availability this week! I'm super interested in that 🔍

**Comment by saschagrunert** [comment]
I’d be still in favor of CircleCI over GitHub actions because of the performance. But both are way better than Travis. 👍

**Comment by lynncyrin** [comment]
I think I'm gonna test out Github Actions for release automation (eg. https://github.com/urfave/cli/issues/923), it's a good fit and not performance intensive (since releases are rare).

**Comment by lynncyrin** [comment]
closed via https://github.com/urfave/cli/pull/970
