### ISSUE TITLE
release 1.22.x

### ISSUE THREAD

**Issue by coilysiren** [urfave/cli#933]
This is a tracking issue for work I do on the release `1.22.X` series. The v1 branch isn't getting any more feature requests, so the version will never increment above `1.22.X`.

The v1 branch can be found here: https://github.com/urfave/cli/tree/v1

Some discussion about the v1 vs v2 maintenance pattern can be found here: https://github.com/urfave/cli/issues/826

**Comment by lynncyrin** [comment]
The archive purposes:

- here's `1.22.1` from a few months ago https://github.com/urfave/cli/releases/tag/v1.22.1
- and here's `1.22.2` from last week https://github.com/urfave/cli/releases/tag/v1.22.2

**Comment by meatballhat** [comment]
Superseded by the [Release 1.22.7](https://github.com/urfave/cli/milestone/9) milestone.
