### ISSUE TITLE
Document how to combine flags from another package

### ISSUE THREAD

**Issue by coilysiren** [urfave/cli#948]
Closes #269

**Comment by leodotcloud** [comment]
There is no clean solution for v2. Request to re-open.

**Comment by lynncyrin** [comment]
@leodotcloud can you make a new issue describing the problem? This issue doesn't context enough context for someone to address it

**Comment by lynncyrin** [comment]
@leodotcloud or use #269, either way if you're interested in this it would help to contribute somewhere to ideas about how it should work, thank you ✨

**Comment by dearchap** [comment]
Will fix as part of #269
