### ISSUE TITLE
v1 bug: ( cannot use []cli.Author literal (type []cli.Author) as type []*cli.Author in assignment 0)

### ISSUE THREAD

**Issue by yezihack** [urfave/cli#949]
## Checklist

```
app.Authors = []cli.Author{{
		Name:"sgfoot",
		Email:"sgfoot2020@gmail.com",
}}
```
This code window10 system compilation error , but linux64 system compilation is ok, why?

**Comment by lynncyrin** [comment]
@yezihack there isn't nearly enough information here for me to help you, please fill out the entire issue template when creating a new issue. I'm closing this b/c there isn't enough detail here.

Also, just from the title

> cannot use []cli.Author literal (type []cli.Author) as type []*cli.Author in assignment

I can tell that you're probably missing an `&` somewhere.

**Comment by AudriusButkevicius** [comment]
I think you are mixing differenr versions of the library between the machines

**Comment by yezihack** [comment]
yes, mixing different version

**Comment by odiferousmint** [comment]
It does not work for me either, I get:

```
cannot use []*cli.Author literal (type []*cli.Author) as type []cli.Author in field value
```

I am using `"github.com/urfave/cli"`, without go modules.

**Comment by odiferousmint** [comment]
It does not work for me either, I get:

```
cannot use []*cli.Author literal (type []*cli.Author) as type []cli.Author in field value
```

For what it is worth, I straight out copied the code from https://github.com/urfave/cli/blob/master/docs/v2/manual.md.

```go
Authors: []*cli.Author{
  &cli.Author{
    Name:  "Example Human",
    Email: "human@example.com",
  },
},
```

I am using `github.com/urfave/cli`, without go modules.
Go version is `go1.13.5 linux/amd64`

**Comment by odiferousmint** [comment]
Make sure to run `go get -u github.com/urfave/cli` to update it if you are not using go modules.
