### ISSUE TITLE
Figure out how to release to gopkg.in

### ISSUE THREAD

**Issue by lynncyrin** [urfave/cli#962]
this is related to https://github.com/urfave/cli/issues/923

**Comment by asahasrabuddhe** [comment]
I think we do not need to do anything special to release to gopkg.in. Taking a look at this [page](https://labix.org/gopkg.in). There are two URL patterns supported:

```
gopkg.in/pkg.v3      → github.com/go-pkg/pkg (branch/tag v3, v3.N, or v3.N.M)
gopkg.in/user/pkg.v3 → github.com/user/pkg   (branch/tag v3, v3.N, or v3.N.M)
```

This is something we already follow this. Therefore, the following should work out well:

```
gopkg.in/urfave/cli.v1 -> v1 branch or v1.x.x release tags
gopkg.in/urfave/cli.v2 -> v2 branch or v2.x.x release tags
```

This would work very well for those not using Go Modules. I have also managed to reproduced this :


![Screenshot 2019-12-01 at 12 33 54 PM](https://user-images.githubusercontent.com/25657923/69910784-f934d480-1436-11ea-8db9-9b8462cb5789.png)
_Code Setup_

![Screenshot 2019-12-01 at 12 34 05 PM](https://user-images.githubusercontent.com/25657923/69910785-f934d480-1436-11ea-9477-aab5fac93c53.png)
_Output for v1_ 

![Screenshot 2019-12-01 at 12 34 44 PM](https://user-images.githubusercontent.com/25657923/69910791-0ce03b00-1437-11ea-83ed-70288b7af911.png)
_Output for v2_

**Comment by asahasrabuddhe** [comment]
I had disabled Go Modules for above project and instead used the project folder as the `GOPATH`

**Comment by lynncyrin** [comment]
Got it, so it sounds like people who want to download the package from gopkg.in are currently 100% capable of doing so 👍 So I'll close this ♻️
