### ISSUE TITLE
Consider using a "stale bot"

### ISSUE THREAD

**Issue by lynncyrin** [urfave/cli#968]
The bot => https://github.com/marketplace/stale

Checking on stale issues / PRs is currently something I do manually, and I would prefer it be automated

@urfave/cli I would like to stop having to do this manually, so I'm gonna implement this sometime after Dec 1st unless I get a 👎 react. Do also feel free to let me know if you're 👍 !

**Comment by asahasrabuddhe** [comment]
I think this is a good idea. It would certainly be more productive.

**Comment by lynncyrin** [comment]
@AudriusButkevicius I believe you now have an email from Github about this ✉️

**Comment by AudriusButkevicius** [comment]
I've approved it.
