### ISSUE TITLE
v2 feature: allow flags after arguments

### ISSUE THREAD

**Issue by jhford** [urfave/cli#976]
## Checklist

* [X] Are you running the latest v2 release? The list of releases is [here](https://github.com/urfave/cli/releases).
* [X] Did you check the manual for your release? The v2 manual is [here](https://github.com/urfave/cli/blob/master/docs/v2/manual.md)
* [X] Did you perform a search about this feature? Here's the [Github guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## What problem does this solve?

I am writing a program which is invoked by another program (openvpn up-script) and it is invoked in a very specific way.  I really like this library, so I'd like to be able to use it as a command line parser.  The problem is that it seems that all flags must appear before all options.

In my specific case, openvpn will always call your script with exactly 10 arguments, then you can configure it to pass additional arguments.  This would result in an os.Args similar to this:
`{"tun0", "1", "2"..."10", "--flush"}`.  The `--flush` is the flag that I'd like to be able to process with this library.

It seems like all flags either take no arguments (`BoolFlag`) or take one arugment (`StringFlag`).

I've needed this for other projects, but having it for this project would be really great.

## Solution description

an `os.Args` value of `{"a", "--bool-flag", "--string-flag", "abc", "b"}` should have:

* `ctx.Args() --> {"a", "b"}`
* `ctx.BoolFlag("bool-flag") --> true`
* `ctx.StringFlag("string-flag") --> "abc"`

## Describe alternatives you've considered

Not using this library for some of my projects

**Comment by AudriusButkevicius** [comment]
Habe you tried setting the flags on the root of the app rather than the command itself?

**Comment by AudriusButkevicius** [comment]
See #585

**Comment by kor44** [comment]
A lot of CLI tools supports flags after arguments. Today switch one of my application to this package and fount this feature is not supported.

**Comment by msmans** [comment]
@AudriusButkevicius #585 isn't the same as this issue. `v2` still doesn't allow for flags after positional arguments.

**Comment by belgaied2** [comment]
This is still a problem, @AudriusButkevicius is it possible to re-open this issue?

**Comment by trinitroglycerin** [comment]
@AudriusButkevicius ran into this today with v2 and v3 and noted that v1 had the desired behavior. Is there an appetite to re-open this?

We're looking to migrate an existing CLI off of cobra and to urfave/cli as this library is simpler, but it would be a breaking change to have to require all of our users to start placing their flags before the args.

**Comment by amalshaji** [comment]
Any updates on this issue? Will this be fixed in v3?

**Comment by dearchap** [comment]
We are still waiting on a flag parser replacement for this.

**Comment by BlueTree242** [comment]
I hope this is fixed soon

**Comment by dearchap** [comment]
Highly unlikely . We've decided to keep the current parser as it is . V3 had support for persistent flags which allows flags to be placed anywhere in the command chain (but not after args)

**Comment by BlueTree242** [comment]
Well I am using V3, even though it isn't documented, will this ever be added? It's such a basic thing and the user will most likely be confused why the flags aren't doing anything

**Comment by guiguan** [comment]
ya, please support flags anywhere

**Comment by fiatjaf** [comment]
I've opened an official feature request for this for v3, which is the only way maintainers will consider fixing it. Please upvote it if you still want it: https://github.com/urfave/cli/issues/1950

There is also a branch and a PR that kinda works linked there that I'm using myself.
